package billing_workflow

import (
	"context"
	"fmt"
	"strings"
	"time"

	"go-template/internal/domain"
	"go-template/utils/log"
)

type Scheduler struct {
	domain domain.Domain
}

func NewScheduler(domain domain.Domain) *Scheduler {
	return &Scheduler{
		domain: domain,
	}
}

func (s *Scheduler) Start(ctx context.Context) {
	go s.scheduleMonthlyInvoiceGeneration(ctx)
	go s.scheduleDailyOverdueCheck(ctx)
	go s.scheduleDailyReminders(ctx)
	// Note: Isolation check is handled separately by isolation workflow
	// go s.scheduleIsolationCheck(ctx)
}

func (s *Scheduler) scheduleMonthlyInvoiceGeneration(ctx context.Context) {
	log.WithContext(ctx).Info("Starting monthly invoice generation scheduler")

	for {
		now := time.Now()

		// Get auto-generate day from system settings
		autoGenerateDay := s.getInvoiceAutoGenerateDay()

		// Calculate next run
		nextRun := time.Date(now.Year(), now.Month(), autoGenerateDay, 0, 0, 0, 0, time.Local)
		if nextRun.Before(now) {
			nextRun = nextRun.AddDate(0, 1, 0)
		}

		duration := time.Until(nextRun)
		log.WithContext(ctx).Info(fmt.Sprintf("Next monthly invoice generation scheduled at %v (in %v)", nextRun, duration))

		select {
		case <-time.After(duration):
			year := nextRun.Year()
			month := int(nextRun.Month())
			err := s.domain.Workflow().Billing().TriggerGenerateMonthlyInvoices(ctx, year, month)
			if err != nil {
				log.WithContext(ctx).Error("Failed to trigger monthly invoice generation", err)
			} else {
				log.WithContext(ctx).Info("Monthly invoice generation triggered successfully")
			}
		case <-ctx.Done():
			log.WithContext(ctx).Info("Monthly invoice generation scheduler stopped")
			return
		}
	}
}

func (s *Scheduler) scheduleDailyOverdueCheck(ctx context.Context) {
	log.WithContext(ctx).Info("Starting daily overdue check scheduler")

	ticker := time.NewTicker(24 * time.Hour)
	defer ticker.Stop()

	for {
		select {
		case <-ticker.C:
			err := s.domain.Workflow().Billing().TriggerCheckOverdue(ctx, true)
			if err != nil {
				log.WithContext(ctx).Error("Failed to trigger overdue check", err)
			} else {
				log.WithContext(ctx).Info("Overdue check triggered successfully")
			}
		case <-ctx.Done():
			log.WithContext(ctx).Info("Daily overdue check scheduler stopped")
			return
		}
	}
}

func (s *Scheduler) scheduleDailyReminders(ctx context.Context) {
	log.WithContext(ctx).Info("Starting daily reminder scheduler")

	ticker := time.NewTicker(24 * time.Hour)
	defer ticker.Stop()

	for {
		select {
		case <-ticker.C:
			daysBeforeDue := s.getReminderDaysBeforeDue()
			daysAfterDue := s.getReminderDaysAfterDue()
			err := s.domain.Workflow().Billing().TriggerSendReminders(ctx, daysBeforeDue, daysAfterDue)
			if err != nil {
				log.WithContext(ctx).Error("Failed to trigger reminder sending", err)
			} else {
				log.WithContext(ctx).Info("Reminder sending triggered successfully")
			}
		case <-ctx.Done():
			log.WithContext(ctx).Info("Daily reminder scheduler stopped")
			return
		}
	}
}

func (s *Scheduler) getInvoiceAutoGenerateDay() int {
	setting, err := s.domain.SystemSetting().GetSetting(context.Background(), "invoice.auto_generate_day")
	if err != nil || setting == nil || setting.Value == nil || *setting.Value == "" {
		return 25
	}

	var day int
	if _, err := fmt.Sscanf(*setting.Value, "%d", &day); err != nil {
		return 25
	}

	if day < 1 {
		day = 1
	} else if day > 28 {
		day = 28
	}

	return day
}

func (s *Scheduler) getReminderDaysBeforeDue() []int {
	setting, err := s.domain.SystemSetting().GetSetting(context.Background(), "reminder.days_before_due")
	if err != nil || setting == nil || setting.Value == nil || *setting.Value == "" {
		return []int{3, 1}
	}

	days, err := parseDays(*setting.Value)
	if err != nil {
		return []int{3, 1}
	}

	return days
}

func (s *Scheduler) getReminderDaysAfterDue() []int {
	setting, err := s.domain.SystemSetting().GetSetting(context.Background(), "reminder.days_after_due")
	if err != nil || setting == nil || setting.Value == nil || *setting.Value == "" {
		return []int{1, 3, 7}
	}

	days, err := parseDays(*setting.Value)
	if err != nil {
		return []int{1, 3, 7}
	}

	return days
}

func (s *Scheduler) getGracePeriodDays() int {
	setting, err := s.domain.SystemSetting().GetSetting(context.Background(), "grace_period_days")
	if err != nil || setting == nil || setting.Value == nil || *setting.Value == "" {
		return 3
	}

	var day int
	if _, err := fmt.Sscanf(*setting.Value, "%d", &day); err != nil {
		return 3
	}

	if day < 1 {
		day = 1
	} else if day > 30 {
		day = 30
	}

	return day
}

func parseDays(s string) ([]int, error) {
	if s == "" {
		return []int{}, nil
	}

	parts := strings.Split(s, ",")
	days := make([]int, 0, len(parts))

	for _, part := range parts {
		part = strings.TrimSpace(part)
		var day int
		if _, err := fmt.Sscanf(part, "%d", &day); err != nil {
			continue
		}
		days = append(days, day)
	}

	return days, nil
}
