// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/registry.go

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	activity "go-template/internal/domain/activity"
	auth "go-template/internal/domain/auth"
	bandwidth_profile "go-template/internal/domain/bandwidth_profile"
	billing "go-template/internal/domain/billing"
	cash "go-template/internal/domain/cash"
	client "go-template/internal/domain/client"
	customer "go-template/internal/domain/customer"
	iface "go-template/internal/domain/iface"
	ippool "go-template/internal/domain/ippool"
	notification "go-template/internal/domain/notification"
	payment "go-template/internal/domain/payment"
	ping "go-template/internal/domain/ping"
	pppoe "go-template/internal/domain/pppoe"
	queue "go-template/internal/domain/queue"
	refund "go-template/internal/domain/refund"
	system_setting "go-template/internal/domain/system_setting"
	user "go-template/internal/domain/user"
	outbound_port "go-template/internal/port/outbound"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDomain is a mock of Domain interface.
type MockDomain struct {
	ctrl     *gomock.Controller
	recorder *MockDomainMockRecorder
}

// MockDomainMockRecorder is the mock recorder for MockDomain.
type MockDomainMockRecorder struct {
	mock *MockDomain
}

// NewMockDomain creates a new mock instance.
func NewMockDomain(ctrl *gomock.Controller) *MockDomain {
	mock := &MockDomain{ctrl: ctrl}
	mock.recorder = &MockDomainMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDomain) EXPECT() *MockDomainMockRecorder {
	return m.recorder
}

// Activity mocks base method.
func (m *MockDomain) Activity() activity.ActivityDomain {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Activity")
	ret0, _ := ret[0].(activity.ActivityDomain)
	return ret0
}

// Activity indicates an expected call of Activity.
func (mr *MockDomainMockRecorder) Activity() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Activity", reflect.TypeOf((*MockDomain)(nil).Activity))
}

// Auth mocks base method.
func (m *MockDomain) Auth() auth.AuthDomain {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Auth")
	ret0, _ := ret[0].(auth.AuthDomain)
	return ret0
}

// Auth indicates an expected call of Auth.
func (mr *MockDomainMockRecorder) Auth() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Auth", reflect.TypeOf((*MockDomain)(nil).Auth))
}

// BandwidthProfile mocks base method.
func (m *MockDomain) BandwidthProfile() bandwidth_profile.BandwidthProfileDomain {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BandwidthProfile")
	ret0, _ := ret[0].(bandwidth_profile.BandwidthProfileDomain)
	return ret0
}

// BandwidthProfile indicates an expected call of BandwidthProfile.
func (mr *MockDomainMockRecorder) BandwidthProfile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BandwidthProfile", reflect.TypeOf((*MockDomain)(nil).BandwidthProfile))
}

// Billing mocks base method.
func (m *MockDomain) Billing() billing.BillingDomain {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Billing")
	ret0, _ := ret[0].(billing.BillingDomain)
	return ret0
}

// Billing indicates an expected call of Billing.
func (mr *MockDomainMockRecorder) Billing() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Billing", reflect.TypeOf((*MockDomain)(nil).Billing))
}

// Cash mocks base method.
func (m *MockDomain) Cash() cash.CashDomain {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cash")
	ret0, _ := ret[0].(cash.CashDomain)
	return ret0
}

// Cash indicates an expected call of Cash.
func (mr *MockDomainMockRecorder) Cash() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cash", reflect.TypeOf((*MockDomain)(nil).Cash))
}

// Client mocks base method.
func (m *MockDomain) Client() client.ClientDomain {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Client")
	ret0, _ := ret[0].(client.ClientDomain)
	return ret0
}

// Client indicates an expected call of Client.
func (mr *MockDomainMockRecorder) Client() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Client", reflect.TypeOf((*MockDomain)(nil).Client))
}

// Customer mocks base method.
func (m *MockDomain) Customer() customer.CustomerDomain {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Customer")
	ret0, _ := ret[0].(customer.CustomerDomain)
	return ret0
}

// Customer indicates an expected call of Customer.
func (mr *MockDomainMockRecorder) Customer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Customer", reflect.TypeOf((*MockDomain)(nil).Customer))
}

// Interface mocks base method.
func (m *MockDomain) Interface() iface.InterfaceDomain {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Interface")
	ret0, _ := ret[0].(iface.InterfaceDomain)
	return ret0
}

// Interface indicates an expected call of Interface.
func (mr *MockDomainMockRecorder) Interface() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Interface", reflect.TypeOf((*MockDomain)(nil).Interface))
}

// IpPool mocks base method.
func (m *MockDomain) IpPool() ippool.IpPoolDomain {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IpPool")
	ret0, _ := ret[0].(ippool.IpPoolDomain)
	return ret0
}

// IpPool indicates an expected call of IpPool.
func (mr *MockDomainMockRecorder) IpPool() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IpPool", reflect.TypeOf((*MockDomain)(nil).IpPool))
}

// Notification mocks base method.
func (m *MockDomain) Notification() notification.NotificationDomain {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notification")
	ret0, _ := ret[0].(notification.NotificationDomain)
	return ret0
}

// Notification indicates an expected call of Notification.
func (mr *MockDomainMockRecorder) Notification() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notification", reflect.TypeOf((*MockDomain)(nil).Notification))
}

// Payment mocks base method.
func (m *MockDomain) Payment() payment.PaymentDomain {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Payment")
	ret0, _ := ret[0].(payment.PaymentDomain)
	return ret0
}

// Payment indicates an expected call of Payment.
func (mr *MockDomainMockRecorder) Payment() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Payment", reflect.TypeOf((*MockDomain)(nil).Payment))
}

// Ping mocks base method.
func (m *MockDomain) Ping() ping.PingDomain {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping")
	ret0, _ := ret[0].(ping.PingDomain)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockDomainMockRecorder) Ping() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockDomain)(nil).Ping))
}

// Pppoe mocks base method.
func (m *MockDomain) Pppoe() pppoe.PppoeDomain {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pppoe")
	ret0, _ := ret[0].(pppoe.PppoeDomain)
	return ret0
}

// Pppoe indicates an expected call of Pppoe.
func (mr *MockDomainMockRecorder) Pppoe() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pppoe", reflect.TypeOf((*MockDomain)(nil).Pppoe))
}

// Queue mocks base method.
func (m *MockDomain) Queue() queue.QueueDomain {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Queue")
	ret0, _ := ret[0].(queue.QueueDomain)
	return ret0
}

// Queue indicates an expected call of Queue.
func (mr *MockDomainMockRecorder) Queue() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Queue", reflect.TypeOf((*MockDomain)(nil).Queue))
}

// Refund mocks base method.
func (m *MockDomain) Refund() refund.RefundDomain {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refund")
	ret0, _ := ret[0].(refund.RefundDomain)
	return ret0
}

// Refund indicates an expected call of Refund.
func (mr *MockDomainMockRecorder) Refund() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refund", reflect.TypeOf((*MockDomain)(nil).Refund))
}

// SystemSetting mocks base method.
func (m *MockDomain) SystemSetting() system_setting.SystemSettingDomain {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SystemSetting")
	ret0, _ := ret[0].(system_setting.SystemSettingDomain)
	return ret0
}

// SystemSetting indicates an expected call of SystemSetting.
func (mr *MockDomainMockRecorder) SystemSetting() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SystemSetting", reflect.TypeOf((*MockDomain)(nil).SystemSetting))
}

// User mocks base method.
func (m *MockDomain) User() user.UserDomain {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "User")
	ret0, _ := ret[0].(user.UserDomain)
	return ret0
}

// User indicates an expected call of User.
func (mr *MockDomainMockRecorder) User() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "User", reflect.TypeOf((*MockDomain)(nil).User))
}

// Workflow mocks base method.
func (m *MockDomain) Workflow() outbound_port.WorkflowPort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Workflow")
	ret0, _ := ret[0].(outbound_port.WorkflowPort)
	return ret0
}

// Workflow indicates an expected call of Workflow.
func (mr *MockDomainMockRecorder) Workflow() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Workflow", reflect.TypeOf((*MockDomain)(nil).Workflow))
}
