package model

import (
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// InvoiceStatus represents the status of an invoice
type InvoiceStatus string

const (
	InvoiceStatusDraft     InvoiceStatus = "draft"
	InvoiceStatusSent      InvoiceStatus = "sent"
	InvoiceStatusPartial   InvoiceStatus = "partial"
	InvoiceStatusPaid      InvoiceStatus = "paid"
	InvoiceStatusOverdue   InvoiceStatus = "overdue"
	InvoiceStatusCancelled InvoiceStatus = "cancelled"
	InvoiceStatusRefunded  InvoiceStatus = "refunded"
)

// PaymentStatus represents the payment status of an invoice
type PaymentStatus string

const (
	PaymentStatusUnpaid   PaymentStatus = "unpaid"
	PaymentStatusPartial  PaymentStatus = "partial"
	PaymentStatusPaid     PaymentStatus = "paid"
	PaymentStatusOverpaid PaymentStatus = "overpaid"
)

// InvoiceType represents the type of invoice
type InvoiceType string

const (
	InvoiceTypeRecurring    InvoiceType = "recurring"
	InvoiceTypeInstallation InvoiceType = "installation"
	InvoiceTypeAdditional   InvoiceType = "additional"
	InvoiceTypeRefund       InvoiceType = "refund"
)

// InvoiceItemType represents the type of invoice item
type InvoiceItemType string

const (
	InvoiceItemTypeSubscription InvoiceItemType = "subscription"
	InvoiceItemTypeInstallation InvoiceItemType = "installation"
	InvoiceItemTypeEquipment    InvoiceItemType = "equipment"
	InvoiceItemTypeOther        InvoiceItemType = "other"
)

type Invoice struct {
	ID                  uuid.UUID     `json:"id" gorm:"type:uuid;primaryKey;default:gen_random_uuid()"`
	InvoiceNumber       string        `json:"invoice_number" gorm:"uniqueIndex;not null"`
	CustomerID          uuid.UUID     `json:"customer_id" gorm:"type:uuid;not null;index"`
	Customer            *Customer     `json:"customer,omitempty" gorm:"foreignKey:CustomerID;references:ID"`
	BillingPeriodStart  time.Time     `json:"billing_period_start" gorm:"not null"`
	BillingPeriodEnd    time.Time     `json:"billing_period_end" gorm:"not null"`
	BillingMonth        int           `json:"billing_month" gorm:"not null;index"`
	BillingYear         int           `json:"billing_year" gorm:"not null;index"`
	IssueDate           time.Time     `json:"issue_date" gorm:"not null;index"`
	DueDate             time.Time     `json:"due_date" gorm:"not null;index"`
	PaymentDeadline     *time.Time    `json:"payment_deadline"`
	Subtotal            decimal.Decimal `json:"subtotal" gorm:"type:decimal(12,2);not null;default:0"`
	TaxAmount           decimal.Decimal `json:"tax_amount" gorm:"type:decimal(12,2);not null;default:0"`
	DiscountAmount      decimal.Decimal `json:"discount_amount" gorm:"type:decimal(12,2);not null;default:0"`
	LateFee             decimal.Decimal `json:"late_fee" gorm:"type:decimal(12,2);not null;default:0"`
	TotalAmount         decimal.Decimal `json:"total_amount" gorm:"type:decimal(12,2);not null;default:0"`
	PaidAmount          decimal.Decimal `json:"paid_amount" gorm:"type:decimal(12,2);not null;default:0"`
	Status              InvoiceStatus `json:"status" gorm:"type:invoice_status;not null;default:'draft';index"`
	PaymentStatus       PaymentStatus `json:"payment_status" gorm:"type:payment_status;not null;default:'unpaid';index"`
	PaymentDate         *time.Time    `json:"payment_date"`
	PaymentMethod       string        `json:"payment_method"`
	InvoiceType         InvoiceType   `json:"invoice_type" gorm:"type:invoice_type;not null;default:'recurring';index"`
	IsAutoGenerated     bool          `json:"is_auto_generated" gorm:"default:false"`
	ReminderSentCount   int           `json:"reminder_sent_count" gorm:"default:0"`
	LastReminderSent    *time.Time    `json:"last_reminder_sent"`
	Notes               string        `json:"notes"`
	InternalNotes       string        `json:"internal_notes"`
	Items               []InvoiceItem `json:"items,omitempty" gorm:"foreignKey:InvoiceID;constraint:OnDelete:CASCADE"`
	CreatedBy           *uint         `json:"created_by" gorm:"index"`
	CreatedByUser       *User         `json:"created_by_user,omitempty" gorm:"foreignKey:CreatedBy;references:ID"`
	UpdatedBy           *uint         `json:"updated_by" gorm:"index"`
	UpdatedByUser       *User         `json:"updated_by_user,omitempty" gorm:"foreignKey:UpdatedBy;references:ID"`
	CreatedAt           time.Time     `json:"created_at" gorm:"autoCreateTime"`
	UpdatedAt           time.Time     `json:"updated_at" gorm:"autoUpdateTime"`
	DeletedAt           *time.Time    `json:"deleted_at,omitempty" gorm:"index"`
}

type InvoiceItem struct {
	ID                  uuid.UUID         `json:"id" gorm:"type:uuid;primaryKey;default:gen_random_uuid()"`
	InvoiceID           uuid.UUID         `json:"invoice_id" gorm:"type:uuid;not null;index"`
	ItemType            InvoiceItemType   `json:"item_type" gorm:"type:invoice_item_type;not null;default:'subscription';index"`
	Description         string            `json:"description" gorm:"not null"`
	ProfileID           *uuid.UUID        `json:"profile_id" gorm:"type:uuid;index"`
	Profile             *BandwidthProfile `json:"profile,omitempty" gorm:"foreignKey:ProfileID;references:ID"`
	Quantity            int               `json:"quantity" gorm:"not null;default:1"`
	UnitPrice           decimal.Decimal   `json:"unit_price" gorm:"type:decimal(12,2);not null;default:0"`
	Subtotal            decimal.Decimal   `json:"subtotal" gorm:"type:decimal(12,2);not null;default:0"`
	TaxRate             decimal.Decimal   `json:"tax_rate" gorm:"type:decimal(5,4);not null;default:0.1100"`
	TaxAmount           decimal.Decimal   `json:"tax_amount" gorm:"type:decimal(12,2);not null;default:0"`
	Total               decimal.Decimal   `json:"total" gorm:"type:decimal(12,2);not null;default:0"`
	IsProrated          bool              `json:"is_prorated" gorm:"default:false"`
	ProrationDays       *int              `json:"proration_days"`
	ProrationPercentage *decimal.Decimal  `json:"proration_percentage" gorm:"type:decimal(5,2)"`
	SortOrder           int               `json:"sort_order" gorm:"default:0;index"`
	CreatedAt           time.Time         `json:"created_at" gorm:"autoCreateTime"`
}

type InvoiceInput struct {
	CustomerID         uuid.UUID         `json:"customer_id" binding:"required"`
	BillingPeriodStart time.Time         `json:"billing_period_start" binding:"required"`
	BillingPeriodEnd   time.Time         `json:"billing_period_end" binding:"required"`
	IssueDate          time.Time         `json:"issue_date" binding:"required"`
	DueDate            time.Time         `json:"due_date" binding:"required"`
	InvoiceType        InvoiceType       `json:"invoice_type" binding:"required,oneof=recurring installation additional refund"`
	DiscountAmount     decimal.Decimal   `json:"discount_amount"`
	Notes              string            `json:"notes"`
	InternalNotes      string            `json:"internal_notes"`
	Items              []InvoiceItemInput `json:"items" binding:"required,min=1,dive"`
}

type InvoiceItemInput struct {
	ItemType            InvoiceItemType `json:"item_type" binding:"required,oneof=subscription installation equipment other"`
	Description         string          `json:"description" binding:"required"`
	ProfileID           *uuid.UUID      `json:"profile_id"`
	Quantity            int             `json:"quantity" binding:"required,min=1"`
	UnitPrice           decimal.Decimal `json:"unit_price" binding:"required"`
	TaxRate             decimal.Decimal `json:"tax_rate"`
	IsProrated          bool            `json:"is_prorated"`
	ProrationDays       *int            `json:"proration_days"`
	ProrationPercentage *decimal.Decimal `json:"proration_percentage"`
}

type InvoiceFilter struct {
	IDs            []uuid.UUID     `json:"ids"`
	InvoiceNumbers []string        `json:"invoice_numbers"`
	CustomerIDs    []uuid.UUID     `json:"customer_ids"`
	Statuses       []InvoiceStatus `json:"statuses"`
	PaymentStatuses []PaymentStatus `json:"payment_statuses"`
	InvoiceTypes   []InvoiceType   `json:"invoice_types"`
	BillingMonth   *int            `json:"billing_month"`
	BillingYear    *int            `json:"billing_year"`
	DueBefore      *time.Time      `json:"due_before"`
	DueAfter       *time.Time      `json:"due_after"`
	IssuedBefore   *time.Time      `json:"issued_before"`
	IssuedAfter    *time.Time      `json:"issued_after"`
	Search         string          `json:"search"`
	Page           int             `json:"page"`
	Limit          int             `json:"limit"`
}

func (f InvoiceFilter) IsEmpty() bool {
	return len(f.IDs) == 0 && len(f.InvoiceNumbers) == 0 && len(f.CustomerIDs) == 0 &&
		len(f.Statuses) == 0 && len(f.PaymentStatuses) == 0 && len(f.InvoiceTypes) == 0 &&
		f.BillingMonth == nil && f.BillingYear == nil && f.DueBefore == nil &&
		f.DueAfter == nil && f.IssuedBefore == nil && f.IssuedAfter == nil && f.Search == ""
}

// TableName specifies the table name for GORM
func (Invoice) TableName() string {
	return "invoices"
}

// TableName specifies the table name for GORM
func (InvoiceItem) TableName() string {
	return "invoice_items"
}

// IsOverdue checks if invoice is overdue
func (i *Invoice) IsOverdue() bool {
	if i.PaymentStatus == PaymentStatusPaid {
		return false
	}
	return time.Now().After(i.DueDate)
}

// RemainingAmount calculates the remaining amount to be paid
func (i *Invoice) RemainingAmount() decimal.Decimal {
	return i.TotalAmount.Sub(i.PaidAmount)
}

// CalculateTotals calculates invoice totals from items
func (i *Invoice) CalculateTotals() {
	subtotal := decimal.Zero
	taxTotal := decimal.Zero

	for _, item := range i.Items {
		subtotal = subtotal.Add(item.Subtotal)
		taxTotal = taxTotal.Add(item.TaxAmount)
	}

	i.Subtotal = subtotal
	i.TaxAmount = taxTotal
	i.TotalAmount = subtotal.Add(taxTotal).Sub(i.DiscountAmount).Add(i.LateFee)
}

// CalculateItemTotals calculates item totals
func (item *InvoiceItem) CalculateItemTotals() {
	// Calculate subtotal
	item.Subtotal = item.UnitPrice.Mul(decimal.NewFromInt(int64(item.Quantity)))

	// Apply proration if needed
	if item.IsProrated && item.ProrationPercentage != nil {
		item.Subtotal = item.Subtotal.Mul(*item.ProrationPercentage).Div(decimal.NewFromInt(100))
	}

	// Calculate tax
	item.TaxAmount = item.Subtotal.Mul(item.TaxRate)

	// Calculate total
	item.Total = item.Subtotal.Add(item.TaxAmount)
}

// GenerateInvoiceNumber generates a unique invoice number
func GenerateInvoiceNumber(year int, month int, sequence int) string {
	prefix := time.Date(year, time.Month(month), 1, 0, 0, 0, 0, time.UTC).Format("INV/2006/01/")
	seqStr := ""
	num := sequence

	// Convert number to string
	if num == 0 {
		seqStr = "0"
	} else {
		for num > 0 {
			digit := num % 10
			seqStr = string(rune('0'+digit)) + seqStr
			num /= 10
		}
	}

	// Pad left with zeros
	for len(seqStr) < 4 {
		seqStr = "0" + seqStr
	}

	return prefix + seqStr
}
