package model

import (
	"time"

	"github.com/google/uuid"
)

type Invoice struct {
	ID                 uuid.UUID  `json:"id" gorm:"type:uuid;primaryKey;default:gen_random_uuid()"`
	InvoiceNumber      string     `json:"invoice_number" gorm:"unique;not null;size:50" validate:"required"`
	CustomerID         uuid.UUID  `json:"customer_id" gorm:"type:uuid;not null" validate:"required"`
	Customer           *Customer  `json:"customer,omitempty" gorm:"foreignKey:CustomerID"`
	BillingPeriodStart time.Time  `json:"billing_period_start" gorm:"not null;type:date" validate:"required"`
	BillingPeriodEnd   time.Time  `json:"billing_period_end" gorm:"not null;type:date" validate:"required"`
	BillingMonth       *int       `json:"billing_month" gorm:"type:integer"`
	BillingYear        *int       `json:"billing_year" gorm:"type:integer"`
	IssueDate          time.Time  `json:"issue_date" gorm:"not null;type:date" validate:"required"`
	DueDate            time.Time  `json:"due_date" gorm:"not null;type:date" validate:"required"`
	PaymentDeadline    *time.Time `json:"payment_deadline" gorm:"type:timestamp"`
	Subtotal           float64    `json:"subtotal" gorm:"not null;type:decimal(12,2);default:0" validate:"min=0"`
	TaxAmount          float64    `json:"tax_amount" gorm:"not null;type:decimal(12,2);default:0" validate:"min=0"`
	DiscountAmount     float64    `json:"discount_amount" gorm:"type:decimal(12,2);default:0" validate:"min=0"`
	LateFee            float64    `json:"late_fee" gorm:"type:decimal(12,2);default:0" validate:"min=0"`
	TotalAmount        float64    `json:"total_amount" gorm:"not null;type:decimal(12,2)" validate:"required,min=0"`
	PaidAmount         float64    `json:"paid_amount" gorm:"type:decimal(12,2);default:0" validate:"min=0"`
	Balance            float64    `json:"balance" gorm:"type:decimal(12,2);->"`
	Status             string     `json:"status" gorm:"default:'draft';not null" validate:"required,oneof=draft sent partial paid overdue cancelled refunded"`
	PaymentStatus      *string    `json:"payment_status" gorm:"type:varchar(20)" validate:"omitempty,oneof=unpaid partial paid overpaid"`
	PaymentDate        *time.Time `json:"payment_date" gorm:"type:timestamp"`
	PaymentMethod      *string    `json:"payment_method" validate:"omitempty,oneof=cash bank_transfer e-wallet credit_card debit_card check"`
	InvoiceType        string     `json:"invoice_type" gorm:"default:'recurring';not null" validate:"required,oneof=recurring installation additional refund"`
	IsAutoGenerated    *bool      `json:"is_auto_generated" gorm:"default:true"`
	ReminderSentCount  *int       `json:"reminder_sent_count" gorm:"default:0"`
	LastReminderSent   *time.Time `json:"last_reminder_sent" gorm:"type:timestamp"`
	Notes              *string    `json:"notes" gorm:"type:text"`
	InternalNotes      *string    `json:"internal_notes" gorm:"type:text"`
	CreatedBy          *uint      `json:"created_by" gorm:"type:integer"`
	UpdatedBy          *uint      `json:"updated_by" gorm:"type:integer"`
	CreatedAt          time.Time  `json:"created_at" gorm:"autoCreateTime"`
	UpdatedAt          time.Time  `json:"updated_at" gorm:"autoUpdateTime"`
	DeletedAt          *time.Time `json:"-" gorm:"index"`
}

type InvoiceInput struct {
	InvoiceNumber      *string            `json:"invoice_number" validate:"omitempty,required_if=Update"`
	CustomerID         uuid.UUID          `json:"customer_id" validate:"required"`
	BillingPeriodStart time.Time          `json:"billing_period_start" validate:"required"`
	BillingPeriodEnd   time.Time          `json:"billing_period_end" validate:"required"`
	BillingMonth       *int               `json:"billing_month" validate:"omitempty,min=1,max=12"`
	BillingYear        *int               `json:"billing_year" validate:"omitempty"`
	IssueDate          *time.Time         `json:"issue_date" validate:"required"`
	DueDate            *time.Time         `json:"due_date" validate:"required"`
	PaymentDeadline    *time.Time         `json:"payment_deadline"`
	Subtotal           *float64           `json:"subtotal" validate:"omitempty,min=0"`
	TaxAmount          *float64           `json:"tax_amount" validate:"omitempty,min=0"`
	DiscountAmount     *float64           `json:"discount_amount" validate:"omitempty,min=0"`
	LateFee            *float64           `json:"late_fee" validate:"omitempty,min=0"`
	TotalAmount        *float64           `json:"total_amount" validate:"omitempty,min=0"`
	PaidAmount         *float64           `json:"paid_amount" validate:"omitempty,min=0"`
	Status             *string            `json:"status" validate:"omitempty,oneof=draft sent partial paid overdue cancelled refunded"`
	PaymentDate        *time.Time         `json:"payment_date"`
	PaymentMethod      *string            `json:"payment_method" validate:"omitempty,oneof=cash bank_transfer e-wallet credit_card debit_card check"`
	InvoiceType        *string            `json:"invoice_type" validate:"omitempty,oneof=recurring installation additional refund"`
	IsAutoGenerated    *bool              `json:"is_auto_generated"`
	Notes              *string            `json:"notes"`
	InternalNotes      *string            `json:"internal_notes"`
	Items              []InvoiceItemInput `json:"items" validate:"required,min=1,dive"`
}

type InvoiceFilter struct {
	IDs             []uuid.UUID `json:"ids"`
	CustomerIDs     []uuid.UUID `json:"customer_ids"`
	Status          []string    `json:"status"`
	PaymentStatus   []string    `json:"payment_status"`
	InvoicesStart   *time.Time  `json:"invoices_start"`
	InvoicesEnd     *time.Time  `json:"invoices_end"`
	BillingMonth    *int        `json:"billing_month" validate:"omitempty,min=1,max=12"`
	BillingYear     *int        `json:"billing_year" validate:"omitempty"`
	IsOverdue       *bool       `json:"is_overdue"`
	IsAutoGenerated *bool       `json:"is_auto_generated"`
	Search          *string     `json:"search"`
}

func (f InvoiceFilter) IsEmpty() bool {
	return len(f.IDs) == 0 && len(f.CustomerIDs) == 0 &&
		len(f.Status) == 0 && len(f.PaymentStatus) == 0 &&
		f.InvoicesStart == nil && f.InvoicesEnd == nil &&
		f.BillingMonth == nil && f.BillingYear == nil &&
		f.IsOverdue == nil && f.IsAutoGenerated == nil && f.Search == nil
}

type InvoiceItem struct {
	ID                  uuid.UUID         `json:"id" gorm:"type:uuid;primaryKey;default:gen_random_uuid()"`
	InvoiceID           uuid.UUID         `json:"invoice_id" gorm:"type:uuid;not null" validate:"required"`
	Invoice             *Invoice          `json:"invoice,omitempty" gorm:"foreignKey:InvoiceID"`
	ItemType            string            `json:"item_type" gorm:"not null;type:varchar(20)" validate:"required,oneof=subscription installation equipment other"`
	Description         string            `json:"description" gorm:"not null" validate:"required"`
	ProfileID           *uuid.UUID        `json:"profile_id" gorm:"type:uuid"`
	Profile             *BandwidthProfile `json:"profile,omitempty" gorm:"foreignKey:ProfileID"`
	Quantity            int               `json:"quantity" gorm:"not null;default:1" validate:"min=1"`
	UnitPrice           float64           `json:"unit_price" gorm:"not null" validate:"required,min=0"`
	Subtotal            float64           `json:"subtotal" gorm:"not null" validate:"required,min=0"`
	TaxRate             float64           `json:"tax_rate" gorm:"default:0;type:decimal(5,4)" validate:"min=0,max=1"`
	TaxAmount           float64           `json:"tax_amount" gorm:"default:0;type:decimal(12,2)" validate:"min=0"`
	Total               float64           `json:"total" gorm:"not null" validate:"required,min=0"`
	IsProrated          *bool             `json:"is_prorated" gorm:"default:false"`
	ProrationDays       *int              `json:"proration_days" validate:"omitempty,min=1"`
	ProrationPercentage *float64          `json:"proration_percentage" validate:"omitempty,min=0,max=100"`
	SortOrder           int               `json:"sort_order" gorm:"default:0"`
	CreatedAt           time.Time         `json:"created_at" gorm:"autoCreateTime"`
}

type InvoiceItemInput struct {
	ItemType            string     `json:"item_type" validate:"required,oneof=subscription installation equipment other"`
	Description         string     `json:"description" validate:"required"`
	ProfileID           *uuid.UUID `json:"profile_id"`
	Quantity            *int       `json:"quantity" validate:"omitempty,min=1"`
	UnitPrice           float64    `json:"unit_price" validate:"required,min=0"`
	TaxRate             *float64   `json:"tax_rate" validate:"omitempty,min=0,max=1"`
	IsProrated          *bool      `json:"is_prorated"`
	ProrationDays       *int       `json:"proration_days" validate:"omitempty,min=1"`
	ProrationPercentage *float64   `json:"proration_percentage" validate:"omitempty,min=0,max=100"`
	SortOrder           *int       `json:"sort_order"`
}

func InvoicePrepare(v *Invoice) {
	if v.Status == "" {
		v.Status = "draft"
	}
	if v.InvoiceType == "" {
		v.InvoiceType = "recurring"
	}
	if v.IsAutoGenerated == nil {
		isAutoGen := true
		v.IsAutoGenerated = &isAutoGen
	}
	if v.ReminderSentCount == nil {
		remCount := 0
		v.ReminderSentCount = &remCount
	}
}

type BillingInfo struct {
	InvoiceCount int64   `json:"invoice_count"`
	TotalPending float64 `json:"total_pending"`
	TotalPaid    float64 `json:"total_paid"`
	TotalOverdue float64 `json:"total_overdue"`
}
