package model

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

// InvoiceStatus represents invoice status
type InvoiceStatus string

const (
	InvoiceStatusDraft     InvoiceStatus = "draft"
	InvoiceStatusSent      InvoiceStatus = "sent"
	InvoiceStatusPartial   InvoiceStatus = "partial"
	InvoiceStatusPaid      InvoiceStatus = "paid"
	InvoiceStatusOverdue   InvoiceStatus = "overdue"
	InvoiceStatusCancelled InvoiceStatus = "cancelled"
	InvoiceStatusRefunded  InvoiceStatus = "refunded"
)

// PaymentStatus represents payment status of invoice
type PaymentStatus string

const (
	PaymentStatusUnpaid   PaymentStatus = "unpaid"
	PaymentStatusPartial  PaymentStatus = "partial"
	PaymentStatusPaid     PaymentStatus = "paid"
	PaymentStatusOverpaid PaymentStatus = "overpaid"
)

// InvoiceType represents type of invoice
type InvoiceType string

const (
	InvoiceTypeRecurring     InvoiceType = "recurring"
	InvoiceTypeInstallation  InvoiceType = "installation"
	InvoiceTypeAdditional    InvoiceType = "additional"
	InvoiceTypeRefund        InvoiceType = "refund"
)

// Invoice represents customer invoice/bill
type Invoice struct {
	ID            uuid.UUID      `gorm:"type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	InvoiceNumber string         `gorm:"size:50;uniqueIndex;not null" json:"invoice_number" validate:"required"`
	CustomerID    uuid.UUID      `gorm:"type:uuid;not null" json:"customer_id" validate:"required"`
	Customer      *Customer      `gorm:"foreignKey:CustomerID;constraint:OnDelete:RESTRICT" json:"customer,omitempty"`

	// Billing Period
	BillingPeriodStart time.Time `gorm:"type:date;not null" json:"billing_period_start" validate:"required"`
	BillingPeriodEnd   time.Time `gorm:"type:date;not null" json:"billing_period_end" validate:"required"`
	BillingMonth       *int      `json:"billing_month" validate:"omitempty,min=1,max=12"`
	BillingYear        *int      `json:"billing_year"`

	// Dates
	IssueDate       time.Time  `gorm:"type:date;not null;default:CURRENT_DATE" json:"issue_date"`
	DueDate         time.Time  `gorm:"type:date;not null" json:"due_date" validate:"required"`
	PaymentDeadline *time.Time `json:"payment_deadline"`

	// Amounts
	Subtotal       float64 `gorm:"type:decimal(12,2);not null;default:0" json:"subtotal"`
	TaxAmount      float64 `gorm:"type:decimal(12,2);not null;default:0" json:"tax_amount"`
	DiscountAmount float64 `gorm:"type:decimal(12,2);default:0" json:"discount_amount"`
	LateFee        float64 `gorm:"type:decimal(12,2);default:0" json:"late_fee"`
	TotalAmount    float64 `gorm:"type:decimal(12,2);not null" json:"total_amount" validate:"required"`
	PaidAmount     float64 `gorm:"type:decimal(12,2);default:0" json:"paid_amount"`
	Balance        float64 `gorm:"type:decimal(12,2);->;default:0" json:"balance"` // computed column

	// Status
	Status        InvoiceStatus  `gorm:"size:20;not null;default:draft" json:"status"`
	PaymentStatus *PaymentStatus `gorm:"size:20" json:"payment_status"`

	// Payment Information
	PaymentDate   *time.Time `json:"payment_date"`
	PaymentMethod *string    `gorm:"size:20" json:"payment_method"`

	// Additional
	InvoiceType        InvoiceType `gorm:"size:20;default:recurring" json:"invoice_type"`
	IsAutoGenerated    *bool       `gorm:"default:true" json:"is_auto_generated"`
	ReminderSentCount  *int        `gorm:"default:0" json:"reminder_sent_count"`
	LastReminderSent   *time.Time  `json:"last_reminder_sent"`

	Notes         *string `gorm:"type:text" json:"notes"`
	InternalNotes *string `gorm:"type:text" json:"internal_notes"` // not shown in PDF

	// Relations
	Items []InvoiceItem `gorm:"foreignKey:InvoiceID" json:"items,omitempty"`

	CreatedBy *uuid.UUID `gorm:"type:uuid" json:"created_by"`
	UpdatedBy *uuid.UUID `gorm:"type:uuid" json:"updated_by"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"index" json:"-"`
}

// TableName specifies the table name for Invoice
func (Invoice) TableName() string {
	return "invoices"
}

// InvoiceItemType represents type of invoice item
type InvoiceItemType string

const (
	InvoiceItemTypeSubscription InvoiceItemType = "subscription"
	InvoiceItemTypeInstallation InvoiceItemType = "installation"
	InvoiceItemTypeEquipment    InvoiceItemType = "equipment"
	InvoiceItemTypeOther        InvoiceItemType = "other"
)

// InvoiceItem represents line item in invoice
type InvoiceItem struct {
	ID          uuid.UUID        `gorm:"type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	InvoiceID   uuid.UUID        `gorm:"type:uuid;not null" json:"invoice_id" validate:"required"`
	ItemType    *InvoiceItemType `gorm:"size:20" json:"item_type"`
	Description string           `gorm:"size:255;not null" json:"description" validate:"required"`

	ProfileID *uuid.UUID        `gorm:"type:uuid" json:"profile_id"`
	Profile   *BandwidthProfile `gorm:"foreignKey:ProfileID;constraint:OnDelete:SET NULL" json:"profile,omitempty"`

	Quantity  int     `gorm:"not null;default:1" json:"quantity" validate:"required,min=1"`
	UnitPrice float64 `gorm:"type:decimal(12,2);not null" json:"unit_price" validate:"required"`
	Subtotal  float64 `gorm:"type:decimal(12,2);not null" json:"subtotal" validate:"required"`
	TaxRate   float64 `gorm:"type:decimal(5,4);default:0" json:"tax_rate"`
	TaxAmount float64 `gorm:"type:decimal(12,2);default:0" json:"tax_amount"`
	Total     float64 `gorm:"type:decimal(12,2);not null" json:"total" validate:"required"`

	// Proration
	IsProrated           *bool    `gorm:"default:false" json:"is_prorated"`
	ProrationDays        *int     `json:"proration_days"`
	ProrationPercentage  *float64 `gorm:"type:decimal(5,2)" json:"proration_percentage"`

	SortOrder *int      `gorm:"default:0" json:"sort_order"`
	CreatedAt time.Time `json:"created_at"`
}

// TableName specifies the table name for InvoiceItem
func (InvoiceItem) TableName() string {
	return "invoice_items"
}

// InvoiceInput for creating/updating invoice
type InvoiceInput struct {
	InvoiceNumber      string     `json:"invoice_number" validate:"required,max=50"`
	CustomerID         uuid.UUID  `json:"customer_id" validate:"required,uuid"`
	BillingPeriodStart time.Time  `json:"billing_period_start" validate:"required"`
	BillingPeriodEnd   time.Time  `json:"billing_period_end" validate:"required"`
	BillingMonth       *int       `json:"billing_month" validate:"omitempty,min=1,max=12"`
	BillingYear        *int       `json:"billing_year"`
	IssueDate          *time.Time `json:"issue_date"`
	DueDate            time.Time  `json:"due_date" validate:"required"`
	PaymentDeadline    *time.Time `json:"payment_deadline"`
	Subtotal           float64    `json:"subtotal" validate:"min=0"`
	TaxAmount          float64    `json:"tax_amount" validate:"min=0"`
	DiscountAmount     float64    `json:"discount_amount" validate:"min=0"`
	LateFee            float64    `json:"late_fee" validate:"min=0"`
	TotalAmount        float64    `json:"total_amount" validate:"required,min=0"`
	Status             *string    `json:"status" validate:"omitempty,oneof=draft sent partial paid overdue cancelled refunded"`
	InvoiceType        *string    `json:"invoice_type" validate:"omitempty,oneof=recurring installation additional refund"`
	Notes              *string    `json:"notes"`
	InternalNotes      *string    `json:"internal_notes"`
	Items              []InvoiceItemInput `json:"items"`
}

// InvoiceItemInput for creating invoice items
type InvoiceItemInput struct {
	ItemType            *string    `json:"item_type" validate:"omitempty,oneof=subscription installation equipment other"`
	Description         string     `json:"description" validate:"required,max=255"`
	ProfileID           *uuid.UUID `json:"profile_id" validate:"omitempty,uuid"`
	Quantity            int        `json:"quantity" validate:"required,min=1"`
	UnitPrice           float64    `json:"unit_price" validate:"required,min=0"`
	Subtotal            float64    `json:"subtotal" validate:"required,min=0"`
	TaxRate             float64    `json:"tax_rate" validate:"min=0,max=1"`
	TaxAmount           float64    `json:"tax_amount" validate:"min=0"`
	Total               float64    `json:"total" validate:"required,min=0"`
	IsProrated          *bool      `json:"is_prorated"`
	ProrationDays       *int       `json:"proration_days" validate:"omitempty,min=1"`
	ProrationPercentage *float64   `json:"proration_percentage" validate:"omitempty,min=0,max=100"`
	SortOrder           *int       `json:"sort_order"`
}

// InvoiceFilter for filtering invoices
type InvoiceFilter struct {
	CustomerID     *uuid.UUID     `json:"customer_id"`
	Status         *InvoiceStatus `json:"status"`
	PaymentStatus  *PaymentStatus `json:"payment_status"`
	InvoiceType    *InvoiceType   `json:"invoice_type"`
	BillingMonth   *int           `json:"billing_month"`
	BillingYear    *int           `json:"billing_year"`
	DueDateFrom    *time.Time     `json:"due_date_from"`
	DueDateTo      *time.Time     `json:"due_date_to"`
	IsAutoGenerated *bool         `json:"is_auto_generated"`
	Search         *string        `json:"search"` // search by invoice number
	IncludeDeleted bool           `json:"include_deleted"`
}

// ToModel converts input to model
func (i *InvoiceInput) ToModel() *Invoice {
	invoice := &Invoice{
		InvoiceNumber:      i.InvoiceNumber,
		CustomerID:         i.CustomerID,
		BillingPeriodStart: i.BillingPeriodStart,
		BillingPeriodEnd:   i.BillingPeriodEnd,
		BillingMonth:       i.BillingMonth,
		BillingYear:        i.BillingYear,
		DueDate:            i.DueDate,
		PaymentDeadline:    i.PaymentDeadline,
		Subtotal:           i.Subtotal,
		TaxAmount:          i.TaxAmount,
		DiscountAmount:     i.DiscountAmount,
		LateFee:            i.LateFee,
		TotalAmount:        i.TotalAmount,
		Notes:              i.Notes,
		InternalNotes:      i.InternalNotes,
	}

	// Set issue date
	if i.IssueDate != nil {
		invoice.IssueDate = *i.IssueDate
	} else {
		invoice.IssueDate = time.Now()
	}

	// Set status
	if i.Status != nil {
		invoice.Status = InvoiceStatus(*i.Status)
	} else {
		invoice.Status = InvoiceStatusDraft
	}

	// Set invoice type
	if i.InvoiceType != nil {
		invoice.InvoiceType = InvoiceType(*i.InvoiceType)
	} else {
		invoice.InvoiceType = InvoiceTypeRecurring
	}

	// Convert items
	if len(i.Items) > 0 {
		items := make([]InvoiceItem, len(i.Items))
		for idx, item := range i.Items {
			items[idx] = *item.ToModel()
		}
		invoice.Items = items
	}

	return invoice
}

// ToModel converts input to model
func (i *InvoiceItemInput) ToModel() *InvoiceItem {
	item := &InvoiceItem{
		Description:         i.Description,
		ProfileID:           i.ProfileID,
		Quantity:            i.Quantity,
		UnitPrice:           i.UnitPrice,
		Subtotal:            i.Subtotal,
		TaxRate:             i.TaxRate,
		TaxAmount:           i.TaxAmount,
		Total:               i.Total,
		IsProrated:          i.IsProrated,
		ProrationDays:       i.ProrationDays,
		ProrationPercentage: i.ProrationPercentage,
		SortOrder:           i.SortOrder,
	}

	// Set item type
	if i.ItemType != nil {
		itemType := InvoiceItemType(*i.ItemType)
		item.ItemType = &itemType
	}

	return item
}

// IsOverdue checks if invoice is overdue
func (inv *Invoice) IsOverdue() bool {
	return time.Now().After(inv.DueDate) && inv.Balance > 0
}

// IsPaid checks if invoice is fully paid
func (inv *Invoice) IsPaid() bool {
	return inv.PaidAmount >= inv.TotalAmount
}

// GetBalance returns balance amount
func (inv *Invoice) GetBalance() float64 {
	return inv.TotalAmount - inv.PaidAmount
}

// UpdatePaymentStatus updates payment status based on paid amount
func (inv *Invoice) UpdatePaymentStatus() {
	balance := inv.GetBalance()

	if balance <= 0 {
		status := PaymentStatusPaid
		inv.PaymentStatus = &status
		inv.Status = InvoiceStatusPaid
	} else if inv.PaidAmount > 0 {
		status := PaymentStatusPartial
		inv.PaymentStatus = &status
		inv.Status = InvoiceStatusPartial
	} else {
		status := PaymentStatusUnpaid
		inv.PaymentStatus = &status
		if inv.IsOverdue() {
			inv.Status = InvoiceStatusOverdue
		}
	}
}
