package postgres_outbound_adapter

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/palantir/stacktrace"
	"gorm.io/gorm"

	"go-template/internal/model"
	outbound_port "go-template/internal/port/outbound"
)

const tableInvoice = "invoices"

type invoiceAdapter struct {
	db *gorm.DB
}

func NewInvoiceAdapter(
	db *gorm.DB,
) outbound_port.InvoiceDatabasePort {
	return &invoiceAdapter{
		db: db,
	}
}

func (a *invoiceAdapter) Create(ctx context.Context, invoice *model.Invoice) error {
	// Create invoice with items using GORM associations
	if err := a.db.WithContext(ctx).Session(&gorm.Session{FullSaveAssociations: true}).Create(invoice).Error; err != nil {
		return stacktrace.Propagate(err, "failed to create invoice in database")
	}
	return nil
}

func (a *invoiceAdapter) FindByID(ctx context.Context, id string) (*model.Invoice, error) {
	var invoice model.Invoice

	invoiceID, err := uuid.Parse(id)
	if err != nil {
		return nil, stacktrace.Propagate(err, "invalid invoice id format")
	}

	if err := a.db.WithContext(ctx).
		Preload("Items").
		Preload("Items.Profile").
		Preload("Customer").
		Preload("Subscription").
		Preload("Subscription.Plan").
		Where("id = ?", invoiceID).
		First(&invoice).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return nil, stacktrace.NewError("invoice not found")
		}
		return nil, stacktrace.Propagate(err, "failed to find invoice by id")
	}

	return &invoice, nil
}

func (a *invoiceAdapter) FindByNumber(ctx context.Context, number string) (*model.Invoice, error) {
	var invoice model.Invoice

	if err := a.db.WithContext(ctx).
		Preload("Items").
		Preload("Items.Profile").
		Preload("Customer").
		Preload("Subscription").
		Preload("Subscription.Plan").
		Where("invoice_number = ?", number).
		First(&invoice).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return nil, stacktrace.NewError("invoice not found")
		}
		return nil, stacktrace.Propagate(err, "failed to find invoice by number")
	}

	return &invoice, nil
}

func (a *invoiceAdapter) FindAll(ctx context.Context, filter *model.InvoiceFilter) ([]model.Invoice, error) {
	var invoices []model.Invoice

	query := a.db.WithContext(ctx).Model(&model.Invoice{})

	// Preload relations
	query = query.Preload("Items").Preload("Items.Profile").Preload("Customer").Preload("Subscription").Preload("Subscription.Plan")

	// Apply filters if provided
	if filter != nil {
		if filter.CustomerID != nil {
			query = query.Where("customer_id = ?", *filter.CustomerID)
		}

		if filter.Status != nil {
			query = query.Where("status = ?", *filter.Status)
		}

		if filter.PaymentStatus != nil {
			query = query.Where("payment_status = ?", *filter.PaymentStatus)
		}

		if filter.InvoiceType != nil {
			query = query.Where("invoice_type = ?", *filter.InvoiceType)
		}

		if filter.BillingMonth != nil {
			query = query.Where("billing_month = ?", *filter.BillingMonth)
		}

		if filter.BillingYear != nil {
			query = query.Where("billing_year = ?", *filter.BillingYear)
		}

		if filter.DueDateFrom != nil {
			query = query.Where("due_date >= ?", *filter.DueDateFrom)
		}

		if filter.DueDateTo != nil {
			query = query.Where("due_date <= ?", *filter.DueDateTo)
		}

		if filter.IsAutoGenerated != nil {
			query = query.Where("is_auto_generated = ?", *filter.IsAutoGenerated)
		}

		if filter.Search != nil && *filter.Search != "" {
			searchPattern := "%" + *filter.Search + "%"
			query = query.Where("invoice_number ILIKE ?", searchPattern)
		}

		// Handle soft deletes
		if !filter.IncludeDeleted {
			query = query.Where("deleted_at IS NULL")
		} else {
			query = query.Unscoped()
		}
	} else {
		// Default: exclude deleted
		query = query.Where("deleted_at IS NULL")
	}

	// Order by creation date
	query = query.Order("created_at DESC")

	if err := query.Find(&invoices).Error; err != nil {
		return nil, stacktrace.Propagate(err, "failed to find invoices")
	}

	return invoices, nil
}

func (a *invoiceAdapter) Update(ctx context.Context, invoice *model.Invoice) error {
	// First, delete existing items
	if err := a.db.WithContext(ctx).Where("invoice_id = ?", invoice.ID).Delete(&model.InvoiceItem{}).Error; err != nil {
		return stacktrace.Propagate(err, "failed to delete existing invoice items")
	}

	// Update invoice with new items using GORM associations
	if err := a.db.WithContext(ctx).Session(&gorm.Session{FullSaveAssociations: true}).Save(invoice).Error; err != nil {
		return stacktrace.Propagate(err, "failed to update invoice in database")
	}
	return nil
}

func (a *invoiceAdapter) Delete(ctx context.Context, id string) error {
	invoiceID, err := uuid.Parse(id)
	if err != nil {
		return stacktrace.Propagate(err, "invalid invoice id format")
	}

	// Soft delete using GORM
	if err := a.db.WithContext(ctx).Delete(&model.Invoice{}, invoiceID).Error; err != nil {
		return stacktrace.Propagate(err, "failed to delete invoice from database")
	}

	return nil
}

func (a *invoiceAdapter) GetLastInvoiceNumber(ctx context.Context, year, month int) (string, error) {
	var invoice model.Invoice

	// Build pattern for this year and month: INV/YYYY/MM/%
	pattern := fmt.Sprintf("INV/%d/%02d/%%", year, month)

	if err := a.db.WithContext(ctx).
		Unscoped().
		Where("invoice_number LIKE ?", pattern).
		Order("created_at DESC").
		First(&invoice).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return "", nil // No invoice found for this month
		}
		return "", stacktrace.Propagate(err, "failed to get last invoice number")
	}

	return invoice.InvoiceNumber, nil
}

func (a *invoiceAdapter) FindOverdueInvoices(ctx context.Context) ([]model.Invoice, error) {
	var invoices []model.Invoice

	if err := a.db.WithContext(ctx).
		Preload("Customer").
		Where("due_date < ? AND balance > 0", gorm.Expr("CURRENT_DATE")).
		Find(&invoices).Error; err != nil {
		return nil, stacktrace.Propagate(err, "failed to find overdue invoices")
	}

	return invoices, nil
}

