package postgres_outbound_adapter

import (
	"errors"
	"time"

	"go-template/internal/model"
	outbound_port "go-template/internal/port/outbound"
	"gorm.io/gorm"
)

const tableInvoice = "invoices"

type InvoiceAdapter struct {
	db *gorm.DB
}

func NewInvoiceAdapter(db *gorm.DB) outbound_port.InvoiceDatabasePort {
	return &InvoiceAdapter{db: db}
}

func (a *InvoiceAdapter) Create(invoice *model.Invoice) error {
	model.InvoicePrepare(invoice)
	return a.db.Create(invoice).Error
}

func (a *InvoiceAdapter) FindByID(id string) (*model.Invoice, error) {
	var invoice model.Invoice
	err := a.db.Preload("Customer").Preload("Items").Preload("Items.Profile").Where("id = ? AND deleted_at IS NULL", id).First(&invoice).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, errors.New("invoice not found")
		}
		return nil, err
	}
	return &invoice, nil
}

func (a *InvoiceAdapter) FindAll() ([]model.Invoice, error) {
	var invoices []model.Invoice
	if err := a.db.Preload("Customer").Where("deleted_at IS NULL").Find(&invoices).Error; err != nil {
		return nil, err
	}
	return invoices, nil
}

func (a *InvoiceAdapter) Find(filter model.InvoiceFilter) ([]model.Invoice, error) {
	var invoices []model.Invoice
	query := a.db.Preload("Customer").Preload("Items").Preload("Items.Profile").Where("deleted_at IS NULL")

	if !filter.IsEmpty() {
		if len(filter.IDs) > 0 {
			query = query.Where("id IN ?", filter.IDs)
		}
		if len(filter.CustomerIDs) > 0 {
			query = query.Where("customer_id IN ?", filter.CustomerIDs)
		}
		if len(filter.Status) > 0 {
			query = query.Where("status IN ?", filter.Status)
		}
		if len(filter.PaymentStatus) > 0 {
			query = query.Where("payment_status IN ?", filter.PaymentStatus)
		}
		if filter.InvoicesStart != nil {
			query = query.Where("issue_date >= ?", *filter.InvoicesStart)
		}
		if filter.InvoicesEnd != nil {
			query = query.Where("issue_date <= ?", *filter.InvoicesEnd)
		}
		if filter.BillingMonth != nil {
			query = query.Where("billing_month = ?", *filter.BillingMonth)
		}
		if filter.BillingYear != nil {
			query = query.Where("billing_year = ?", *filter.BillingYear)
		}
		if filter.IsOverdue != nil {
			if *filter.IsOverdue {
				query = query.Where("status = ? AND due_date < ?", "sent", time.Now())
			}
		}
		if filter.IsAutoGenerated != nil {
			query = query.Where("is_auto_generated = ?", *filter.IsAutoGenerated)
		}
		if filter.Search != nil {
			search := "%" + *filter.Search + "%"
			query = query.Where("invoice_number ILIKE ?", search)
		}
	}

	if err := query.Find(&invoices).Error; err != nil {
		return nil, err
	}
	return invoices, nil
}

func (a *InvoiceAdapter) Update(invoice *model.Invoice) error {
	result := a.db.Save(invoice)
	if result.Error != nil {
		return result.Error
	}
	if result.RowsAffected == 0 {
		return errors.New("no rows affected")
	}
	return nil
}

func (a *InvoiceAdapter) Delete(id string) error {
	result := a.db.Where("id = ?", id).Update("deleted_at", "NOW()")
	if result.Error != nil {
		return result.Error
	}
	if result.RowsAffected == 0 {
		return errors.New("no rows affected")
	}
	return nil
}

func (a *InvoiceAdapter) FindByCustomerID(customerID string) ([]model.Invoice, error) {
	var invoices []model.Invoice
	if err := a.db.Preload("Items").Where("customer_id = ? AND deleted_at IS NULL", customerID).Find(&invoices).Error; err != nil {
		return nil, err
	}
	return invoices, nil
}

func (a *InvoiceAdapter) FindByInvoiceNumber(number string) (*model.Invoice, error) {
	var invoice model.Invoice
	err := a.db.Preload("Customer").Preload("Items").Where("invoice_number = ? AND deleted_at IS NULL", number).First(&invoice).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, errors.New("invoice not found")
		}
		return nil, err
	}
	return &invoice, nil
}

func (a *InvoiceAdapter) FindOverdue() ([]model.Invoice, error) {
	var invoices []model.Invoice
	err := a.db.Preload("Customer").Where("status = ? AND due_date < ? AND deleted_at IS NULL", "sent", time.Now()).Find(&invoices).Error
	if err != nil {
		return nil, err
	}
	return invoices, nil
}

func (a *InvoiceAdapter) FindByBillingPeriod(year int, month int) ([]model.Invoice, error) {
	var invoices []model.Invoice
	err := a.db.Preload("Customer").Where("billing_year = ? AND billing_month = ? AND deleted_at IS NULL", year, month).Find(&invoices).Error
	if err != nil {
		return nil, err
	}
	return invoices, nil
}
