package gowa

import (
	"context"
	"fmt"
	"net/http"
)

// ListDevices returns all registered devices with their connection status.
func (c *Client) ListDevices(ctx context.Context) ([]DeviceInfo, error) {
	body, statusCode, err := c.doRequest(ctx, http.MethodGet, "/devices", nil, "")
	if err != nil {
		return nil, fmt.Errorf("list devices request failed: %w", err)
	}

	var result DeviceListResponse
	if err := parseResponse(body, statusCode, &result); err != nil {
		return nil, fmt.Errorf("list devices failed: %w", err)
	}

	return result.Results, nil
}

// AddDevice creates a new device slot for multi-device management.
// If deviceID is empty, one will be generated by the server.
func (c *Client) AddDevice(ctx context.Context, deviceID string) (*DeviceInfo, error) {
	req := AddDeviceRequest{}
	if deviceID != "" {
		req.DeviceID = deviceID
	}

	body, statusCode, err := c.doRequest(ctx, http.MethodPost, "/devices", req, "")
	if err != nil {
		return nil, fmt.Errorf("add device request failed: %w", err)
	}

	var result DeviceAddResponse
	if err := parseResponse(body, statusCode, &result); err != nil {
		return nil, fmt.Errorf("add device failed: %w", err)
	}

	return &result.Results, nil
}

// GetDevice returns detailed information about a specific device.
func (c *Client) GetDevice(ctx context.Context, deviceID string) (*DeviceInfo, error) {
	body, statusCode, err := c.doRequest(ctx, http.MethodGet, "/devices/"+deviceID, nil, "")
	if err != nil {
		return nil, fmt.Errorf("get device request failed: %w", err)
	}

	var result DeviceInfoResponse
	if err := parseResponse(body, statusCode, &result); err != nil {
		return nil, fmt.Errorf("get device failed: %w", err)
	}

	return &result.Results, nil
}

// RemoveDevice removes a device from the server.
// Note: This does not logout from WhatsApp.
func (c *Client) RemoveDevice(ctx context.Context, deviceID string) (*GenericResponse, error) {
	body, statusCode, err := c.doRequest(ctx, http.MethodDelete, "/devices/"+deviceID, nil, "")
	if err != nil {
		return nil, fmt.Errorf("remove device request failed: %w", err)
	}

	var result GenericResponse
	if err := parseResponse(body, statusCode, &result); err != nil {
		return nil, fmt.Errorf("remove device failed: %w", err)
	}

	return &result, nil
}

// LoginDevice initiates QR code login for a specific device.
func (c *Client) LoginDevice(ctx context.Context, deviceID string) (*LoginResponse, error) {
	body, statusCode, err := c.doRequest(ctx, http.MethodGet, "/devices/"+deviceID+"/login", nil, "")
	if err != nil {
		return nil, fmt.Errorf("login device request failed: %w", err)
	}

	var result LoginResponse
	if err := parseResponse(body, statusCode, &result); err != nil {
		return nil, fmt.Errorf("login device failed: %w", err)
	}

	return &result, nil
}

// LoginDeviceWithCode initiates pairing code login for a specific device.
// phone should be in format: 628912344551
func (c *Client) LoginDeviceWithCode(ctx context.Context, deviceID, phone string) (*LoginWithCodeResponse, error) {
	params := map[string]string{
		"phone": phone,
	}

	body, statusCode, err := c.doRequestWithQuery(ctx, "/devices/"+deviceID+"/login/code", params, "")
	if err != nil {
		return nil, fmt.Errorf("login device with code request failed: %w", err)
	}

	var result LoginWithCodeResponse
	if err := parseResponse(body, statusCode, &result); err != nil {
		return nil, fmt.Errorf("login device with code failed: %w", err)
	}

	return &result, nil
}

// LogoutDevice logs out a specific device from WhatsApp and removes its session.
func (c *Client) LogoutDevice(ctx context.Context, deviceID string) (*GenericResponse, error) {
	body, statusCode, err := c.doRequest(ctx, http.MethodPost, "/devices/"+deviceID+"/logout", nil, "")
	if err != nil {
		return nil, fmt.Errorf("logout device request failed: %w", err)
	}

	var result GenericResponse
	if err := parseResponse(body, statusCode, &result); err != nil {
		return nil, fmt.Errorf("logout device failed: %w", err)
	}

	return &result, nil
}

// ReconnectDevice reconnects a specific device to WhatsApp.
func (c *Client) ReconnectDevice(ctx context.Context, deviceID string) (*GenericResponse, error) {
	body, statusCode, err := c.doRequest(ctx, http.MethodPost, "/devices/"+deviceID+"/reconnect", nil, "")
	if err != nil {
		return nil, fmt.Errorf("reconnect device request failed: %w", err)
	}

	var result GenericResponse
	if err := parseResponse(body, statusCode, &result); err != nil {
		return nil, fmt.Errorf("reconnect device failed: %w", err)
	}

	return &result, nil
}

// GetDeviceStatus returns the connection status of a specific device.
func (c *Client) GetDeviceStatus(ctx context.Context, deviceID string) (*DeviceStatusResult, error) {
	body, statusCode, err := c.doRequest(ctx, http.MethodGet, "/devices/"+deviceID+"/status", nil, "")
	if err != nil {
		return nil, fmt.Errorf("get device status request failed: %w", err)
	}

	var result DeviceStatusResponse
	if err := parseResponse(body, statusCode, &result); err != nil {
		return nil, fmt.Errorf("get device status failed: %w", err)
	}

	return &result.Results, nil
}

// IsDeviceConnected checks if a specific device is connected and logged in.
func (c *Client) IsDeviceConnected(ctx context.Context, deviceID string) (bool, error) {
	status, err := c.GetDeviceStatus(ctx, deviceID)
	if err != nil {
		return false, err
	}
	return status.IsConnected && status.IsLoggedIn, nil
}
