// Code generated by MockGen. DO NOT EDIT.
// Source: customer.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	context "context"
	model "go-template/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCustomerDatabasePort is a mock of CustomerDatabasePort interface.
type MockCustomerDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerDatabasePortMockRecorder
}

// MockCustomerDatabasePortMockRecorder is the mock recorder for MockCustomerDatabasePort.
type MockCustomerDatabasePortMockRecorder struct {
	mock *MockCustomerDatabasePort
}

// NewMockCustomerDatabasePort creates a new mock instance.
func NewMockCustomerDatabasePort(ctrl *gomock.Controller) *MockCustomerDatabasePort {
	mock := &MockCustomerDatabasePort{ctrl: ctrl}
	mock.recorder = &MockCustomerDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerDatabasePort) EXPECT() *MockCustomerDatabasePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCustomerDatabasePort) Create(ctx context.Context, customer *model.Customer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, customer)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCustomerDatabasePortMockRecorder) Create(ctx, customer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCustomerDatabasePort)(nil).Create), ctx, customer)
}

// Delete mocks base method.
func (m *MockCustomerDatabasePort) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCustomerDatabasePortMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCustomerDatabasePort)(nil).Delete), ctx, id)
}

// FindAll mocks base method.
func (m *MockCustomerDatabasePort) FindAll(ctx context.Context, filter *model.CustomerFilter) ([]model.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, filter)
	ret0, _ := ret[0].([]model.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockCustomerDatabasePortMockRecorder) FindAll(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockCustomerDatabasePort)(nil).FindAll), ctx, filter)
}

// FindByCode mocks base method.
func (m *MockCustomerDatabasePort) FindByCode(ctx context.Context, code string) (*model.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCode", ctx, code)
	ret0, _ := ret[0].(*model.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCode indicates an expected call of FindByCode.
func (mr *MockCustomerDatabasePortMockRecorder) FindByCode(ctx, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCode", reflect.TypeOf((*MockCustomerDatabasePort)(nil).FindByCode), ctx, code)
}

// FindByID mocks base method.
func (m *MockCustomerDatabasePort) FindByID(ctx context.Context, id string) (*model.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*model.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockCustomerDatabasePortMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCustomerDatabasePort)(nil).FindByID), ctx, id)
}

// FindByPortalIdentifier mocks base method.
func (m *MockCustomerDatabasePort) FindByPortalIdentifier(ctx context.Context, identifier string) (*model.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByPortalIdentifier", ctx, identifier)
	ret0, _ := ret[0].(*model.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByPortalIdentifier indicates an expected call of FindByPortalIdentifier.
func (mr *MockCustomerDatabasePortMockRecorder) FindByPortalIdentifier(ctx, identifier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByPortalIdentifier", reflect.TypeOf((*MockCustomerDatabasePort)(nil).FindByPortalIdentifier), ctx, identifier)
}

// Update mocks base method.
func (m *MockCustomerDatabasePort) Update(ctx context.Context, customer *model.Customer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, customer)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCustomerDatabasePortMockRecorder) Update(ctx, customer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCustomerDatabasePort)(nil).Update), ctx, customer)
}

// UpdateStatus mocks base method.
func (m *MockCustomerDatabasePort) UpdateStatus(ctx context.Context, id string, status model.CustomerStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockCustomerDatabasePortMockRecorder) UpdateStatus(ctx, id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockCustomerDatabasePort)(nil).UpdateStatus), ctx, id, status)
}
