// Code generated by MockGen. DO NOT EDIT.
// Source: bandwidth_profile.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	context "context"
	model "go-template/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBandwidthProfileDatabasePort is a mock of BandwidthProfileDatabasePort interface.
type MockBandwidthProfileDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockBandwidthProfileDatabasePortMockRecorder
}

// MockBandwidthProfileDatabasePortMockRecorder is the mock recorder for MockBandwidthProfileDatabasePort.
type MockBandwidthProfileDatabasePortMockRecorder struct {
	mock *MockBandwidthProfileDatabasePort
}

// NewMockBandwidthProfileDatabasePort creates a new mock instance.
func NewMockBandwidthProfileDatabasePort(ctrl *gomock.Controller) *MockBandwidthProfileDatabasePort {
	mock := &MockBandwidthProfileDatabasePort{ctrl: ctrl}
	mock.recorder = &MockBandwidthProfileDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBandwidthProfileDatabasePort) EXPECT() *MockBandwidthProfileDatabasePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBandwidthProfileDatabasePort) Create(ctx context.Context, profile *model.BandwidthProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBandwidthProfileDatabasePortMockRecorder) Create(ctx, profile interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBandwidthProfileDatabasePort)(nil).Create), ctx, profile)
}

// Delete mocks base method.
func (m *MockBandwidthProfileDatabasePort) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBandwidthProfileDatabasePortMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBandwidthProfileDatabasePort)(nil).Delete), ctx, id)
}

// FindAll mocks base method.
func (m *MockBandwidthProfileDatabasePort) FindAll(ctx context.Context, filter *model.BandwidthProfileFilter) ([]model.BandwidthProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, filter)
	ret0, _ := ret[0].([]model.BandwidthProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockBandwidthProfileDatabasePortMockRecorder) FindAll(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockBandwidthProfileDatabasePort)(nil).FindAll), ctx, filter)
}

// FindByCode mocks base method.
func (m *MockBandwidthProfileDatabasePort) FindByCode(ctx context.Context, code string) (*model.BandwidthProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCode", ctx, code)
	ret0, _ := ret[0].(*model.BandwidthProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCode indicates an expected call of FindByCode.
func (mr *MockBandwidthProfileDatabasePortMockRecorder) FindByCode(ctx, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCode", reflect.TypeOf((*MockBandwidthProfileDatabasePort)(nil).FindByCode), ctx, code)
}

// FindByID mocks base method.
func (m *MockBandwidthProfileDatabasePort) FindByID(ctx context.Context, id string) (*model.BandwidthProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*model.BandwidthProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockBandwidthProfileDatabasePortMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockBandwidthProfileDatabasePort)(nil).FindByID), ctx, id)
}

// Update mocks base method.
func (m *MockBandwidthProfileDatabasePort) Update(ctx context.Context, profile *model.BandwidthProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockBandwidthProfileDatabasePortMockRecorder) Update(ctx, profile interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBandwidthProfileDatabasePort)(nil).Update), ctx, profile)
}
