// Code generated by MockGen. DO NOT EDIT.
// Source: pppoe_cache.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	context "context"
	model "go-template/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPppoeCachePort is a mock of PppoeCachePort interface.
type MockPppoeCachePort struct {
	ctrl     *gomock.Controller
	recorder *MockPppoeCachePortMockRecorder
}

// MockPppoeCachePortMockRecorder is the mock recorder for MockPppoeCachePort.
type MockPppoeCachePortMockRecorder struct {
	mock *MockPppoeCachePort
}

// NewMockPppoeCachePort creates a new mock instance.
func NewMockPppoeCachePort(ctrl *gomock.Controller) *MockPppoeCachePort {
	mock := &MockPppoeCachePort{ctrl: ctrl}
	mock.recorder = &MockPppoeCachePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPppoeCachePort) EXPECT() *MockPppoeCachePortMockRecorder {
	return m.recorder
}

// PublishInterfaceStats mocks base method.
func (m *MockPppoeCachePort) PublishInterfaceStats(data interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishInterfaceStats", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishInterfaceStats indicates an expected call of PublishInterfaceStats.
func (mr *MockPppoeCachePortMockRecorder) PublishInterfaceStats(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishInterfaceStats", reflect.TypeOf((*MockPppoeCachePort)(nil).PublishInterfaceStats), data)
}

// PublishInterfaceStatsByName mocks base method.
func (m *MockPppoeCachePort) PublishInterfaceStatsByName(interfaceName string, data interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishInterfaceStatsByName", interfaceName, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishInterfaceStatsByName indicates an expected call of PublishInterfaceStatsByName.
func (mr *MockPppoeCachePortMockRecorder) PublishInterfaceStatsByName(interfaceName, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishInterfaceStatsByName", reflect.TypeOf((*MockPppoeCachePort)(nil).PublishInterfaceStatsByName), interfaceName, data)
}

// PublishPingResult mocks base method.
func (m *MockPppoeCachePort) PublishPingResult(address string, data interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishPingResult", address, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishPingResult indicates an expected call of PublishPingResult.
func (mr *MockPppoeCachePortMockRecorder) PublishPingResult(address, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishPingResult", reflect.TypeOf((*MockPppoeCachePort)(nil).PublishPingResult), address, data)
}

// PublishQueueStats mocks base method.
func (m *MockPppoeCachePort) PublishQueueStats(data interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishQueueStats", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishQueueStats indicates an expected call of PublishQueueStats.
func (mr *MockPppoeCachePortMockRecorder) PublishQueueStats(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishQueueStats", reflect.TypeOf((*MockPppoeCachePort)(nil).PublishQueueStats), data)
}

// PublishQueueStatsByName mocks base method.
func (m *MockPppoeCachePort) PublishQueueStatsByName(queueName string, data interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishQueueStatsByName", queueName, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishQueueStatsByName indicates an expected call of PublishQueueStatsByName.
func (mr *MockPppoeCachePortMockRecorder) PublishQueueStatsByName(queueName, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishQueueStatsByName", reflect.TypeOf((*MockPppoeCachePort)(nil).PublishQueueStatsByName), queueName, data)
}

// PublishSessionEvent mocks base method.
func (m *MockPppoeCachePort) PublishSessionEvent(event string, data interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishSessionEvent", event, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishSessionEvent indicates an expected call of PublishSessionEvent.
func (mr *MockPppoeCachePortMockRecorder) PublishSessionEvent(event, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishSessionEvent", reflect.TypeOf((*MockPppoeCachePort)(nil).PublishSessionEvent), event, data)
}

// SubscribeToInterfaceStats mocks base method.
func (m *MockPppoeCachePort) SubscribeToInterfaceStats(ctx context.Context) (<-chan model.WebSocketMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeToInterfaceStats", ctx)
	ret0, _ := ret[0].(<-chan model.WebSocketMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeToInterfaceStats indicates an expected call of SubscribeToInterfaceStats.
func (mr *MockPppoeCachePortMockRecorder) SubscribeToInterfaceStats(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeToInterfaceStats", reflect.TypeOf((*MockPppoeCachePort)(nil).SubscribeToInterfaceStats), ctx)
}

// SubscribeToInterfaceStatsByName mocks base method.
func (m *MockPppoeCachePort) SubscribeToInterfaceStatsByName(ctx context.Context, interfaceName string) (<-chan model.WebSocketMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeToInterfaceStatsByName", ctx, interfaceName)
	ret0, _ := ret[0].(<-chan model.WebSocketMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeToInterfaceStatsByName indicates an expected call of SubscribeToInterfaceStatsByName.
func (mr *MockPppoeCachePortMockRecorder) SubscribeToInterfaceStatsByName(ctx, interfaceName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeToInterfaceStatsByName", reflect.TypeOf((*MockPppoeCachePort)(nil).SubscribeToInterfaceStatsByName), ctx, interfaceName)
}

// SubscribeToPingResults mocks base method.
func (m *MockPppoeCachePort) SubscribeToPingResults(ctx context.Context, address string) (<-chan model.WebSocketMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeToPingResults", ctx, address)
	ret0, _ := ret[0].(<-chan model.WebSocketMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeToPingResults indicates an expected call of SubscribeToPingResults.
func (mr *MockPppoeCachePortMockRecorder) SubscribeToPingResults(ctx, address interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeToPingResults", reflect.TypeOf((*MockPppoeCachePort)(nil).SubscribeToPingResults), ctx, address)
}

// SubscribeToQueueStats mocks base method.
func (m *MockPppoeCachePort) SubscribeToQueueStats(ctx context.Context) (<-chan model.WebSocketMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeToQueueStats", ctx)
	ret0, _ := ret[0].(<-chan model.WebSocketMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeToQueueStats indicates an expected call of SubscribeToQueueStats.
func (mr *MockPppoeCachePortMockRecorder) SubscribeToQueueStats(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeToQueueStats", reflect.TypeOf((*MockPppoeCachePort)(nil).SubscribeToQueueStats), ctx)
}

// SubscribeToQueueStatsByName mocks base method.
func (m *MockPppoeCachePort) SubscribeToQueueStatsByName(ctx context.Context, queueName string) (<-chan model.WebSocketMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeToQueueStatsByName", ctx, queueName)
	ret0, _ := ret[0].(<-chan model.WebSocketMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeToQueueStatsByName indicates an expected call of SubscribeToQueueStatsByName.
func (mr *MockPppoeCachePortMockRecorder) SubscribeToQueueStatsByName(ctx, queueName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeToQueueStatsByName", reflect.TypeOf((*MockPppoeCachePort)(nil).SubscribeToQueueStatsByName), ctx, queueName)
}

// SubscribeToSessionEvents mocks base method.
func (m *MockPppoeCachePort) SubscribeToSessionEvents(ctx context.Context) (<-chan model.WebSocketMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeToSessionEvents", ctx)
	ret0, _ := ret[0].(<-chan model.WebSocketMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeToSessionEvents indicates an expected call of SubscribeToSessionEvents.
func (mr *MockPppoeCachePortMockRecorder) SubscribeToSessionEvents(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeToSessionEvents", reflect.TypeOf((*MockPppoeCachePort)(nil).SubscribeToSessionEvents), ctx)
}
