// Code generated by MockGen. DO NOT EDIT.
// Source: tenant_setting.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "mikrops/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTenantSettingDatabasePort is a mock of TenantSettingDatabasePort interface.
type MockTenantSettingDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockTenantSettingDatabasePortMockRecorder
}

// MockTenantSettingDatabasePortMockRecorder is the mock recorder for MockTenantSettingDatabasePort.
type MockTenantSettingDatabasePortMockRecorder struct {
	mock *MockTenantSettingDatabasePort
}

// NewMockTenantSettingDatabasePort creates a new mock instance.
func NewMockTenantSettingDatabasePort(ctrl *gomock.Controller) *MockTenantSettingDatabasePort {
	mock := &MockTenantSettingDatabasePort{ctrl: ctrl}
	mock.recorder = &MockTenantSettingDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantSettingDatabasePort) EXPECT() *MockTenantSettingDatabasePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTenantSettingDatabasePort) Create(data model.TenantSettingInput) (model.TenantSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", data)
	ret0, _ := ret[0].(model.TenantSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTenantSettingDatabasePortMockRecorder) Create(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTenantSettingDatabasePort)(nil).Create), data)
}

// Delete mocks base method.
func (m *MockTenantSettingDatabasePort) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTenantSettingDatabasePortMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTenantSettingDatabasePort)(nil).Delete), id)
}

// FindByFilter mocks base method.
func (m *MockTenantSettingDatabasePort) FindByFilter(filter model.TenantSettingFilter) ([]model.TenantSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFilter", filter)
	ret0, _ := ret[0].([]model.TenantSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFilter indicates an expected call of FindByFilter.
func (mr *MockTenantSettingDatabasePortMockRecorder) FindByFilter(filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFilter", reflect.TypeOf((*MockTenantSettingDatabasePort)(nil).FindByFilter), filter)
}

// FindByID mocks base method.
func (m *MockTenantSettingDatabasePort) FindByID(id string) (model.TenantSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(model.TenantSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockTenantSettingDatabasePortMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockTenantSettingDatabasePort)(nil).FindByID), id)
}

// FindByTenantID mocks base method.
func (m *MockTenantSettingDatabasePort) FindByTenantID(tenantID string) (model.TenantSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTenantID", tenantID)
	ret0, _ := ret[0].(model.TenantSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTenantID indicates an expected call of FindByTenantID.
func (mr *MockTenantSettingDatabasePortMockRecorder) FindByTenantID(tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTenantID", reflect.TypeOf((*MockTenantSettingDatabasePort)(nil).FindByTenantID), tenantID)
}

// Update mocks base method.
func (m *MockTenantSettingDatabasePort) Update(id string, data model.TenantSettingInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTenantSettingDatabasePortMockRecorder) Update(id, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTenantSettingDatabasePort)(nil).Update), id, data)
}

// Upsert mocks base method.
func (m *MockTenantSettingDatabasePort) Upsert(data model.TenantSettingInput) (model.TenantSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", data)
	ret0, _ := ret[0].(model.TenantSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *MockTenantSettingDatabasePortMockRecorder) Upsert(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockTenantSettingDatabasePort)(nil).Upsert), data)
}
