// Code generated by MockGen. DO NOT EDIT.
// Source: invoice.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	context "context"
	model "go-template/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockInvoiceDatabasePort is a mock of InvoiceDatabasePort interface.
type MockInvoiceDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockInvoiceDatabasePortMockRecorder
}

// MockInvoiceDatabasePortMockRecorder is the mock recorder for MockInvoiceDatabasePort.
type MockInvoiceDatabasePortMockRecorder struct {
	mock *MockInvoiceDatabasePort
}

// NewMockInvoiceDatabasePort creates a new mock instance.
func NewMockInvoiceDatabasePort(ctrl *gomock.Controller) *MockInvoiceDatabasePort {
	mock := &MockInvoiceDatabasePort{ctrl: ctrl}
	mock.recorder = &MockInvoiceDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvoiceDatabasePort) EXPECT() *MockInvoiceDatabasePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockInvoiceDatabasePort) Create(ctx context.Context, invoice *model.Invoice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, invoice)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockInvoiceDatabasePortMockRecorder) Create(ctx, invoice interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInvoiceDatabasePort)(nil).Create), ctx, invoice)
}

// Delete mocks base method.
func (m *MockInvoiceDatabasePort) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockInvoiceDatabasePortMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInvoiceDatabasePort)(nil).Delete), ctx, id)
}

// FindAll mocks base method.
func (m *MockInvoiceDatabasePort) FindAll(ctx context.Context, filter *model.InvoiceFilter) ([]model.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, filter)
	ret0, _ := ret[0].([]model.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockInvoiceDatabasePortMockRecorder) FindAll(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockInvoiceDatabasePort)(nil).FindAll), ctx, filter)
}

// FindByID mocks base method.
func (m *MockInvoiceDatabasePort) FindByID(ctx context.Context, id string) (*model.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*model.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockInvoiceDatabasePortMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockInvoiceDatabasePort)(nil).FindByID), ctx, id)
}

// FindByNumber mocks base method.
func (m *MockInvoiceDatabasePort) FindByNumber(ctx context.Context, number string) (*model.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByNumber", ctx, number)
	ret0, _ := ret[0].(*model.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByNumber indicates an expected call of FindByNumber.
func (mr *MockInvoiceDatabasePortMockRecorder) FindByNumber(ctx, number interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByNumber", reflect.TypeOf((*MockInvoiceDatabasePort)(nil).FindByNumber), ctx, number)
}

// FindOverdueInvoices mocks base method.
func (m *MockInvoiceDatabasePort) FindOverdueInvoices(ctx context.Context) ([]model.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOverdueInvoices", ctx)
	ret0, _ := ret[0].([]model.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOverdueInvoices indicates an expected call of FindOverdueInvoices.
func (mr *MockInvoiceDatabasePortMockRecorder) FindOverdueInvoices(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOverdueInvoices", reflect.TypeOf((*MockInvoiceDatabasePort)(nil).FindOverdueInvoices), ctx)
}

// GetLastInvoiceNumber mocks base method.
func (m *MockInvoiceDatabasePort) GetLastInvoiceNumber(ctx context.Context, year, month int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastInvoiceNumber", ctx, year, month)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastInvoiceNumber indicates an expected call of GetLastInvoiceNumber.
func (mr *MockInvoiceDatabasePortMockRecorder) GetLastInvoiceNumber(ctx, year, month interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastInvoiceNumber", reflect.TypeOf((*MockInvoiceDatabasePort)(nil).GetLastInvoiceNumber), ctx, year, month)
}

// Update mocks base method.
func (m *MockInvoiceDatabasePort) Update(ctx context.Context, invoice *model.Invoice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, invoice)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockInvoiceDatabasePortMockRecorder) Update(ctx, invoice interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockInvoiceDatabasePort)(nil).Update), ctx, invoice)
}
