// Code generated by MockGen. DO NOT EDIT.
// Source: go-template/internal/port/outbound (interfaces: DatabasePort)

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	outbound_port "go-template/internal/port/outbound"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDatabasePort is a mock of DatabasePort interface.
type MockDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockDatabasePortMockRecorder
}

// MockDatabasePortMockRecorder is the mock recorder for MockDatabasePort.
type MockDatabasePortMockRecorder struct {
	mock *MockDatabasePort
}

// NewMockDatabasePort creates a new mock instance.
func NewMockDatabasePort(ctrl *gomock.Controller) *MockDatabasePort {
	mock := &MockDatabasePort{ctrl: ctrl}
	mock.recorder = &MockDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabasePort) EXPECT() *MockDatabasePortMockRecorder {
	return m.recorder
}

// BandwidthProfile mocks base method.
func (m *MockDatabasePort) BandwidthProfile() outbound_port.BandwidthProfileDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BandwidthProfile")
	ret0, _ := ret[0].(outbound_port.BandwidthProfileDatabasePort)
	return ret0
}

// BandwidthProfile indicates an expected call of BandwidthProfile.
func (mr *MockDatabasePortMockRecorder) BandwidthProfile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BandwidthProfile", reflect.TypeOf((*MockDatabasePort)(nil).BandwidthProfile))
}

// Client mocks base method.
func (m *MockDatabasePort) Client() outbound_port.ClientDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Client")
	ret0, _ := ret[0].(outbound_port.ClientDatabasePort)
	return ret0
}

// Client indicates an expected call of Client.
func (mr *MockDatabasePortMockRecorder) Client() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Client", reflect.TypeOf((*MockDatabasePort)(nil).Client))
}

// Customer mocks base method.
func (m *MockDatabasePort) Customer() outbound_port.CustomerDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Customer")
	ret0, _ := ret[0].(outbound_port.CustomerDatabasePort)
	return ret0
}

// Customer indicates an expected call of Customer.
func (mr *MockDatabasePortMockRecorder) Customer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Customer", reflect.TypeOf((*MockDatabasePort)(nil).Customer))
}

// DoInTransaction mocks base method.
func (m *MockDatabasePort) DoInTransaction(arg0 outbound_port.InTransaction) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoInTransaction", arg0)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoInTransaction indicates an expected call of DoInTransaction.
func (mr *MockDatabasePortMockRecorder) DoInTransaction(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoInTransaction", reflect.TypeOf((*MockDatabasePort)(nil).DoInTransaction), arg0)
}

// Invoice mocks base method.
func (m *MockDatabasePort) Invoice() outbound_port.InvoiceDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Invoice")
	ret0, _ := ret[0].(outbound_port.InvoiceDatabasePort)
	return ret0
}

// Invoice indicates an expected call of Invoice.
func (mr *MockDatabasePortMockRecorder) Invoice() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invoice", reflect.TypeOf((*MockDatabasePort)(nil).Invoice))
}

// Mikrotik mocks base method.
func (m *MockDatabasePort) Mikrotik() outbound_port.MikrotikDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mikrotik")
	ret0, _ := ret[0].(outbound_port.MikrotikDatabasePort)
	return ret0
}

// Mikrotik indicates an expected call of Mikrotik.
func (mr *MockDatabasePortMockRecorder) Mikrotik() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mikrotik", reflect.TypeOf((*MockDatabasePort)(nil).Mikrotik))
}

// Payment mocks base method.
func (m *MockDatabasePort) Payment() outbound_port.PaymentDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Payment")
	ret0, _ := ret[0].(outbound_port.PaymentDatabasePort)
	return ret0
}

// Payment indicates an expected call of Payment.
func (mr *MockDatabasePortMockRecorder) Payment() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Payment", reflect.TypeOf((*MockDatabasePort)(nil).Payment))
}

// User mocks base method.
func (m *MockDatabasePort) User() outbound_port.UserDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "User")
	ret0, _ := ret[0].(outbound_port.UserDatabasePort)
	return ret0
}

// User indicates an expected call of User.
func (mr *MockDatabasePortMockRecorder) User() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "User", reflect.TypeOf((*MockDatabasePort)(nil).User))
}
