// Code generated by MockGen. DO NOT EDIT.
// Source: registration.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	context "context"
	model "go-template/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRegistrationDatabasePort is a mock of RegistrationDatabasePort interface.
type MockRegistrationDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockRegistrationDatabasePortMockRecorder
}

// MockRegistrationDatabasePortMockRecorder is the mock recorder for MockRegistrationDatabasePort.
type MockRegistrationDatabasePortMockRecorder struct {
	mock *MockRegistrationDatabasePort
}

// NewMockRegistrationDatabasePort creates a new mock instance.
func NewMockRegistrationDatabasePort(ctrl *gomock.Controller) *MockRegistrationDatabasePort {
	mock := &MockRegistrationDatabasePort{ctrl: ctrl}
	mock.recorder = &MockRegistrationDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistrationDatabasePort) EXPECT() *MockRegistrationDatabasePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRegistrationDatabasePort) Create(ctx context.Context, registration *model.CustomerRegistration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, registration)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRegistrationDatabasePortMockRecorder) Create(ctx, registration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRegistrationDatabasePort)(nil).Create), ctx, registration)
}

// FindAll mocks base method.
func (m *MockRegistrationDatabasePort) FindAll(ctx context.Context, filter *model.RegistrationFilter) ([]model.CustomerRegistration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, filter)
	ret0, _ := ret[0].([]model.CustomerRegistration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockRegistrationDatabasePortMockRecorder) FindAll(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockRegistrationDatabasePort)(nil).FindAll), ctx, filter)
}

// FindByID mocks base method.
func (m *MockRegistrationDatabasePort) FindByID(ctx context.Context, id string) (*model.CustomerRegistration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*model.CustomerRegistration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRegistrationDatabasePortMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRegistrationDatabasePort)(nil).FindByID), ctx, id)
}

// SetApproved mocks base method.
func (m *MockRegistrationDatabasePort) SetApproved(ctx context.Context, id, approverID, customerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetApproved", ctx, id, approverID, customerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetApproved indicates an expected call of SetApproved.
func (mr *MockRegistrationDatabasePortMockRecorder) SetApproved(ctx, id, approverID, customerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetApproved", reflect.TypeOf((*MockRegistrationDatabasePort)(nil).SetApproved), ctx, id, approverID, customerID)
}

// SetRejected mocks base method.
func (m *MockRegistrationDatabasePort) SetRejected(ctx context.Context, id, approverID, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRejected", ctx, id, approverID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRejected indicates an expected call of SetRejected.
func (mr *MockRegistrationDatabasePortMockRecorder) SetRejected(ctx, id, approverID, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRejected", reflect.TypeOf((*MockRegistrationDatabasePort)(nil).SetRejected), ctx, id, approverID, reason)
}
