// Code generated by MockGen. DO NOT EDIT.
// Source: role.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "mikrops/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRoleDatabasePort is a mock of RoleDatabasePort interface.
type MockRoleDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockRoleDatabasePortMockRecorder
}

// MockRoleDatabasePortMockRecorder is the mock recorder for MockRoleDatabasePort.
type MockRoleDatabasePortMockRecorder struct {
	mock *MockRoleDatabasePort
}

// NewMockRoleDatabasePort creates a new mock instance.
func NewMockRoleDatabasePort(ctrl *gomock.Controller) *MockRoleDatabasePort {
	mock := &MockRoleDatabasePort{ctrl: ctrl}
	mock.recorder = &MockRoleDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleDatabasePort) EXPECT() *MockRoleDatabasePortMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockRoleDatabasePort) FindAll() ([]model.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]model.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockRoleDatabasePortMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockRoleDatabasePort)(nil).FindAll))
}

// FindByID mocks base method.
func (m *MockRoleDatabasePort) FindByID(id int) (model.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(model.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRoleDatabasePortMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRoleDatabasePort)(nil).FindByID), id)
}

// FindByName mocks base method.
func (m *MockRoleDatabasePort) FindByName(name string) (model.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", name)
	ret0, _ := ret[0].(model.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockRoleDatabasePortMockRecorder) FindByName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockRoleDatabasePort)(nil).FindByName), name)
}
