// Code generated by MockGen. DO NOT EDIT.
// Source: nas.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "mikrops/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockNasDatabasePort is a mock of NasDatabasePort interface.
type MockNasDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockNasDatabasePortMockRecorder
}

// MockNasDatabasePortMockRecorder is the mock recorder for MockNasDatabasePort.
type MockNasDatabasePortMockRecorder struct {
	mock *MockNasDatabasePort
}

// NewMockNasDatabasePort creates a new mock instance.
func NewMockNasDatabasePort(ctrl *gomock.Controller) *MockNasDatabasePort {
	mock := &MockNasDatabasePort{ctrl: ctrl}
	mock.recorder = &MockNasDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNasDatabasePort) EXPECT() *MockNasDatabasePortMockRecorder {
	return m.recorder
}

// CountByTenantID mocks base method.
func (m *MockNasDatabasePort) CountByTenantID(tenantID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByTenantID", tenantID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByTenantID indicates an expected call of CountByTenantID.
func (mr *MockNasDatabasePortMockRecorder) CountByTenantID(tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByTenantID", reflect.TypeOf((*MockNasDatabasePort)(nil).CountByTenantID), tenantID)
}

// Create mocks base method.
func (m *MockNasDatabasePort) Create(data model.NasInput) (model.Nas, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", data)
	ret0, _ := ret[0].(model.Nas)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockNasDatabasePortMockRecorder) Create(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNasDatabasePort)(nil).Create), data)
}

// Delete mocks base method.
func (m *MockNasDatabasePort) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockNasDatabasePortMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNasDatabasePort)(nil).Delete), id)
}

// FindByFilter mocks base method.
func (m *MockNasDatabasePort) FindByFilter(filter model.NasFilter) ([]model.Nas, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFilter", filter)
	ret0, _ := ret[0].([]model.Nas)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFilter indicates an expected call of FindByFilter.
func (mr *MockNasDatabasePortMockRecorder) FindByFilter(filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFilter", reflect.TypeOf((*MockNasDatabasePort)(nil).FindByFilter), filter)
}

// FindByID mocks base method.
func (m *MockNasDatabasePort) FindByID(id string) (model.Nas, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(model.Nas)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockNasDatabasePortMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockNasDatabasePort)(nil).FindByID), id)
}

// Update mocks base method.
func (m *MockNasDatabasePort) Update(id string, data model.NasInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockNasDatabasePortMockRecorder) Update(id, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockNasDatabasePort)(nil).Update), id, data)
}
