// Code generated by MockGen. DO NOT EDIT.
// Source: payment.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "mikrops/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPaymentDatabasePort is a mock of PaymentDatabasePort interface.
type MockPaymentDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentDatabasePortMockRecorder
}

// MockPaymentDatabasePortMockRecorder is the mock recorder for MockPaymentDatabasePort.
type MockPaymentDatabasePortMockRecorder struct {
	mock *MockPaymentDatabasePort
}

// NewMockPaymentDatabasePort creates a new mock instance.
func NewMockPaymentDatabasePort(ctrl *gomock.Controller) *MockPaymentDatabasePort {
	mock := &MockPaymentDatabasePort{ctrl: ctrl}
	mock.recorder = &MockPaymentDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentDatabasePort) EXPECT() *MockPaymentDatabasePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPaymentDatabasePort) Create(data model.PaymentInput) (model.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", data)
	ret0, _ := ret[0].(model.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPaymentDatabasePortMockRecorder) Create(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPaymentDatabasePort)(nil).Create), data)
}

// Delete mocks base method.
func (m *MockPaymentDatabasePort) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPaymentDatabasePortMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPaymentDatabasePort)(nil).Delete), id)
}

// FindByFilter mocks base method.
func (m *MockPaymentDatabasePort) FindByFilter(filter model.PaymentFilter) ([]model.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFilter", filter)
	ret0, _ := ret[0].([]model.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFilter indicates an expected call of FindByFilter.
func (mr *MockPaymentDatabasePortMockRecorder) FindByFilter(filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFilter", reflect.TypeOf((*MockPaymentDatabasePort)(nil).FindByFilter), filter)
}

// FindByID mocks base method.
func (m *MockPaymentDatabasePort) FindByID(id string) (model.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(model.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPaymentDatabasePortMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPaymentDatabasePort)(nil).FindByID), id)
}

// Update mocks base method.
func (m *MockPaymentDatabasePort) Update(id string, data model.PaymentInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPaymentDatabasePortMockRecorder) Update(id, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPaymentDatabasePort)(nil).Update), id, data)
}
