// Code generated by MockGen. DO NOT EDIT.
// Source: refund.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "go-template/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRefundDatabasePort is a mock of RefundDatabasePort interface.
type MockRefundDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockRefundDatabasePortMockRecorder
}

// MockRefundDatabasePortMockRecorder is the mock recorder for MockRefundDatabasePort.
type MockRefundDatabasePortMockRecorder struct {
	mock *MockRefundDatabasePort
}

// NewMockRefundDatabasePort creates a new mock instance.
func NewMockRefundDatabasePort(ctrl *gomock.Controller) *MockRefundDatabasePort {
	mock := &MockRefundDatabasePort{ctrl: ctrl}
	mock.recorder = &MockRefundDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefundDatabasePort) EXPECT() *MockRefundDatabasePortMockRecorder {
	return m.recorder
}

// Approve mocks base method.
func (m *MockRefundDatabasePort) Approve(id, approvedBy string) (*model.Refund, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Approve", id, approvedBy)
	ret0, _ := ret[0].(*model.Refund)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Approve indicates an expected call of Approve.
func (mr *MockRefundDatabasePortMockRecorder) Approve(id, approvedBy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Approve", reflect.TypeOf((*MockRefundDatabasePort)(nil).Approve), id, approvedBy)
}

// Complete mocks base method.
func (m *MockRefundDatabasePort) Complete(id, processedBy, xenditRefundID string) (*model.Refund, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", id, processedBy, xenditRefundID)
	ret0, _ := ret[0].(*model.Refund)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Complete indicates an expected call of Complete.
func (mr *MockRefundDatabasePortMockRecorder) Complete(id, processedBy, xenditRefundID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockRefundDatabasePort)(nil).Complete), id, processedBy, xenditRefundID)
}

// Create mocks base method.
func (m *MockRefundDatabasePort) Create(input *model.RefundInput) (*model.Refund, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", input)
	ret0, _ := ret[0].(*model.Refund)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRefundDatabasePortMockRecorder) Create(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRefundDatabasePort)(nil).Create), input)
}

// Delete mocks base method.
func (m *MockRefundDatabasePort) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRefundDatabasePortMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRefundDatabasePort)(nil).Delete), id)
}

// FindByFilter mocks base method.
func (m *MockRefundDatabasePort) FindByFilter(filter model.RefundFilter, lock bool) ([]model.Refund, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFilter", filter, lock)
	ret0, _ := ret[0].([]model.Refund)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFilter indicates an expected call of FindByFilter.
func (mr *MockRefundDatabasePortMockRecorder) FindByFilter(filter, lock interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFilter", reflect.TypeOf((*MockRefundDatabasePort)(nil).FindByFilter), filter, lock)
}

// FindByID mocks base method.
func (m *MockRefundDatabasePort) FindByID(id string) (*model.Refund, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*model.Refund)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRefundDatabasePortMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRefundDatabasePort)(nil).FindByID), id)
}

// FindPendingRefunds mocks base method.
func (m *MockRefundDatabasePort) FindPendingRefunds() ([]model.Refund, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPendingRefunds")
	ret0, _ := ret[0].([]model.Refund)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPendingRefunds indicates an expected call of FindPendingRefunds.
func (mr *MockRefundDatabasePortMockRecorder) FindPendingRefunds() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPendingRefunds", reflect.TypeOf((*MockRefundDatabasePort)(nil).FindPendingRefunds))
}

// Process mocks base method.
func (m *MockRefundDatabasePort) Process(id, processedBy string) (*model.Refund, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", id, processedBy)
	ret0, _ := ret[0].(*model.Refund)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Process indicates an expected call of Process.
func (mr *MockRefundDatabasePortMockRecorder) Process(id, processedBy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockRefundDatabasePort)(nil).Process), id, processedBy)
}

// Reject mocks base method.
func (m *MockRefundDatabasePort) Reject(id, rejectedBy, reason string) (*model.Refund, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reject", id, rejectedBy, reason)
	ret0, _ := ret[0].(*model.Refund)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reject indicates an expected call of Reject.
func (mr *MockRefundDatabasePortMockRecorder) Reject(id, rejectedBy, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reject", reflect.TypeOf((*MockRefundDatabasePort)(nil).Reject), id, rejectedBy, reason)
}

// Update mocks base method.
func (m *MockRefundDatabasePort) Update(id string, input *model.RefundInput) (*model.Refund, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, input)
	ret0, _ := ret[0].(*model.Refund)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRefundDatabasePortMockRecorder) Update(id, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRefundDatabasePort)(nil).Update), id, input)
}
