// Code generated by MockGen. DO NOT EDIT.
// Source: permission.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "mikrops/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPermissionDatabasePort is a mock of PermissionDatabasePort interface.
type MockPermissionDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionDatabasePortMockRecorder
}

// MockPermissionDatabasePortMockRecorder is the mock recorder for MockPermissionDatabasePort.
type MockPermissionDatabasePortMockRecorder struct {
	mock *MockPermissionDatabasePort
}

// NewMockPermissionDatabasePort creates a new mock instance.
func NewMockPermissionDatabasePort(ctrl *gomock.Controller) *MockPermissionDatabasePort {
	mock := &MockPermissionDatabasePort{ctrl: ctrl}
	mock.recorder = &MockPermissionDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionDatabasePort) EXPECT() *MockPermissionDatabasePortMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockPermissionDatabasePort) FindAll() ([]model.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]model.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockPermissionDatabasePortMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockPermissionDatabasePort)(nil).FindAll))
}

// FindByRoleID mocks base method.
func (m *MockPermissionDatabasePort) FindByRoleID(roleID int) ([]model.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRoleID", roleID)
	ret0, _ := ret[0].([]model.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRoleID indicates an expected call of FindByRoleID.
func (mr *MockPermissionDatabasePortMockRecorder) FindByRoleID(roleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRoleID", reflect.TypeOf((*MockPermissionDatabasePort)(nil).FindByRoleID), roleID)
}
