// Code generated by MockGen. DO NOT EDIT.
// Source: pppoe_account.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "mikrops/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPppoeAccountDatabasePort is a mock of PppoeAccountDatabasePort interface.
type MockPppoeAccountDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockPppoeAccountDatabasePortMockRecorder
}

// MockPppoeAccountDatabasePortMockRecorder is the mock recorder for MockPppoeAccountDatabasePort.
type MockPppoeAccountDatabasePortMockRecorder struct {
	mock *MockPppoeAccountDatabasePort
}

// NewMockPppoeAccountDatabasePort creates a new mock instance.
func NewMockPppoeAccountDatabasePort(ctrl *gomock.Controller) *MockPppoeAccountDatabasePort {
	mock := &MockPppoeAccountDatabasePort{ctrl: ctrl}
	mock.recorder = &MockPppoeAccountDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPppoeAccountDatabasePort) EXPECT() *MockPppoeAccountDatabasePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPppoeAccountDatabasePort) Create(data model.PppoeAccountInput) (model.PppoeAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", data)
	ret0, _ := ret[0].(model.PppoeAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPppoeAccountDatabasePortMockRecorder) Create(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPppoeAccountDatabasePort)(nil).Create), data)
}

// Delete mocks base method.
func (m *MockPppoeAccountDatabasePort) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPppoeAccountDatabasePortMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPppoeAccountDatabasePort)(nil).Delete), id)
}

// FindByFilter mocks base method.
func (m *MockPppoeAccountDatabasePort) FindByFilter(filter model.PppoeAccountFilter) ([]model.PppoeAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFilter", filter)
	ret0, _ := ret[0].([]model.PppoeAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFilter indicates an expected call of FindByFilter.
func (mr *MockPppoeAccountDatabasePortMockRecorder) FindByFilter(filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFilter", reflect.TypeOf((*MockPppoeAccountDatabasePort)(nil).FindByFilter), filter)
}

// FindByID mocks base method.
func (m *MockPppoeAccountDatabasePort) FindByID(id string) (model.PppoeAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(model.PppoeAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPppoeAccountDatabasePortMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPppoeAccountDatabasePort)(nil).FindByID), id)
}

// Update mocks base method.
func (m *MockPppoeAccountDatabasePort) Update(id string, data model.PppoeAccountInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPppoeAccountDatabasePortMockRecorder) Update(id, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPppoeAccountDatabasePort)(nil).Update), id, data)
}
