// Code generated by MockGen. DO NOT EDIT.
// Source: internal/port/outbound/system_setting.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "go-template/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSystemSettingDatabasePort is a mock of SystemSettingDatabasePort interface.
type MockSystemSettingDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockSystemSettingDatabasePortMockRecorder
}

// MockSystemSettingDatabasePortMockRecorder is the mock recorder for MockSystemSettingDatabasePort.
type MockSystemSettingDatabasePortMockRecorder struct {
	mock *MockSystemSettingDatabasePort
}

// NewMockSystemSettingDatabasePort creates a new mock instance.
func NewMockSystemSettingDatabasePort(ctrl *gomock.Controller) *MockSystemSettingDatabasePort {
	mock := &MockSystemSettingDatabasePort{ctrl: ctrl}
	mock.recorder = &MockSystemSettingDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSystemSettingDatabasePort) EXPECT() *MockSystemSettingDatabasePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSystemSettingDatabasePort) Create(setting *model.SystemSetting) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", setting)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSystemSettingDatabasePortMockRecorder) Create(setting interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSystemSettingDatabasePort)(nil).Create), setting)
}

// Delete mocks base method.
func (m *MockSystemSettingDatabasePort) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSystemSettingDatabasePortMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSystemSettingDatabasePort)(nil).Delete), id)
}

// FindAll mocks base method.
func (m *MockSystemSettingDatabasePort) FindAll() ([]model.SystemSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]model.SystemSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockSystemSettingDatabasePortMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockSystemSettingDatabasePort)(nil).FindAll))
}

// FindByCategory mocks base method.
func (m *MockSystemSettingDatabasePort) FindByCategory(category string) ([]model.SystemSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCategory", category)
	ret0, _ := ret[0].([]model.SystemSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCategory indicates an expected call of FindByCategory.
func (mr *MockSystemSettingDatabasePortMockRecorder) FindByCategory(category interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCategory", reflect.TypeOf((*MockSystemSettingDatabasePort)(nil).FindByCategory), category)
}

// FindByID mocks base method.
func (m *MockSystemSettingDatabasePort) FindByID(id string) (*model.SystemSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*model.SystemSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockSystemSettingDatabasePortMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockSystemSettingDatabasePort)(nil).FindByID), id)
}

// FindByKey mocks base method.
func (m *MockSystemSettingDatabasePort) FindByKey(key string) (*model.SystemSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByKey", key)
	ret0, _ := ret[0].(*model.SystemSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByKey indicates an expected call of FindByKey.
func (mr *MockSystemSettingDatabasePortMockRecorder) FindByKey(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByKey", reflect.TypeOf((*MockSystemSettingDatabasePort)(nil).FindByKey), key)
}

// FindPublic mocks base method.
func (m *MockSystemSettingDatabasePort) FindPublic() ([]model.SystemSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPublic")
	ret0, _ := ret[0].([]model.SystemSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPublic indicates an expected call of FindPublic.
func (mr *MockSystemSettingDatabasePortMockRecorder) FindPublic() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPublic", reflect.TypeOf((*MockSystemSettingDatabasePort)(nil).FindPublic))
}

// Update mocks base method.
func (m *MockSystemSettingDatabasePort) Update(setting *model.SystemSetting) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", setting)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSystemSettingDatabasePortMockRecorder) Update(setting interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSystemSettingDatabasePort)(nil).Update), setting)
}

// UpdateByKey mocks base method.
func (m *MockSystemSettingDatabasePort) UpdateByKey(key, value, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByKey", key, value, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByKey indicates an expected call of UpdateByKey.
func (mr *MockSystemSettingDatabasePortMockRecorder) UpdateByKey(key, value, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByKey", reflect.TypeOf((*MockSystemSettingDatabasePort)(nil).UpdateByKey), key, value, userID)
}
