// Code generated by MockGen. DO NOT EDIT.
// Source: staff.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "mikrops/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStaffDatabasePort is a mock of StaffDatabasePort interface.
type MockStaffDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockStaffDatabasePortMockRecorder
}

// MockStaffDatabasePortMockRecorder is the mock recorder for MockStaffDatabasePort.
type MockStaffDatabasePortMockRecorder struct {
	mock *MockStaffDatabasePort
}

// NewMockStaffDatabasePort creates a new mock instance.
func NewMockStaffDatabasePort(ctrl *gomock.Controller) *MockStaffDatabasePort {
	mock := &MockStaffDatabasePort{ctrl: ctrl}
	mock.recorder = &MockStaffDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStaffDatabasePort) EXPECT() *MockStaffDatabasePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStaffDatabasePort) Create(data model.StaffInput) (model.Staff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", data)
	ret0, _ := ret[0].(model.Staff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockStaffDatabasePortMockRecorder) Create(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStaffDatabasePort)(nil).Create), data)
}

// Delete mocks base method.
func (m *MockStaffDatabasePort) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStaffDatabasePortMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStaffDatabasePort)(nil).Delete), id)
}

// FindByEmail mocks base method.
func (m *MockStaffDatabasePort) FindByEmail(email string) (model.Staff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", email)
	ret0, _ := ret[0].(model.Staff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockStaffDatabasePortMockRecorder) FindByEmail(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockStaffDatabasePort)(nil).FindByEmail), email)
}

// FindByFilter mocks base method.
func (m *MockStaffDatabasePort) FindByFilter(filter model.StaffFilter) ([]model.Staff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFilter", filter)
	ret0, _ := ret[0].([]model.Staff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFilter indicates an expected call of FindByFilter.
func (mr *MockStaffDatabasePortMockRecorder) FindByFilter(filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFilter", reflect.TypeOf((*MockStaffDatabasePort)(nil).FindByFilter), filter)
}

// FindByID mocks base method.
func (m *MockStaffDatabasePort) FindByID(id string) (model.Staff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(model.Staff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockStaffDatabasePortMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockStaffDatabasePort)(nil).FindByID), id)
}

// Update mocks base method.
func (m *MockStaffDatabasePort) Update(id string, data model.StaffInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockStaffDatabasePortMockRecorder) Update(id, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStaffDatabasePort)(nil).Update), id, data)
}

// MockStaffCachePort is a mock of StaffCachePort interface.
type MockStaffCachePort struct {
	ctrl     *gomock.Controller
	recorder *MockStaffCachePortMockRecorder
}

// MockStaffCachePortMockRecorder is the mock recorder for MockStaffCachePort.
type MockStaffCachePortMockRecorder struct {
	mock *MockStaffCachePort
}

// NewMockStaffCachePort creates a new mock instance.
func NewMockStaffCachePort(ctrl *gomock.Controller) *MockStaffCachePort {
	mock := &MockStaffCachePort{ctrl: ctrl}
	mock.recorder = &MockStaffCachePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStaffCachePort) EXPECT() *MockStaffCachePortMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockStaffCachePort) Delete(staffID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", staffID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStaffCachePortMockRecorder) Delete(staffID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStaffCachePort)(nil).Delete), staffID)
}

// Get mocks base method.
func (m *MockStaffCachePort) Get(staffID string) (model.Staff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", staffID)
	ret0, _ := ret[0].(model.Staff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStaffCachePortMockRecorder) Get(staffID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStaffCachePort)(nil).Get), staffID)
}

// Set mocks base method.
func (m *MockStaffCachePort) Set(data model.Staff) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockStaffCachePortMockRecorder) Set(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockStaffCachePort)(nil).Set), data)
}
