// Code generated by MockGen. DO NOT EDIT.
// Source: internal/port/outbound/registry_cache.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "go-template/internal/model"
	outbound_port "go-template/internal/port/outbound"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCachePort is a mock of CachePort interface.
type MockCachePort struct {
	ctrl     *gomock.Controller
	recorder *MockCachePortMockRecorder
}

// MockCachePortMockRecorder is the mock recorder for MockCachePort.
type MockCachePortMockRecorder struct {
	mock *MockCachePort
}

// NewMockCachePort creates a new mock instance.
func NewMockCachePort(ctrl *gomock.Controller) *MockCachePort {
	mock := &MockCachePort{ctrl: ctrl}
	mock.recorder = &MockCachePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCachePort) EXPECT() *MockCachePortMockRecorder {
	return m.recorder
}

// Client mocks base method.
func (m *MockCachePort) Client() outbound_port.ClientCachePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Client")
	ret0, _ := ret[0].(outbound_port.ClientCachePort)
	return ret0
}

// Client indicates an expected call of Client.
func (mr *MockCachePortMockRecorder) Client() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Client", reflect.TypeOf((*MockCachePort)(nil).Client))
}

// PppoePubSub mocks base method.
func (m *MockCachePort) PppoePubSub() outbound_port.PppoeCachePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PppoePubSub")
	ret0, _ := ret[0].(outbound_port.PppoeCachePort)
	return ret0
}

// PppoePubSub indicates an expected call of PppoePubSub.
func (mr *MockCachePortMockRecorder) PppoePubSub() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PppoePubSub", reflect.TypeOf((*MockCachePort)(nil).PppoePubSub))
}

// MockPppoeCachePort is a mock of PppoeCachePort interface.
type MockPppoeCachePort struct {
	ctrl     *gomock.Controller
	recorder *MockPppoeCachePortMockRecorder
}

// MockPppoeCachePortMockRecorder is the mock recorder for MockPppoeCachePort.
type MockPppoeCachePortMockRecorder struct {
	mock *MockPppoeCachePort
}

// NewMockPppoeCachePort creates a new mock instance.
func NewMockPppoeCachePort(ctrl *gomock.Controller) *MockPppoeCachePort {
	mock := &MockPppoeCachePort{ctrl: ctrl}
	mock.recorder = &MockPppoeCachePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPppoeCachePort) EXPECT() *MockPppoeCachePortMockRecorder {
	return m.recorder
}

// PublishSessionEvent mocks base method.
func (m *MockPppoeCachePort) PublishSessionEvent(event string, data interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishSessionEvent", event, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishSessionEvent indicates an expected call of PublishSessionEvent.
func (mr *MockPppoeCachePortMockRecorder) PublishSessionEvent(event, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishSessionEvent", reflect.TypeOf((*MockPppoeCachePort)(nil).PublishSessionEvent), event, data)
}

// SubscribeToSessionEvents mocks base method.
func (m *MockPppoeCachePort) SubscribeToSessionEvents() (<-chan model.WebSocketMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeToSessionEvents")
	ret0, _ := ret[0].(<-chan model.WebSocketMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeToSessionEvents indicates an expected call of SubscribeToSessionEvents.
func (mr *MockPppoeCachePortMockRecorder) SubscribeToSessionEvents() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeToSessionEvents", reflect.TypeOf((*MockPppoeCachePort)(nil).SubscribeToSessionEvents))
}
