// Code generated by MockGen. DO NOT EDIT.
// Source: mikrotik_sync_log.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "mikrops/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMikrotikSyncLogDatabasePort is a mock of MikrotikSyncLogDatabasePort interface.
type MockMikrotikSyncLogDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockMikrotikSyncLogDatabasePortMockRecorder
}

// MockMikrotikSyncLogDatabasePortMockRecorder is the mock recorder for MockMikrotikSyncLogDatabasePort.
type MockMikrotikSyncLogDatabasePortMockRecorder struct {
	mock *MockMikrotikSyncLogDatabasePort
}

// NewMockMikrotikSyncLogDatabasePort creates a new mock instance.
func NewMockMikrotikSyncLogDatabasePort(ctrl *gomock.Controller) *MockMikrotikSyncLogDatabasePort {
	mock := &MockMikrotikSyncLogDatabasePort{ctrl: ctrl}
	mock.recorder = &MockMikrotikSyncLogDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMikrotikSyncLogDatabasePort) EXPECT() *MockMikrotikSyncLogDatabasePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMikrotikSyncLogDatabasePort) Create(data model.MikrotikSyncLogInput) (model.MikrotikSyncLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", data)
	ret0, _ := ret[0].(model.MikrotikSyncLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMikrotikSyncLogDatabasePortMockRecorder) Create(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMikrotikSyncLogDatabasePort)(nil).Create), data)
}

// FindByFilter mocks base method.
func (m *MockMikrotikSyncLogDatabasePort) FindByFilter(filter model.MikrotikSyncLogFilter) ([]model.MikrotikSyncLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFilter", filter)
	ret0, _ := ret[0].([]model.MikrotikSyncLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFilter indicates an expected call of FindByFilter.
func (mr *MockMikrotikSyncLogDatabasePortMockRecorder) FindByFilter(filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFilter", reflect.TypeOf((*MockMikrotikSyncLogDatabasePort)(nil).FindByFilter), filter)
}

// FindByID mocks base method.
func (m *MockMikrotikSyncLogDatabasePort) FindByID(id string) (model.MikrotikSyncLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(model.MikrotikSyncLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockMikrotikSyncLogDatabasePortMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockMikrotikSyncLogDatabasePort)(nil).FindByID), id)
}
