// Code generated by MockGen. DO NOT EDIT.
// Source: internal/port/outbound/mikrotik_port.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "go-template/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMikrotikPort is a mock of MikrotikPort interface.
type MockMikrotikPort struct {
	ctrl     *gomock.Controller
	recorder *MockMikrotikPortMockRecorder
}

// MockMikrotikPortMockRecorder is the mock recorder for MockMikrotikPort.
type MockMikrotikPortMockRecorder struct {
	mock *MockMikrotikPort
}

// NewMockMikrotikPort creates a new mock instance.
func NewMockMikrotikPort(ctrl *gomock.Controller) *MockMikrotikPort {
	mock := &MockMikrotikPort{ctrl: ctrl}
	mock.recorder = &MockMikrotikPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMikrotikPort) EXPECT() *MockMikrotikPortMockRecorder {
	return m.recorder
}

// CreateSecret mocks base method.
func (m *MockMikrotikPort) CreateSecret(router *model.MikrotikRouter, secret *model.PppoeSecret) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSecret", router, secret)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSecret indicates an expected call of CreateSecret.
func (mr *MockMikrotikPortMockRecorder) CreateSecret(router, secret interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSecret", reflect.TypeOf((*MockMikrotikPort)(nil).CreateSecret), router, secret)
}

// UpdateSecret mocks base method.
func (m *MockMikrotikPort) UpdateSecret(router *model.MikrotikRouter, secret *model.PppoeSecret) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSecret", router, secret)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSecret indicates an expected call of UpdateSecret.
func (mr *MockMikrotikPortMockRecorder) UpdateSecret(router, secret interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSecret", reflect.TypeOf((*MockMikrotikPort)(nil).UpdateSecret), router, secret)
}

// DeleteSecret mocks base method.
func (m *MockMikrotikPort) DeleteSecret(router *model.MikrotikRouter, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSecret", router, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSecret indicates an expected call of DeleteSecret.
func (mr *MockMikrotikPortMockRecorder) DeleteSecret(router, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSecret", reflect.TypeOf((*MockMikrotikPort)(nil).DeleteSecret), router, id)
}

// GetSecret mocks base method.
func (m *MockMikrotikPort) GetSecret(router *model.MikrotikRouter, id string) (*model.PppoeSecret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecret", router, id)
	ret0, _ := ret[0].(*model.PppoeSecret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecret indicates an expected call of GetSecret.
func (mr *MockMikrotikPortMockRecorder) GetSecret(router, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecret", reflect.TypeOf((*MockMikrotikPort)(nil).GetSecret), router, id)
}

// ListSecrets mocks base method.
func (m *MockMikrotikPort) ListSecrets(router *model.MikrotikRouter) ([]model.PppoeSecret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSecrets", router)
	ret0, _ := ret[0].([]model.PppoeSecret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSecrets indicates an expected call of ListSecrets.
func (mr *MockMikrotikPortMockRecorder) ListSecrets(router interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSecrets", reflect.TypeOf((*MockMikrotikPort)(nil).ListSecrets), router)
}

// CreateProfile mocks base method.
func (m *MockMikrotikPort) CreateProfile(router *model.MikrotikRouter, profile *model.PppoeProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProfile", router, profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateProfile indicates an expected call of CreateProfile.
func (mr *MockMikrotikPortMockRecorder) CreateProfile(router, profile interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProfile", reflect.TypeOf((*MockMikrotikPort)(nil).CreateProfile), router, profile)
}

// UpdateProfile mocks base method.
func (m *MockMikrotikPort) UpdateProfile(router *model.MikrotikRouter, profile *model.PppoeProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", router, profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockMikrotikPortMockRecorder) UpdateProfile(router, profile interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockMikrotikPort)(nil).UpdateProfile), router, profile)
}

// DeleteProfile mocks base method.
func (m *MockMikrotikPort) DeleteProfile(router *model.MikrotikRouter, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProfile", router, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProfile indicates an expected call of DeleteProfile.
func (mr *MockMikrotikPortMockRecorder) DeleteProfile(router, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProfile", reflect.TypeOf((*MockMikrotikPort)(nil).DeleteProfile), router, id)
}

// GetProfile mocks base method.
func (m *MockMikrotikPort) GetProfile(router *model.MikrotikRouter, id string) (*model.PppoeProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", router, id)
	ret0, _ := ret[0].(*model.PppoeProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockMikrotikPortMockRecorder) GetProfile(router, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockMikrotikPort)(nil).GetProfile), router, id)
}

// ListProfiles mocks base method.
func (m *MockMikrotikPort) ListProfiles(router *model.MikrotikRouter) ([]model.PppoeProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProfiles", router)
	ret0, _ := ret[0].([]model.PppoeProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProfiles indicates an expected call of ListProfiles.
func (mr *MockMikrotikPortMockRecorder) ListProfiles(router interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProfiles", reflect.TypeOf((*MockMikrotikPort)(nil).ListProfiles), router)
}

// ListActiveSessions mocks base method.
func (m *MockMikrotikPort) ListActiveSessions(router *model.MikrotikRouter) ([]model.PppoeActive, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveSessions", router)
	ret0, _ := ret[0].([]model.PppoeActive)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveSessions indicates an expected call of ListActiveSessions.
func (mr *MockMikrotikPortMockRecorder) ListActiveSessions(router interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveSessions", reflect.TypeOf((*MockMikrotikPort)(nil).ListActiveSessions), router)
}

// GetActiveSession mocks base method.
func (m *MockMikrotikPort) GetActiveSession(router *model.MikrotikRouter, id string) (*model.PppoeActive, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveSession", router, id)
	ret0, _ := ret[0].(*model.PppoeActive)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveSession indicates an expected call of GetActiveSession.
func (mr *MockMikrotikPortMockRecorder) GetActiveSession(router, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveSession", reflect.TypeOf((*MockMikrotikPort)(nil).GetActiveSession), router, id)
}

// RemoveActiveSession mocks base method.
func (m *MockMikrotikPort) RemoveActiveSession(router *model.MikrotikRouter, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveActiveSession", router, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveActiveSession indicates an expected call of RemoveActiveSession.
func (mr *MockMikrotikPortMockRecorder) RemoveActiveSession(router, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveActiveSession", reflect.TypeOf((*MockMikrotikPort)(nil).RemoveActiveSession), router, id)
}

// MockMikrotikDatabasePort is a mock of MikrotikDatabasePort interface.
type MockMikrotikDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockMikrotikDatabasePortMockRecorder
}

// MockMikrotikDatabasePortMockRecorder is the mock recorder for MockMikrotikDatabasePort.
type MockMikrotikDatabasePortMockRecorder struct {
	mock *MockMikrotikDatabasePort
}

// NewMockMikrotikDatabasePort creates a new mock instance.
func NewMockMikrotikDatabasePort(ctrl *gomock.Controller) *MockMikrotikDatabasePort {
	mock := &MockMikrotikDatabasePort{ctrl: ctrl}
	mock.recorder = &MockMikrotikDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMikrotikDatabasePort) EXPECT() *MockMikrotikDatabasePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMikrotikDatabasePort) Create(router *model.MikrotikRouter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", router)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMikrotikDatabasePortMockRecorder) Create(router interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMikrotikDatabasePort)(nil).Create), router)
}

// FindByID mocks base method.
func (m *MockMikrotikDatabasePort) FindByID(id uint) (*model.MikrotikRouter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*model.MikrotikRouter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockMikrotikDatabasePortMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockMikrotikDatabasePort)(nil).FindByID), id)
}

// FindAll mocks base method.
func (m *MockMikrotikDatabasePort) FindAll() ([]model.MikrotikRouter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]model.MikrotikRouter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockMikrotikDatabasePortMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockMikrotikDatabasePort)(nil).FindAll))
}

// Update mocks base method.
func (m *MockMikrotikDatabasePort) Update(router *model.MikrotikRouter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", router)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMikrotikDatabasePortMockRecorder) Update(router interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMikrotikDatabasePort)(nil).Update), router)
}

// Delete mocks base method.
func (m *MockMikrotikDatabasePort) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMikrotikDatabasePortMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMikrotikDatabasePort)(nil).Delete), id)
}
