// Code generated by MockGen. DO NOT EDIT.
// Source: internal/port/outbound/user.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "go-template/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserDatabasePort is a mock of UserDatabasePort interface.
type MockUserDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockUserDatabasePortMockRecorder
}

// MockUserDatabasePortMockRecorder is the mock recorder for MockUserDatabasePort.
type MockUserDatabasePortMockRecorder struct {
	mock *MockUserDatabasePort
}

// NewMockUserDatabasePort creates a new mock instance.
func NewMockUserDatabasePort(ctrl *gomock.Controller) *MockUserDatabasePort {
	mock := &MockUserDatabasePort{ctrl: ctrl}
	mock.recorder = &MockUserDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserDatabasePort) EXPECT() *MockUserDatabasePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserDatabasePort) Create(user *model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserDatabasePortMockRecorder) Create(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserDatabasePort)(nil).Create), user)
}

// FindByEmail mocks base method.
func (m *MockUserDatabasePort) FindByEmail(email string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", email)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockUserDatabasePortMockRecorder) FindByEmail(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockUserDatabasePort)(nil).FindByEmail), email)
}

// FindByID mocks base method.
func (m *MockUserDatabasePort) FindByID(id uint) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockUserDatabasePortMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockUserDatabasePort)(nil).FindByID), id)
}

// Update mocks base method.
func (m *MockUserDatabasePort) Update(user model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserDatabasePortMockRecorder) Update(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserDatabasePort)(nil).Update), user)
}
