// Code generated by MockGen. DO NOT EDIT.
// Source: customer.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "mikrops/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCustomerDatabasePort is a mock of CustomerDatabasePort interface.
type MockCustomerDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerDatabasePortMockRecorder
}

// MockCustomerDatabasePortMockRecorder is the mock recorder for MockCustomerDatabasePort.
type MockCustomerDatabasePortMockRecorder struct {
	mock *MockCustomerDatabasePort
}

// NewMockCustomerDatabasePort creates a new mock instance.
func NewMockCustomerDatabasePort(ctrl *gomock.Controller) *MockCustomerDatabasePort {
	mock := &MockCustomerDatabasePort{ctrl: ctrl}
	mock.recorder = &MockCustomerDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerDatabasePort) EXPECT() *MockCustomerDatabasePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCustomerDatabasePort) Create(data model.CustomerInput) (model.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", data)
	ret0, _ := ret[0].(model.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCustomerDatabasePortMockRecorder) Create(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCustomerDatabasePort)(nil).Create), data)
}

// Delete mocks base method.
func (m *MockCustomerDatabasePort) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCustomerDatabasePortMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCustomerDatabasePort)(nil).Delete), id)
}

// FindByFilter mocks base method.
func (m *MockCustomerDatabasePort) FindByFilter(filter model.CustomerFilter) ([]model.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFilter", filter)
	ret0, _ := ret[0].([]model.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFilter indicates an expected call of FindByFilter.
func (mr *MockCustomerDatabasePortMockRecorder) FindByFilter(filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFilter", reflect.TypeOf((*MockCustomerDatabasePort)(nil).FindByFilter), filter)
}

// FindByID mocks base method.
func (m *MockCustomerDatabasePort) FindByID(id string) (model.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(model.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockCustomerDatabasePortMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCustomerDatabasePort)(nil).FindByID), id)
}

// FindByUsername mocks base method.
func (m *MockCustomerDatabasePort) FindByUsername(username string) (model.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUsername", username)
	ret0, _ := ret[0].(model.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUsername indicates an expected call of FindByUsername.
func (mr *MockCustomerDatabasePortMockRecorder) FindByUsername(username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUsername", reflect.TypeOf((*MockCustomerDatabasePort)(nil).FindByUsername), username)
}

// Update mocks base method.
func (m *MockCustomerDatabasePort) Update(id string, data model.CustomerInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCustomerDatabasePortMockRecorder) Update(id, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCustomerDatabasePort)(nil).Update), id, data)
}

// MockCustomerCachePort is a mock of CustomerCachePort interface.
type MockCustomerCachePort struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerCachePortMockRecorder
}

// MockCustomerCachePortMockRecorder is the mock recorder for MockCustomerCachePort.
type MockCustomerCachePortMockRecorder struct {
	mock *MockCustomerCachePort
}

// NewMockCustomerCachePort creates a new mock instance.
func NewMockCustomerCachePort(ctrl *gomock.Controller) *MockCustomerCachePort {
	mock := &MockCustomerCachePort{ctrl: ctrl}
	mock.recorder = &MockCustomerCachePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerCachePort) EXPECT() *MockCustomerCachePortMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockCustomerCachePort) Delete(customerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", customerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCustomerCachePortMockRecorder) Delete(customerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCustomerCachePort)(nil).Delete), customerID)
}

// Get mocks base method.
func (m *MockCustomerCachePort) Get(customerID string) (model.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", customerID)
	ret0, _ := ret[0].(model.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCustomerCachePortMockRecorder) Get(customerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCustomerCachePort)(nil).Get), customerID)
}

// Set mocks base method.
func (m *MockCustomerCachePort) Set(data model.Customer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockCustomerCachePortMockRecorder) Set(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCustomerCachePort)(nil).Set), data)
}
