// Code generated by MockGen. DO NOT EDIT.
// Source: customer_registration.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "mikrops/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCustomerRegistrationDatabasePort is a mock of CustomerRegistrationDatabasePort interface.
type MockCustomerRegistrationDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerRegistrationDatabasePortMockRecorder
}

// MockCustomerRegistrationDatabasePortMockRecorder is the mock recorder for MockCustomerRegistrationDatabasePort.
type MockCustomerRegistrationDatabasePortMockRecorder struct {
	mock *MockCustomerRegistrationDatabasePort
}

// NewMockCustomerRegistrationDatabasePort creates a new mock instance.
func NewMockCustomerRegistrationDatabasePort(ctrl *gomock.Controller) *MockCustomerRegistrationDatabasePort {
	mock := &MockCustomerRegistrationDatabasePort{ctrl: ctrl}
	mock.recorder = &MockCustomerRegistrationDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerRegistrationDatabasePort) EXPECT() *MockCustomerRegistrationDatabasePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCustomerRegistrationDatabasePort) Create(data model.CustomerRegistrationInput) (model.CustomerRegistration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", data)
	ret0, _ := ret[0].(model.CustomerRegistration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCustomerRegistrationDatabasePortMockRecorder) Create(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCustomerRegistrationDatabasePort)(nil).Create), data)
}

// Delete mocks base method.
func (m *MockCustomerRegistrationDatabasePort) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCustomerRegistrationDatabasePortMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCustomerRegistrationDatabasePort)(nil).Delete), id)
}

// FindByFilter mocks base method.
func (m *MockCustomerRegistrationDatabasePort) FindByFilter(filter model.CustomerRegistrationFilter) ([]model.CustomerRegistration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFilter", filter)
	ret0, _ := ret[0].([]model.CustomerRegistration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFilter indicates an expected call of FindByFilter.
func (mr *MockCustomerRegistrationDatabasePortMockRecorder) FindByFilter(filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFilter", reflect.TypeOf((*MockCustomerRegistrationDatabasePort)(nil).FindByFilter), filter)
}

// FindByID mocks base method.
func (m *MockCustomerRegistrationDatabasePort) FindByID(id string) (model.CustomerRegistration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(model.CustomerRegistration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockCustomerRegistrationDatabasePortMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCustomerRegistrationDatabasePort)(nil).FindByID), id)
}

// Update mocks base method.
func (m *MockCustomerRegistrationDatabasePort) Update(id string, data model.CustomerRegistrationInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCustomerRegistrationDatabasePortMockRecorder) Update(id, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCustomerRegistrationDatabasePort)(nil).Update), id, data)
}
