// Code generated by MockGen. DO NOT EDIT.
// Source: internet_package.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "mikrops/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockInternetPackageDatabasePort is a mock of InternetPackageDatabasePort interface.
type MockInternetPackageDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockInternetPackageDatabasePortMockRecorder
}

// MockInternetPackageDatabasePortMockRecorder is the mock recorder for MockInternetPackageDatabasePort.
type MockInternetPackageDatabasePortMockRecorder struct {
	mock *MockInternetPackageDatabasePort
}

// NewMockInternetPackageDatabasePort creates a new mock instance.
func NewMockInternetPackageDatabasePort(ctrl *gomock.Controller) *MockInternetPackageDatabasePort {
	mock := &MockInternetPackageDatabasePort{ctrl: ctrl}
	mock.recorder = &MockInternetPackageDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInternetPackageDatabasePort) EXPECT() *MockInternetPackageDatabasePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockInternetPackageDatabasePort) Create(data model.InternetPackageInput) (model.InternetPackage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", data)
	ret0, _ := ret[0].(model.InternetPackage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockInternetPackageDatabasePortMockRecorder) Create(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInternetPackageDatabasePort)(nil).Create), data)
}

// Delete mocks base method.
func (m *MockInternetPackageDatabasePort) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockInternetPackageDatabasePortMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInternetPackageDatabasePort)(nil).Delete), id)
}

// FindByFilter mocks base method.
func (m *MockInternetPackageDatabasePort) FindByFilter(filter model.InternetPackageFilter) ([]model.InternetPackage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFilter", filter)
	ret0, _ := ret[0].([]model.InternetPackage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFilter indicates an expected call of FindByFilter.
func (mr *MockInternetPackageDatabasePortMockRecorder) FindByFilter(filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFilter", reflect.TypeOf((*MockInternetPackageDatabasePort)(nil).FindByFilter), filter)
}

// FindByID mocks base method.
func (m *MockInternetPackageDatabasePort) FindByID(id string) (model.InternetPackage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(model.InternetPackage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockInternetPackageDatabasePortMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockInternetPackageDatabasePort)(nil).FindByID), id)
}

// Update mocks base method.
func (m *MockInternetPackageDatabasePort) Update(id string, data model.InternetPackageInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockInternetPackageDatabasePortMockRecorder) Update(id, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockInternetPackageDatabasePort)(nil).Update), id, data)
}
