// Code generated by MockGen. DO NOT EDIT.
// Source: internal/port/outbound/customer.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "go-template/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCustomerDatabasePort is a mock of CustomerDatabasePort interface.
type MockCustomerDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerDatabasePortMockRecorder
}

// MockCustomerDatabasePortMockRecorder is the mock recorder for MockCustomerDatabasePort.
type MockCustomerDatabasePortMockRecorder struct {
	mock *MockCustomerDatabasePort
}

// NewMockCustomerDatabasePort creates a new mock instance.
func NewMockCustomerDatabasePort(ctrl *gomock.Controller) *MockCustomerDatabasePort {
	mock := &MockCustomerDatabasePort{ctrl: ctrl}
	mock.recorder = &MockCustomerDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerDatabasePort) EXPECT() *MockCustomerDatabasePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCustomerDatabasePort) Create(customer *model.Customer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", customer)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCustomerDatabasePortMockRecorder) Create(customer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCustomerDatabasePort)(nil).Create), customer)
}

// Delete mocks base method.
func (m *MockCustomerDatabasePort) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCustomerDatabasePortMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCustomerDatabasePort)(nil).Delete), id)
}

// Find mocks base method.
func (m *MockCustomerDatabasePort) Find(filter model.CustomerFilter) ([]model.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", filter)
	ret0, _ := ret[0].([]model.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockCustomerDatabasePortMockRecorder) Find(filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockCustomerDatabasePort)(nil).Find), filter)
}

// FindAll mocks base method.
func (m *MockCustomerDatabasePort) FindAll() ([]model.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]model.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockCustomerDatabasePortMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockCustomerDatabasePort)(nil).FindAll))
}

// FindByCustomerCode mocks base method.
func (m *MockCustomerDatabasePort) FindByCustomerCode(code string) (*model.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCustomerCode", code)
	ret0, _ := ret[0].(*model.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCustomerCode indicates an expected call of FindByCustomerCode.
func (mr *MockCustomerDatabasePortMockRecorder) FindByCustomerCode(code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCustomerCode", reflect.TypeOf((*MockCustomerDatabasePort)(nil).FindByCustomerCode), code)
}

// FindByID mocks base method.
func (m *MockCustomerDatabasePort) FindByID(id string) (*model.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*model.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockCustomerDatabasePortMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCustomerDatabasePort)(nil).FindByID), id)
}

// FindByPppSecretName mocks base method.
func (m *MockCustomerDatabasePort) FindByPppSecretName(name string) (*model.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByPppSecretName", name)
	ret0, _ := ret[0].(*model.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByPppSecretName indicates an expected call of FindByPppSecretName.
func (mr *MockCustomerDatabasePortMockRecorder) FindByPppSecretName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByPppSecretName", reflect.TypeOf((*MockCustomerDatabasePort)(nil).FindByPppSecretName), name)
}

// FindByProfileID mocks base method.
func (m *MockCustomerDatabasePort) FindByProfileID(profileID string) ([]model.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProfileID", profileID)
	ret0, _ := ret[0].([]model.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByProfileID indicates an expected call of FindByProfileID.
func (mr *MockCustomerDatabasePortMockRecorder) FindByProfileID(profileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProfileID", reflect.TypeOf((*MockCustomerDatabasePort)(nil).FindByProfileID), profileID)
}

// FindByRouterID mocks base method.
func (m *MockCustomerDatabasePort) FindByRouterID(routerID string) ([]model.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRouterID", routerID)
	ret0, _ := ret[0].([]model.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRouterID indicates an expected call of FindByRouterID.
func (mr *MockCustomerDatabasePortMockRecorder) FindByRouterID(routerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRouterID", reflect.TypeOf((*MockCustomerDatabasePort)(nil).FindByRouterID), routerID)
}

// FindExpired mocks base method.
func (m *MockCustomerDatabasePort) FindExpired() ([]model.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindExpired")
	ret0, _ := ret[0].([]model.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindExpired indicates an expected call of FindExpired.
func (mr *MockCustomerDatabasePortMockRecorder) FindExpired() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindExpired", reflect.TypeOf((*MockCustomerDatabasePort)(nil).FindExpired))
}

// FindExpiringSoon mocks base method.
func (m *MockCustomerDatabasePort) FindExpiringSoon(days int) ([]model.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindExpiringSoon", days)
	ret0, _ := ret[0].([]model.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindExpiringSoon indicates an expected call of FindExpiringSoon.
func (mr *MockCustomerDatabasePortMockRecorder) FindExpiringSoon(days interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindExpiringSoon", reflect.TypeOf((*MockCustomerDatabasePort)(nil).FindExpiringSoon), days)
}

// Update mocks base method.
func (m *MockCustomerDatabasePort) Update(customer *model.Customer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", customer)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCustomerDatabasePortMockRecorder) Update(customer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCustomerDatabasePort)(nil).Update), customer)
}
