// Code generated by MockGen. DO NOT EDIT.
// Source: payment.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	context "context"
	model "go-template/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPaymentDatabasePort is a mock of PaymentDatabasePort interface.
type MockPaymentDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentDatabasePortMockRecorder
}

// MockPaymentDatabasePortMockRecorder is the mock recorder for MockPaymentDatabasePort.
type MockPaymentDatabasePortMockRecorder struct {
	mock *MockPaymentDatabasePort
}

// NewMockPaymentDatabasePort creates a new mock instance.
func NewMockPaymentDatabasePort(ctrl *gomock.Controller) *MockPaymentDatabasePort {
	mock := &MockPaymentDatabasePort{ctrl: ctrl}
	mock.recorder = &MockPaymentDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentDatabasePort) EXPECT() *MockPaymentDatabasePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPaymentDatabasePort) Create(ctx context.Context, payment *model.Payment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, payment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPaymentDatabasePortMockRecorder) Create(ctx, payment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPaymentDatabasePort)(nil).Create), ctx, payment)
}

// CreateAllocation mocks base method.
func (m *MockPaymentDatabasePort) CreateAllocation(ctx context.Context, allocation *model.PaymentAllocation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAllocation", ctx, allocation)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAllocation indicates an expected call of CreateAllocation.
func (mr *MockPaymentDatabasePortMockRecorder) CreateAllocation(ctx, allocation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAllocation", reflect.TypeOf((*MockPaymentDatabasePort)(nil).CreateAllocation), ctx, allocation)
}

// Delete mocks base method.
func (m *MockPaymentDatabasePort) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPaymentDatabasePortMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPaymentDatabasePort)(nil).Delete), ctx, id)
}

// FindAll mocks base method.
func (m *MockPaymentDatabasePort) FindAll(ctx context.Context, filter *model.PaymentFilter) ([]model.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, filter)
	ret0, _ := ret[0].([]model.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockPaymentDatabasePortMockRecorder) FindAll(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockPaymentDatabasePort)(nil).FindAll), ctx, filter)
}

// FindByID mocks base method.
func (m *MockPaymentDatabasePort) FindByID(ctx context.Context, id string) (*model.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*model.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPaymentDatabasePortMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPaymentDatabasePort)(nil).FindByID), ctx, id)
}

// FindByNumber mocks base method.
func (m *MockPaymentDatabasePort) FindByNumber(ctx context.Context, number string) (*model.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByNumber", ctx, number)
	ret0, _ := ret[0].(*model.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByNumber indicates an expected call of FindByNumber.
func (mr *MockPaymentDatabasePortMockRecorder) FindByNumber(ctx, number interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByNumber", reflect.TypeOf((*MockPaymentDatabasePort)(nil).FindByNumber), ctx, number)
}

// GetLastPaymentNumber mocks base method.
func (m *MockPaymentDatabasePort) GetLastPaymentNumber(ctx context.Context, year, month int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastPaymentNumber", ctx, year, month)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastPaymentNumber indicates an expected call of GetLastPaymentNumber.
func (mr *MockPaymentDatabasePortMockRecorder) GetLastPaymentNumber(ctx, year, month interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastPaymentNumber", reflect.TypeOf((*MockPaymentDatabasePort)(nil).GetLastPaymentNumber), ctx, year, month)
}

// Update mocks base method.
func (m *MockPaymentDatabasePort) Update(ctx context.Context, payment *model.Payment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, payment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPaymentDatabasePortMockRecorder) Update(ctx, payment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPaymentDatabasePort)(nil).Update), ctx, payment)
}
