// Code generated by MockGen. DO NOT EDIT.
// Source: activity_log.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "mikrops/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockActivityLogDatabasePort is a mock of ActivityLogDatabasePort interface.
type MockActivityLogDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockActivityLogDatabasePortMockRecorder
}

// MockActivityLogDatabasePortMockRecorder is the mock recorder for MockActivityLogDatabasePort.
type MockActivityLogDatabasePortMockRecorder struct {
	mock *MockActivityLogDatabasePort
}

// NewMockActivityLogDatabasePort creates a new mock instance.
func NewMockActivityLogDatabasePort(ctrl *gomock.Controller) *MockActivityLogDatabasePort {
	mock := &MockActivityLogDatabasePort{ctrl: ctrl}
	mock.recorder = &MockActivityLogDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActivityLogDatabasePort) EXPECT() *MockActivityLogDatabasePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockActivityLogDatabasePort) Create(data model.ActivityLogInput) (model.ActivityLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", data)
	ret0, _ := ret[0].(model.ActivityLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockActivityLogDatabasePortMockRecorder) Create(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockActivityLogDatabasePort)(nil).Create), data)
}

// FindByFilter mocks base method.
func (m *MockActivityLogDatabasePort) FindByFilter(filter model.ActivityLogFilter) ([]model.ActivityLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFilter", filter)
	ret0, _ := ret[0].([]model.ActivityLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFilter indicates an expected call of FindByFilter.
func (mr *MockActivityLogDatabasePortMockRecorder) FindByFilter(filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFilter", reflect.TypeOf((*MockActivityLogDatabasePort)(nil).FindByFilter), filter)
}

// FindByID mocks base method.
func (m *MockActivityLogDatabasePort) FindByID(id string) (model.ActivityLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(model.ActivityLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockActivityLogDatabasePortMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockActivityLogDatabasePort)(nil).FindByID), id)
}
