// Code generated by MockGen. DO NOT EDIT.
// Source: registry_workflow.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	inbound_port "go-template/internal/port/inbound"
	outbound_port "go-template/internal/port/outbound"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockWorkflowPort is a mock of WorkflowPort interface.
type MockWorkflowPort struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowPortMockRecorder
}

// MockWorkflowPortMockRecorder is the mock recorder for MockWorkflowPort.
type MockWorkflowPortMockRecorder struct {
	mock *MockWorkflowPort
}

// NewMockWorkflowPort creates a new mock instance.
func NewMockWorkflowPort(ctrl *gomock.Controller) *MockWorkflowPort {
	mock := &MockWorkflowPort{ctrl: ctrl}
	mock.recorder = &MockWorkflowPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkflowPort) EXPECT() *MockWorkflowPortMockRecorder {
	return m.recorder
}

// Billing mocks base method.
func (m *MockWorkflowPort) Billing() inbound_port.BillingWorkflowPort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Billing")
	ret0, _ := ret[0].(inbound_port.BillingWorkflowPort)
	return ret0
}

// Billing indicates an expected call of Billing.
func (mr *MockWorkflowPortMockRecorder) Billing() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Billing", reflect.TypeOf((*MockWorkflowPort)(nil).Billing))
}

// Client mocks base method.
func (m *MockWorkflowPort) Client() outbound_port.ClientWorkflowPort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Client")
	ret0, _ := ret[0].(outbound_port.ClientWorkflowPort)
	return ret0
}

// Client indicates an expected call of Client.
func (mr *MockWorkflowPortMockRecorder) Client() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Client", reflect.TypeOf((*MockWorkflowPort)(nil).Client))
}

// Isolation mocks base method.
func (m *MockWorkflowPort) Isolation() inbound_port.IsolationWorkflowPort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Isolation")
	ret0, _ := ret[0].(inbound_port.IsolationWorkflowPort)
	return ret0
}

// Isolation indicates an expected call of Isolation.
func (mr *MockWorkflowPortMockRecorder) Isolation() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Isolation", reflect.TypeOf((*MockWorkflowPort)(nil).Isolation))
}
