// Code generated by MockGen. DO NOT EDIT.
// Source: mikrotik_sync.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "go-template/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMikrotikSyncMessagePort is a mock of MikrotikSyncMessagePort interface.
type MockMikrotikSyncMessagePort struct {
	ctrl     *gomock.Controller
	recorder *MockMikrotikSyncMessagePortMockRecorder
}

// MockMikrotikSyncMessagePortMockRecorder is the mock recorder for MockMikrotikSyncMessagePort.
type MockMikrotikSyncMessagePortMockRecorder struct {
	mock *MockMikrotikSyncMessagePort
}

// NewMockMikrotikSyncMessagePort creates a new mock instance.
func NewMockMikrotikSyncMessagePort(ctrl *gomock.Controller) *MockMikrotikSyncMessagePort {
	mock := &MockMikrotikSyncMessagePort{ctrl: ctrl}
	mock.recorder = &MockMikrotikSyncMessagePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMikrotikSyncMessagePort) EXPECT() *MockMikrotikSyncMessagePortMockRecorder {
	return m.recorder
}

// PublishSyncMessage mocks base method.
func (m *MockMikrotikSyncMessagePort) PublishSyncMessage(message model.MikrotikSyncMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishSyncMessage", message)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishSyncMessage indicates an expected call of PublishSyncMessage.
func (mr *MockMikrotikSyncMessagePortMockRecorder) PublishSyncMessage(message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishSyncMessage", reflect.TypeOf((*MockMikrotikSyncMessagePort)(nil).PublishSyncMessage), message)
}
