// Code generated by MockGen. DO NOT EDIT.
// Source: tenant.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "mikrops/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTenantDatabasePort is a mock of TenantDatabasePort interface.
type MockTenantDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockTenantDatabasePortMockRecorder
}

// MockTenantDatabasePortMockRecorder is the mock recorder for MockTenantDatabasePort.
type MockTenantDatabasePortMockRecorder struct {
	mock *MockTenantDatabasePort
}

// NewMockTenantDatabasePort creates a new mock instance.
func NewMockTenantDatabasePort(ctrl *gomock.Controller) *MockTenantDatabasePort {
	mock := &MockTenantDatabasePort{ctrl: ctrl}
	mock.recorder = &MockTenantDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantDatabasePort) EXPECT() *MockTenantDatabasePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTenantDatabasePort) Create(data model.TenantInput) (model.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", data)
	ret0, _ := ret[0].(model.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTenantDatabasePortMockRecorder) Create(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTenantDatabasePort)(nil).Create), data)
}

// Delete mocks base method.
func (m *MockTenantDatabasePort) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTenantDatabasePortMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTenantDatabasePort)(nil).Delete), id)
}

// FindByFilter mocks base method.
func (m *MockTenantDatabasePort) FindByFilter(filter model.TenantFilter) ([]model.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFilter", filter)
	ret0, _ := ret[0].([]model.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFilter indicates an expected call of FindByFilter.
func (mr *MockTenantDatabasePortMockRecorder) FindByFilter(filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFilter", reflect.TypeOf((*MockTenantDatabasePort)(nil).FindByFilter), filter)
}

// FindByID mocks base method.
func (m *MockTenantDatabasePort) FindByID(id string) (model.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(model.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockTenantDatabasePortMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockTenantDatabasePort)(nil).FindByID), id)
}

// Update mocks base method.
func (m *MockTenantDatabasePort) Update(id string, data model.TenantInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTenantDatabasePortMockRecorder) Update(id, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTenantDatabasePort)(nil).Update), id, data)
}
