// Code generated by MockGen. DO NOT EDIT.
// Source: internal/port/outbound/invoice.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "go-template/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockInvoiceDatabasePort is a mock of InvoiceDatabasePort interface.
type MockInvoiceDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockInvoiceDatabasePortMockRecorder
}

// MockInvoiceDatabasePortMockRecorder is the mock recorder for MockInvoiceDatabasePort.
type MockInvoiceDatabasePortMockRecorder struct {
	mock *MockInvoiceDatabasePort
}

// NewMockInvoiceDatabasePort creates a new mock instance.
func NewMockInvoiceDatabasePort(ctrl *gomock.Controller) *MockInvoiceDatabasePort {
	mock := &MockInvoiceDatabasePort{ctrl: ctrl}
	mock.recorder = &MockInvoiceDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvoiceDatabasePort) EXPECT() *MockInvoiceDatabasePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockInvoiceDatabasePort) Create(invoice *model.Invoice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", invoice)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockInvoiceDatabasePortMockRecorder) Create(invoice interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInvoiceDatabasePort)(nil).Create), invoice)
}

// Delete mocks base method.
func (m *MockInvoiceDatabasePort) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockInvoiceDatabasePortMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInvoiceDatabasePort)(nil).Delete), id)
}

// Find mocks base method.
func (m *MockInvoiceDatabasePort) Find(filter model.InvoiceFilter) ([]model.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", filter)
	ret0, _ := ret[0].([]model.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockInvoiceDatabasePortMockRecorder) Find(filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockInvoiceDatabasePort)(nil).Find), filter)
}

// FindAll mocks base method.
func (m *MockInvoiceDatabasePort) FindAll() ([]model.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]model.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockInvoiceDatabasePortMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockInvoiceDatabasePort)(nil).FindAll))
}

// FindByBillingPeriod mocks base method.
func (m *MockInvoiceDatabasePort) FindByBillingPeriod(year, month int) ([]model.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByBillingPeriod", year, month)
	ret0, _ := ret[0].([]model.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByBillingPeriod indicates an expected call of FindByBillingPeriod.
func (mr *MockInvoiceDatabasePortMockRecorder) FindByBillingPeriod(year, month interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByBillingPeriod", reflect.TypeOf((*MockInvoiceDatabasePort)(nil).FindByBillingPeriod), year, month)
}

// FindByCustomerID mocks base method.
func (m *MockInvoiceDatabasePort) FindByCustomerID(customerID string) ([]model.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCustomerID", customerID)
	ret0, _ := ret[0].([]model.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCustomerID indicates an expected call of FindByCustomerID.
func (mr *MockInvoiceDatabasePortMockRecorder) FindByCustomerID(customerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCustomerID", reflect.TypeOf((*MockInvoiceDatabasePort)(nil).FindByCustomerID), customerID)
}

// FindByID mocks base method.
func (m *MockInvoiceDatabasePort) FindByID(id string) (*model.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*model.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockInvoiceDatabasePortMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockInvoiceDatabasePort)(nil).FindByID), id)
}

// FindByInvoiceNumber mocks base method.
func (m *MockInvoiceDatabasePort) FindByInvoiceNumber(number string) (*model.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByInvoiceNumber", number)
	ret0, _ := ret[0].(*model.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByInvoiceNumber indicates an expected call of FindByInvoiceNumber.
func (mr *MockInvoiceDatabasePortMockRecorder) FindByInvoiceNumber(number interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByInvoiceNumber", reflect.TypeOf((*MockInvoiceDatabasePort)(nil).FindByInvoiceNumber), number)
}

// FindOverdue mocks base method.
func (m *MockInvoiceDatabasePort) FindOverdue() ([]model.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOverdue")
	ret0, _ := ret[0].([]model.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOverdue indicates an expected call of FindOverdue.
func (mr *MockInvoiceDatabasePortMockRecorder) FindOverdue() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOverdue", reflect.TypeOf((*MockInvoiceDatabasePort)(nil).FindOverdue))
}

// Update mocks base method.
func (m *MockInvoiceDatabasePort) Update(invoice *model.Invoice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", invoice)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockInvoiceDatabasePortMockRecorder) Update(invoice interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockInvoiceDatabasePort)(nil).Update), invoice)
}

// MockInvoiceItemDatabasePort is a mock of InvoiceItemDatabasePort interface.
type MockInvoiceItemDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockInvoiceItemDatabasePortMockRecorder
}

// MockInvoiceItemDatabasePortMockRecorder is the mock recorder for MockInvoiceItemDatabasePort.
type MockInvoiceItemDatabasePortMockRecorder struct {
	mock *MockInvoiceItemDatabasePort
}

// NewMockInvoiceItemDatabasePort creates a new mock instance.
func NewMockInvoiceItemDatabasePort(ctrl *gomock.Controller) *MockInvoiceItemDatabasePort {
	mock := &MockInvoiceItemDatabasePort{ctrl: ctrl}
	mock.recorder = &MockInvoiceItemDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvoiceItemDatabasePort) EXPECT() *MockInvoiceItemDatabasePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockInvoiceItemDatabasePort) Create(item *model.InvoiceItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockInvoiceItemDatabasePortMockRecorder) Create(item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInvoiceItemDatabasePort)(nil).Create), item)
}

// Delete mocks base method.
func (m *MockInvoiceItemDatabasePort) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockInvoiceItemDatabasePortMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInvoiceItemDatabasePort)(nil).Delete), id)
}

// FindByID mocks base method.
func (m *MockInvoiceItemDatabasePort) FindByID(id string) (*model.InvoiceItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*model.InvoiceItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockInvoiceItemDatabasePortMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockInvoiceItemDatabasePort)(nil).FindByID), id)
}

// FindByInvoiceID mocks base method.
func (m *MockInvoiceItemDatabasePort) FindByInvoiceID(invoiceID string) ([]model.InvoiceItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByInvoiceID", invoiceID)
	ret0, _ := ret[0].([]model.InvoiceItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByInvoiceID indicates an expected call of FindByInvoiceID.
func (mr *MockInvoiceItemDatabasePortMockRecorder) FindByInvoiceID(invoiceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByInvoiceID", reflect.TypeOf((*MockInvoiceItemDatabasePort)(nil).FindByInvoiceID), invoiceID)
}

// Update mocks base method.
func (m *MockInvoiceItemDatabasePort) Update(item *model.InvoiceItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockInvoiceItemDatabasePortMockRecorder) Update(item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockInvoiceItemDatabasePort)(nil).Update), item)
}
