// Code generated by MockGen. DO NOT EDIT.
// Source: registry_database.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	outbound_port "mikrops/internal/port/outbound"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDatabasePort is a mock of DatabasePort interface.
type MockDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockDatabasePortMockRecorder
}

// MockDatabasePortMockRecorder is the mock recorder for MockDatabasePort.
type MockDatabasePortMockRecorder struct {
	mock *MockDatabasePort
}

// NewMockDatabasePort creates a new mock instance.
func NewMockDatabasePort(ctrl *gomock.Controller) *MockDatabasePort {
	mock := &MockDatabasePort{ctrl: ctrl}
	mock.recorder = &MockDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabasePort) EXPECT() *MockDatabasePortMockRecorder {
	return m.recorder
}

// Client mocks base method.
func (m *MockDatabasePort) Client() outbound_port.ClientDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Client")
	ret0, _ := ret[0].(outbound_port.ClientDatabasePort)
	return ret0
}

// Client indicates an expected call of Client.
func (mr *MockDatabasePortMockRecorder) Client() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Client", reflect.TypeOf((*MockDatabasePort)(nil).Client))
}

// Customer mocks base method.
func (m *MockDatabasePort) Customer() outbound_port.CustomerDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Customer")
	ret0, _ := ret[0].(outbound_port.CustomerDatabasePort)
	return ret0
}

// Customer indicates an expected call of Customer.
func (mr *MockDatabasePortMockRecorder) Customer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Customer", reflect.TypeOf((*MockDatabasePort)(nil).Customer))
}

// DoInTransaction mocks base method.
func (m *MockDatabasePort) DoInTransaction(txFunc outbound_port.InTransaction) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoInTransaction", txFunc)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoInTransaction indicates an expected call of DoInTransaction.
func (mr *MockDatabasePortMockRecorder) DoInTransaction(txFunc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoInTransaction", reflect.TypeOf((*MockDatabasePort)(nil).DoInTransaction), txFunc)
}

// InternetPackage mocks base method.
func (m *MockDatabasePort) InternetPackage() outbound_port.InternetPackageDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternetPackage")
	ret0, _ := ret[0].(outbound_port.InternetPackageDatabasePort)
	return ret0
}

// InternetPackage indicates an expected call of InternetPackage.
func (mr *MockDatabasePortMockRecorder) InternetPackage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternetPackage", reflect.TypeOf((*MockDatabasePort)(nil).InternetPackage))
}

// Invoice mocks base method.
func (m *MockDatabasePort) Invoice() outbound_port.InvoiceDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Invoice")
	ret0, _ := ret[0].(outbound_port.InvoiceDatabasePort)
	return ret0
}

// Invoice indicates an expected call of Invoice.
func (mr *MockDatabasePortMockRecorder) Invoice() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invoice", reflect.TypeOf((*MockDatabasePort)(nil).Invoice))
}

// Nas mocks base method.
func (m *MockDatabasePort) Nas() outbound_port.NasDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Nas")
	ret0, _ := ret[0].(outbound_port.NasDatabasePort)
	return ret0
}

// Nas indicates an expected call of Nas.
func (mr *MockDatabasePortMockRecorder) Nas() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Nas", reflect.TypeOf((*MockDatabasePort)(nil).Nas))
}

// Payment mocks base method.
func (m *MockDatabasePort) Payment() outbound_port.PaymentDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Payment")
	ret0, _ := ret[0].(outbound_port.PaymentDatabasePort)
	return ret0
}

// Payment indicates an expected call of Payment.
func (mr *MockDatabasePortMockRecorder) Payment() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Payment", reflect.TypeOf((*MockDatabasePort)(nil).Payment))
}

// PaymentMethod mocks base method.
func (m *MockDatabasePort) PaymentMethod() outbound_port.PaymentMethodDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PaymentMethod")
	ret0, _ := ret[0].(outbound_port.PaymentMethodDatabasePort)
	return ret0
}

// PaymentMethod indicates an expected call of PaymentMethod.
func (mr *MockDatabasePortMockRecorder) PaymentMethod() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PaymentMethod", reflect.TypeOf((*MockDatabasePort)(nil).PaymentMethod))
}

// Permission mocks base method.
func (m *MockDatabasePort) Permission() outbound_port.PermissionDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Permission")
	ret0, _ := ret[0].(outbound_port.PermissionDatabasePort)
	return ret0
}

// Permission indicates an expected call of Permission.
func (mr *MockDatabasePortMockRecorder) Permission() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Permission", reflect.TypeOf((*MockDatabasePort)(nil).Permission))
}

// Role mocks base method.
func (m *MockDatabasePort) Role() outbound_port.RoleDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Role")
	ret0, _ := ret[0].(outbound_port.RoleDatabasePort)
	return ret0
}

// Role indicates an expected call of Role.
func (mr *MockDatabasePortMockRecorder) Role() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Role", reflect.TypeOf((*MockDatabasePort)(nil).Role))
}

// Staff mocks base method.
func (m *MockDatabasePort) Staff() outbound_port.StaffDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Staff")
	ret0, _ := ret[0].(outbound_port.StaffDatabasePort)
	return ret0
}

// Staff indicates an expected call of Staff.
func (mr *MockDatabasePortMockRecorder) Staff() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Staff", reflect.TypeOf((*MockDatabasePort)(nil).Staff))
}

// Subscription mocks base method.
func (m *MockDatabasePort) Subscription() outbound_port.SubscriptionDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscription")
	ret0, _ := ret[0].(outbound_port.SubscriptionDatabasePort)
	return ret0
}

// Subscription indicates an expected call of Subscription.
func (mr *MockDatabasePortMockRecorder) Subscription() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscription", reflect.TypeOf((*MockDatabasePort)(nil).Subscription))
}

// Tenant mocks base method.
func (m *MockDatabasePort) Tenant() outbound_port.TenantDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tenant")
	ret0, _ := ret[0].(outbound_port.TenantDatabasePort)
	return ret0
}

// Tenant indicates an expected call of Tenant.
func (mr *MockDatabasePortMockRecorder) Tenant() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tenant", reflect.TypeOf((*MockDatabasePort)(nil).Tenant))
}

// TenantSetting mocks base method.
func (m *MockDatabasePort) TenantSetting() outbound_port.TenantSettingDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TenantSetting")
	ret0, _ := ret[0].(outbound_port.TenantSettingDatabasePort)
	return ret0
}

// TenantSetting indicates an expected call of TenantSetting.
func (mr *MockDatabasePortMockRecorder) TenantSetting() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TenantSetting", reflect.TypeOf((*MockDatabasePort)(nil).TenantSetting))
}

// CustomerRegistration mocks base method.
func (m *MockDatabasePort) CustomerRegistration() outbound_port.CustomerRegistrationDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CustomerRegistration")
	ret0, _ := ret[0].(outbound_port.CustomerRegistrationDatabasePort)
	return ret0
}

// CustomerRegistration indicates an expected call of CustomerRegistration.
func (mr *MockDatabasePortMockRecorder) CustomerRegistration() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CustomerRegistration", reflect.TypeOf((*MockDatabasePort)(nil).CustomerRegistration))
}

// PppoeAccount mocks base method.
func (m *MockDatabasePort) PppoeAccount() outbound_port.PppoeAccountDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PppoeAccount")
	ret0, _ := ret[0].(outbound_port.PppoeAccountDatabasePort)
	return ret0
}

// PppoeAccount indicates an expected call of PppoeAccount.
func (mr *MockDatabasePortMockRecorder) PppoeAccount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PppoeAccount", reflect.TypeOf((*MockDatabasePort)(nil).PppoeAccount))
}

// ActivityLog mocks base method.
func (m *MockDatabasePort) ActivityLog() outbound_port.ActivityLogDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivityLog")
	ret0, _ := ret[0].(outbound_port.ActivityLogDatabasePort)
	return ret0
}

// ActivityLog indicates an expected call of ActivityLog.
func (mr *MockDatabasePortMockRecorder) ActivityLog() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivityLog", reflect.TypeOf((*MockDatabasePort)(nil).ActivityLog))
}

// MikrotikSyncLog mocks base method.
func (m *MockDatabasePort) MikrotikSyncLog() outbound_port.MikrotikSyncLogDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MikrotikSyncLog")
	ret0, _ := ret[0].(outbound_port.MikrotikSyncLogDatabasePort)
	return ret0
}

// MikrotikSyncLog indicates an expected call of MikrotikSyncLog.
func (mr *MockDatabasePortMockRecorder) MikrotikSyncLog() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MikrotikSyncLog", reflect.TypeOf((*MockDatabasePort)(nil).MikrotikSyncLog))
}

// WithTenantScope mocks base method.
func (m *MockDatabasePort) WithTenantScope(tenantID string) outbound_port.DatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTenantScope", tenantID)
	ret0, _ := ret[0].(outbound_port.DatabasePort)
	return ret0
}

// WithTenantScope indicates an expected call of WithTenantScope.
func (mr *MockDatabasePortMockRecorder) WithTenantScope(tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTenantScope", reflect.TypeOf((*MockDatabasePort)(nil).WithTenantScope), tenantID)
}
