// Code generated by MockGen. DO NOT EDIT.
// Source: internal/port/outbound/cash.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "go-template/internal/model"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockCashCategoryDatabasePort is a mock of CashCategoryDatabasePort interface.
type MockCashCategoryDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockCashCategoryDatabasePortMockRecorder
}

// MockCashCategoryDatabasePortMockRecorder is the mock recorder for MockCashCategoryDatabasePort.
type MockCashCategoryDatabasePortMockRecorder struct {
	mock *MockCashCategoryDatabasePort
}

// NewMockCashCategoryDatabasePort creates a new mock instance.
func NewMockCashCategoryDatabasePort(ctrl *gomock.Controller) *MockCashCategoryDatabasePort {
	mock := &MockCashCategoryDatabasePort{ctrl: ctrl}
	mock.recorder = &MockCashCategoryDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCashCategoryDatabasePort) EXPECT() *MockCashCategoryDatabasePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCashCategoryDatabasePort) Create(category *model.CashCategory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", category)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCashCategoryDatabasePortMockRecorder) Create(category interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCashCategoryDatabasePort)(nil).Create), category)
}

// Delete mocks base method.
func (m *MockCashCategoryDatabasePort) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCashCategoryDatabasePortMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCashCategoryDatabasePort)(nil).Delete), id)
}

// Find mocks base method.
func (m *MockCashCategoryDatabasePort) Find(filter model.CashCategoryFilter) ([]model.CashCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", filter)
	ret0, _ := ret[0].([]model.CashCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockCashCategoryDatabasePortMockRecorder) Find(filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockCashCategoryDatabasePort)(nil).Find), filter)
}

// FindAll mocks base method.
func (m *MockCashCategoryDatabasePort) FindAll() ([]model.CashCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]model.CashCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockCashCategoryDatabasePortMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockCashCategoryDatabasePort)(nil).FindAll))
}

// FindByCode mocks base method.
func (m *MockCashCategoryDatabasePort) FindByCode(code string) (*model.CashCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCode", code)
	ret0, _ := ret[0].(*model.CashCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCode indicates an expected call of FindByCode.
func (mr *MockCashCategoryDatabasePortMockRecorder) FindByCode(code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCode", reflect.TypeOf((*MockCashCategoryDatabasePort)(nil).FindByCode), code)
}

// FindByID mocks base method.
func (m *MockCashCategoryDatabasePort) FindByID(id string) (*model.CashCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*model.CashCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockCashCategoryDatabasePortMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCashCategoryDatabasePort)(nil).FindByID), id)
}

// FindByType mocks base method.
func (m *MockCashCategoryDatabasePort) FindByType(cashType string) ([]model.CashCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByType", cashType)
	ret0, _ := ret[0].([]model.CashCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByType indicates an expected call of FindByType.
func (mr *MockCashCategoryDatabasePortMockRecorder) FindByType(cashType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByType", reflect.TypeOf((*MockCashCategoryDatabasePort)(nil).FindByType), cashType)
}

// Update mocks base method.
func (m *MockCashCategoryDatabasePort) Update(category *model.CashCategory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", category)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCashCategoryDatabasePortMockRecorder) Update(category interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCashCategoryDatabasePort)(nil).Update), category)
}

// MockCashTransactionDatabasePort is a mock of CashTransactionDatabasePort interface.
type MockCashTransactionDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockCashTransactionDatabasePortMockRecorder
}

// MockCashTransactionDatabasePortMockRecorder is the mock recorder for MockCashTransactionDatabasePort.
type MockCashTransactionDatabasePortMockRecorder struct {
	mock *MockCashTransactionDatabasePort
}

// NewMockCashTransactionDatabasePort creates a new mock instance.
func NewMockCashTransactionDatabasePort(ctrl *gomock.Controller) *MockCashTransactionDatabasePort {
	mock := &MockCashTransactionDatabasePort{ctrl: ctrl}
	mock.recorder = &MockCashTransactionDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCashTransactionDatabasePort) EXPECT() *MockCashTransactionDatabasePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCashTransactionDatabasePort) Create(transaction *model.CashTransaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", transaction)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCashTransactionDatabasePortMockRecorder) Create(transaction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCashTransactionDatabasePort)(nil).Create), transaction)
}

// Delete mocks base method.
func (m *MockCashTransactionDatabasePort) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCashTransactionDatabasePortMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCashTransactionDatabasePort)(nil).Delete), id)
}

// Find mocks base method.
func (m *MockCashTransactionDatabasePort) Find(filter model.CashTransactionFilter) ([]model.CashTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", filter)
	ret0, _ := ret[0].([]model.CashTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockCashTransactionDatabasePortMockRecorder) Find(filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockCashTransactionDatabasePort)(nil).Find), filter)
}

// FindAll mocks base method.
func (m *MockCashTransactionDatabasePort) FindAll() ([]model.CashTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]model.CashTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockCashTransactionDatabasePortMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockCashTransactionDatabasePort)(nil).FindAll))
}

// FindByID mocks base method.
func (m *MockCashTransactionDatabasePort) FindByID(id string) (*model.CashTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*model.CashTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockCashTransactionDatabasePortMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCashTransactionDatabasePort)(nil).FindByID), id)
}

// FindByNumber mocks base method.
func (m *MockCashTransactionDatabasePort) FindByNumber(number string) (*model.CashTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByNumber", number)
	ret0, _ := ret[0].(*model.CashTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByNumber indicates an expected call of FindByNumber.
func (mr *MockCashTransactionDatabasePortMockRecorder) FindByNumber(number interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByNumber", reflect.TypeOf((*MockCashTransactionDatabasePort)(nil).FindByNumber), number)
}

// FindByReference mocks base method.
func (m *MockCashTransactionDatabasePort) FindByReference(refType, refID string) ([]model.CashTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByReference", refType, refID)
	ret0, _ := ret[0].([]model.CashTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByReference indicates an expected call of FindByReference.
func (mr *MockCashTransactionDatabasePortMockRecorder) FindByReference(refType, refID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByReference", reflect.TypeOf((*MockCashTransactionDatabasePort)(nil).FindByReference), refType, refID)
}

// GetExpenseTotal mocks base method.
func (m *MockCashTransactionDatabasePort) GetExpenseTotal(startDate, endDate time.Time) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExpenseTotal", startDate, endDate)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExpenseTotal indicates an expected call of GetExpenseTotal.
func (mr *MockCashTransactionDatabasePortMockRecorder) GetExpenseTotal(startDate, endDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExpenseTotal", reflect.TypeOf((*MockCashTransactionDatabasePort)(nil).GetExpenseTotal), startDate, endDate)
}

// GetIncomeTotal mocks base method.
func (m *MockCashTransactionDatabasePort) GetIncomeTotal(startDate, endDate time.Time) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncomeTotal", startDate, endDate)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncomeTotal indicates an expected call of GetIncomeTotal.
func (mr *MockCashTransactionDatabasePortMockRecorder) GetIncomeTotal(startDate, endDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncomeTotal", reflect.TypeOf((*MockCashTransactionDatabasePort)(nil).GetIncomeTotal), startDate, endDate)
}

// Update mocks base method.
func (m *MockCashTransactionDatabasePort) Update(transaction *model.CashTransaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", transaction)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCashTransactionDatabasePortMockRecorder) Update(transaction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCashTransactionDatabasePort)(nil).Update), transaction)
}
