// Code generated by MockGen. DO NOT EDIT.
// Source: invoice.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "mikrops/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockInvoiceDatabasePort is a mock of InvoiceDatabasePort interface.
type MockInvoiceDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockInvoiceDatabasePortMockRecorder
}

// MockInvoiceDatabasePortMockRecorder is the mock recorder for MockInvoiceDatabasePort.
type MockInvoiceDatabasePortMockRecorder struct {
	mock *MockInvoiceDatabasePort
}

// NewMockInvoiceDatabasePort creates a new mock instance.
func NewMockInvoiceDatabasePort(ctrl *gomock.Controller) *MockInvoiceDatabasePort {
	mock := &MockInvoiceDatabasePort{ctrl: ctrl}
	mock.recorder = &MockInvoiceDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvoiceDatabasePort) EXPECT() *MockInvoiceDatabasePortMockRecorder {
	return m.recorder
}

// BulkCreate mocks base method.
func (m *MockInvoiceDatabasePort) BulkCreate(datas []model.InvoiceInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkCreate", datas)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkCreate indicates an expected call of BulkCreate.
func (mr *MockInvoiceDatabasePortMockRecorder) BulkCreate(datas interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkCreate", reflect.TypeOf((*MockInvoiceDatabasePort)(nil).BulkCreate), datas)
}

// Create mocks base method.
func (m *MockInvoiceDatabasePort) Create(data model.InvoiceInput) (model.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", data)
	ret0, _ := ret[0].(model.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockInvoiceDatabasePortMockRecorder) Create(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInvoiceDatabasePort)(nil).Create), data)
}

// Delete mocks base method.
func (m *MockInvoiceDatabasePort) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockInvoiceDatabasePortMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInvoiceDatabasePort)(nil).Delete), id)
}

// FindByFilter mocks base method.
func (m *MockInvoiceDatabasePort) FindByFilter(filter model.InvoiceFilter) ([]model.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFilter", filter)
	ret0, _ := ret[0].([]model.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFilter indicates an expected call of FindByFilter.
func (mr *MockInvoiceDatabasePortMockRecorder) FindByFilter(filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFilter", reflect.TypeOf((*MockInvoiceDatabasePort)(nil).FindByFilter), filter)
}

// FindByID mocks base method.
func (m *MockInvoiceDatabasePort) FindByID(id string) (model.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(model.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockInvoiceDatabasePortMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockInvoiceDatabasePort)(nil).FindByID), id)
}

// Update mocks base method.
func (m *MockInvoiceDatabasePort) Update(id string, data model.InvoiceInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockInvoiceDatabasePortMockRecorder) Update(id, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockInvoiceDatabasePort)(nil).Update), id, data)
}
