// Code generated by MockGen. DO NOT EDIT.
// Source: internal/port/outbound/bandwidth_profile.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "go-template/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBandwidthProfileDatabasePort is a mock of BandwidthProfileDatabasePort interface.
type MockBandwidthProfileDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockBandwidthProfileDatabasePortMockRecorder
}

// MockBandwidthProfileDatabasePortMockRecorder is the mock recorder for MockBandwidthProfileDatabasePort.
type MockBandwidthProfileDatabasePortMockRecorder struct {
	mock *MockBandwidthProfileDatabasePort
}

// NewMockBandwidthProfileDatabasePort creates a new mock instance.
func NewMockBandwidthProfileDatabasePort(ctrl *gomock.Controller) *MockBandwidthProfileDatabasePort {
	mock := &MockBandwidthProfileDatabasePort{ctrl: ctrl}
	mock.recorder = &MockBandwidthProfileDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBandwidthProfileDatabasePort) EXPECT() *MockBandwidthProfileDatabasePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBandwidthProfileDatabasePort) Create(profile *model.BandwidthProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBandwidthProfileDatabasePortMockRecorder) Create(profile interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBandwidthProfileDatabasePort)(nil).Create), profile)
}

// Delete mocks base method.
func (m *MockBandwidthProfileDatabasePort) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBandwidthProfileDatabasePortMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBandwidthProfileDatabasePort)(nil).Delete), id)
}

// Find mocks base method.
func (m *MockBandwidthProfileDatabasePort) Find(filter model.BandwidthProfileFilter) ([]model.BandwidthProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", filter)
	ret0, _ := ret[0].([]model.BandwidthProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockBandwidthProfileDatabasePortMockRecorder) Find(filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockBandwidthProfileDatabasePort)(nil).Find), filter)
}

// FindAll mocks base method.
func (m *MockBandwidthProfileDatabasePort) FindAll() ([]model.BandwidthProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]model.BandwidthProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockBandwidthProfileDatabasePortMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockBandwidthProfileDatabasePort)(nil).FindAll))
}

// FindByCategory mocks base method.
func (m *MockBandwidthProfileDatabasePort) FindByCategory(category string) ([]model.BandwidthProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCategory", category)
	ret0, _ := ret[0].([]model.BandwidthProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCategory indicates an expected call of FindByCategory.
func (mr *MockBandwidthProfileDatabasePortMockRecorder) FindByCategory(category interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCategory", reflect.TypeOf((*MockBandwidthProfileDatabasePort)(nil).FindByCategory), category)
}

// FindByID mocks base method.
func (m *MockBandwidthProfileDatabasePort) FindByID(id string) (*model.BandwidthProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*model.BandwidthProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockBandwidthProfileDatabasePortMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockBandwidthProfileDatabasePort)(nil).FindByID), id)
}

// FindByProfileCode mocks base method.
func (m *MockBandwidthProfileDatabasePort) FindByProfileCode(code string) (*model.BandwidthProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProfileCode", code)
	ret0, _ := ret[0].(*model.BandwidthProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByProfileCode indicates an expected call of FindByProfileCode.
func (mr *MockBandwidthProfileDatabasePortMockRecorder) FindByProfileCode(code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProfileCode", reflect.TypeOf((*MockBandwidthProfileDatabasePort)(nil).FindByProfileCode), code)
}

// Update mocks base method.
func (m *MockBandwidthProfileDatabasePort) Update(profile *model.BandwidthProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockBandwidthProfileDatabasePortMockRecorder) Update(profile interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBandwidthProfileDatabasePort)(nil).Update), profile)
}
