// Code generated by MockGen. DO NOT EDIT.
// Source: go-template/internal/port/outbound (interfaces: SubscriptionDatabasePort)

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "go-template/internal/model"
)

// MockSubscriptionDatabasePort is a mock of SubscriptionDatabasePort interface.
type MockSubscriptionDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionDatabasePortMockRecorder
}

// MockSubscriptionDatabasePortMockRecorder is the mock recorder for MockSubscriptionDatabasePort.
type MockSubscriptionDatabasePortMockRecorder struct {
	mock *MockSubscriptionDatabasePort
}

// NewMockSubscriptionDatabasePort creates a new mock instance.
func NewMockSubscriptionDatabasePort(ctrl *gomock.Controller) *MockSubscriptionDatabasePort {
	mock := &MockSubscriptionDatabasePort{ctrl: ctrl}
	mock.recorder = &MockSubscriptionDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionDatabasePort) EXPECT() *MockSubscriptionDatabasePortMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockSubscriptionDatabasePort) FindByID(ctx context.Context, id string) (*model.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*model.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockSubscriptionDatabasePortMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockSubscriptionDatabasePort)(nil).FindByID), ctx, id)
}

// FindByCustomerID mocks base method.
func (m *MockSubscriptionDatabasePort) FindByCustomerID(ctx context.Context, customerID string) ([]model.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCustomerID", ctx, customerID)
	ret0, _ := ret[0].([]model.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCustomerID indicates an expected call of FindByCustomerID.
func (mr *MockSubscriptionDatabasePortMockRecorder) FindByCustomerID(ctx, customerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCustomerID", reflect.TypeOf((*MockSubscriptionDatabasePort)(nil).FindByCustomerID), ctx, customerID)
}

// FindActiveByCustomerID mocks base method.
func (m *MockSubscriptionDatabasePort) FindActiveByCustomerID(ctx context.Context, customerID string) ([]model.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveByCustomerID", ctx, customerID)
	ret0, _ := ret[0].([]model.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveByCustomerID indicates an expected call of FindActiveByCustomerID.
func (mr *MockSubscriptionDatabasePortMockRecorder) FindActiveByCustomerID(ctx, customerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveByCustomerID", reflect.TypeOf((*MockSubscriptionDatabasePort)(nil).FindActiveByCustomerID), ctx, customerID)
}

// Update mocks base method.
func (m *MockSubscriptionDatabasePort) Update(ctx context.Context, subscription *model.Subscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, subscription)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSubscriptionDatabasePortMockRecorder) Update(ctx, subscription interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSubscriptionDatabasePort)(nil).Update), ctx, subscription)
}
