// Code generated by MockGen. DO NOT EDIT.
// Source: subscription.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "mikrops/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSubscriptionDatabasePort is a mock of SubscriptionDatabasePort interface.
type MockSubscriptionDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionDatabasePortMockRecorder
}

// MockSubscriptionDatabasePortMockRecorder is the mock recorder for MockSubscriptionDatabasePort.
type MockSubscriptionDatabasePortMockRecorder struct {
	mock *MockSubscriptionDatabasePort
}

// NewMockSubscriptionDatabasePort creates a new mock instance.
func NewMockSubscriptionDatabasePort(ctrl *gomock.Controller) *MockSubscriptionDatabasePort {
	mock := &MockSubscriptionDatabasePort{ctrl: ctrl}
	mock.recorder = &MockSubscriptionDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionDatabasePort) EXPECT() *MockSubscriptionDatabasePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSubscriptionDatabasePort) Create(data model.SubscriptionInput) (model.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", data)
	ret0, _ := ret[0].(model.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSubscriptionDatabasePortMockRecorder) Create(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSubscriptionDatabasePort)(nil).Create), data)
}

// FindByFilter mocks base method.
func (m *MockSubscriptionDatabasePort) FindByFilter(filter model.SubscriptionFilter) ([]model.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFilter", filter)
	ret0, _ := ret[0].([]model.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFilter indicates an expected call of FindByFilter.
func (mr *MockSubscriptionDatabasePortMockRecorder) FindByFilter(filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFilter", reflect.TypeOf((*MockSubscriptionDatabasePort)(nil).FindByFilter), filter)
}

// FindByID mocks base method.
func (m *MockSubscriptionDatabasePort) FindByID(id string) (model.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(model.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockSubscriptionDatabasePortMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockSubscriptionDatabasePort)(nil).FindByID), id)
}

// FindExpiring mocks base method.
func (m *MockSubscriptionDatabasePort) FindExpiring(daysBeforeExpiry int, tenantID string) ([]model.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindExpiring", daysBeforeExpiry, tenantID)
	ret0, _ := ret[0].([]model.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindExpiring indicates an expected call of FindExpiring.
func (mr *MockSubscriptionDatabasePortMockRecorder) FindExpiring(daysBeforeExpiry, tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindExpiring", reflect.TypeOf((*MockSubscriptionDatabasePort)(nil).FindExpiring), daysBeforeExpiry, tenantID)
}

// Update mocks base method.
func (m *MockSubscriptionDatabasePort) Update(id string, data model.SubscriptionInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSubscriptionDatabasePortMockRecorder) Update(id, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSubscriptionDatabasePort)(nil).Update), id, data)
}
