// Code generated by MockGen. DO NOT EDIT.
// Source: internal/port/outbound/payment.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "go-template/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPaymentDatabasePort is a mock of PaymentDatabasePort interface.
type MockPaymentDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentDatabasePortMockRecorder
}

// MockPaymentDatabasePortMockRecorder is the mock recorder for MockPaymentDatabasePort.
type MockPaymentDatabasePortMockRecorder struct {
	mock *MockPaymentDatabasePort
}

// NewMockPaymentDatabasePort creates a new mock instance.
func NewMockPaymentDatabasePort(ctrl *gomock.Controller) *MockPaymentDatabasePort {
	mock := &MockPaymentDatabasePort{ctrl: ctrl}
	mock.recorder = &MockPaymentDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentDatabasePort) EXPECT() *MockPaymentDatabasePortMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockPaymentDatabasePort) Count(filter model.PaymentFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockPaymentDatabasePortMockRecorder) Count(filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockPaymentDatabasePort)(nil).Count), filter)
}

// Create mocks base method.
func (m *MockPaymentDatabasePort) Create(payment *model.Payment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", payment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPaymentDatabasePortMockRecorder) Create(payment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPaymentDatabasePort)(nil).Create), payment)
}

// Delete mocks base method.
func (m *MockPaymentDatabasePort) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPaymentDatabasePortMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPaymentDatabasePort)(nil).Delete), id)
}

// Find mocks base method.
func (m *MockPaymentDatabasePort) Find(filter model.PaymentFilter) ([]model.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", filter)
	ret0, _ := ret[0].([]model.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockPaymentDatabasePortMockRecorder) Find(filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockPaymentDatabasePort)(nil).Find), filter)
}

// FindByCustomerID mocks base method.
func (m *MockPaymentDatabasePort) FindByCustomerID(customerID string) ([]model.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCustomerID", customerID)
	ret0, _ := ret[0].([]model.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCustomerID indicates an expected call of FindByCustomerID.
func (mr *MockPaymentDatabasePortMockRecorder) FindByCustomerID(customerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCustomerID", reflect.TypeOf((*MockPaymentDatabasePort)(nil).FindByCustomerID), customerID)
}

// FindByID mocks base method.
func (m *MockPaymentDatabasePort) FindByID(id string) (*model.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*model.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPaymentDatabasePortMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPaymentDatabasePort)(nil).FindByID), id)
}

// FindByInvoiceID mocks base method.
func (m *MockPaymentDatabasePort) FindByInvoiceID(invoiceID string) ([]model.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByInvoiceID", invoiceID)
	ret0, _ := ret[0].([]model.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByInvoiceID indicates an expected call of FindByInvoiceID.
func (mr *MockPaymentDatabasePortMockRecorder) FindByInvoiceID(invoiceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByInvoiceID", reflect.TypeOf((*MockPaymentDatabasePort)(nil).FindByInvoiceID), invoiceID)
}

// FindByXenditExternalID mocks base method.
func (m *MockPaymentDatabasePort) FindByXenditExternalID(externalID string) (*model.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByXenditExternalID", externalID)
	ret0, _ := ret[0].(*model.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByXenditExternalID indicates an expected call of FindByXenditExternalID.
func (mr *MockPaymentDatabasePortMockRecorder) FindByXenditExternalID(externalID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByXenditExternalID", reflect.TypeOf((*MockPaymentDatabasePort)(nil).FindByXenditExternalID), externalID)
}

// Update mocks base method.
func (m *MockPaymentDatabasePort) Update(payment *model.Payment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", payment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPaymentDatabasePortMockRecorder) Update(payment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPaymentDatabasePort)(nil).Update), payment)
}

// MockPaymentAllocationDatabasePort is a mock of PaymentAllocationDatabasePort interface.
type MockPaymentAllocationDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentAllocationDatabasePortMockRecorder
}

// MockPaymentAllocationDatabasePortMockRecorder is the mock recorder for MockPaymentAllocationDatabasePort.
type MockPaymentAllocationDatabasePortMockRecorder struct {
	mock *MockPaymentAllocationDatabasePort
}

// NewMockPaymentAllocationDatabasePort creates a new mock instance.
func NewMockPaymentAllocationDatabasePort(ctrl *gomock.Controller) *MockPaymentAllocationDatabasePort {
	mock := &MockPaymentAllocationDatabasePort{ctrl: ctrl}
	mock.recorder = &MockPaymentAllocationDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentAllocationDatabasePort) EXPECT() *MockPaymentAllocationDatabasePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPaymentAllocationDatabasePort) Create(allocation *model.PaymentAllocation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", allocation)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPaymentAllocationDatabasePortMockRecorder) Create(allocation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPaymentAllocationDatabasePort)(nil).Create), allocation)
}

// Delete mocks base method.
func (m *MockPaymentAllocationDatabasePort) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPaymentAllocationDatabasePortMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPaymentAllocationDatabasePort)(nil).Delete), id)
}

// FindByID mocks base method.
func (m *MockPaymentAllocationDatabasePort) FindByID(id string) (*model.PaymentAllocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*model.PaymentAllocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPaymentAllocationDatabasePortMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPaymentAllocationDatabasePort)(nil).FindByID), id)
}

// FindByInvoiceID mocks base method.
func (m *MockPaymentAllocationDatabasePort) FindByInvoiceID(invoiceID string) ([]model.PaymentAllocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByInvoiceID", invoiceID)
	ret0, _ := ret[0].([]model.PaymentAllocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByInvoiceID indicates an expected call of FindByInvoiceID.
func (mr *MockPaymentAllocationDatabasePortMockRecorder) FindByInvoiceID(invoiceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByInvoiceID", reflect.TypeOf((*MockPaymentAllocationDatabasePort)(nil).FindByInvoiceID), invoiceID)
}

// FindByPaymentID mocks base method.
func (m *MockPaymentAllocationDatabasePort) FindByPaymentID(paymentID string) ([]model.PaymentAllocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByPaymentID", paymentID)
	ret0, _ := ret[0].([]model.PaymentAllocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByPaymentID indicates an expected call of FindByPaymentID.
func (mr *MockPaymentAllocationDatabasePortMockRecorder) FindByPaymentID(paymentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByPaymentID", reflect.TypeOf((*MockPaymentAllocationDatabasePort)(nil).FindByPaymentID), paymentID)
}
