// Code generated by MockGen. DO NOT EDIT.
// Source: mikrotik.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "mikrops/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMikrotikPort is a mock of MikrotikPort interface.
type MockMikrotikPort struct {
	ctrl     *gomock.Controller
	recorder *MockMikrotikPortMockRecorder
}

// MockMikrotikPortMockRecorder is the mock recorder for MockMikrotikPort.
type MockMikrotikPortMockRecorder struct {
	mock *MockMikrotikPort
}

// NewMockMikrotikPort creates a new mock instance.
func NewMockMikrotikPort(ctrl *gomock.Controller) *MockMikrotikPort {
	mock := &MockMikrotikPort{ctrl: ctrl}
	mock.recorder = &MockMikrotikPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMikrotikPort) EXPECT() *MockMikrotikPortMockRecorder {
	return m.recorder
}

// CreateHotspotUser mocks base method.
func (m *MockMikrotikPort) CreateHotspotUser(host string, restPort int, username, password string, useSSL bool, data model.MikrotikHotspotUserInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateHotspotUser", host, restPort, username, password, useSSL, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateHotspotUser indicates an expected call of CreateHotspotUser.
func (mr *MockMikrotikPortMockRecorder) CreateHotspotUser(host, restPort, username, password, useSSL, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateHotspotUser", reflect.TypeOf((*MockMikrotikPort)(nil).CreateHotspotUser), host, restPort, username, password, useSSL, data)
}

// CreatePPPoEProfile mocks base method.
func (m *MockMikrotikPort) CreatePPPoEProfile(host string, restPort int, username, password string, useSSL bool, data model.MikrotikProfileInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePPPoEProfile", host, restPort, username, password, useSSL, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePPPoEProfile indicates an expected call of CreatePPPoEProfile.
func (mr *MockMikrotikPortMockRecorder) CreatePPPoEProfile(host, restPort, username, password, useSSL, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePPPoEProfile", reflect.TypeOf((*MockMikrotikPort)(nil).CreatePPPoEProfile), host, restPort, username, password, useSSL, data)
}

// CreatePPPoESecret mocks base method.
func (m *MockMikrotikPort) CreatePPPoESecret(host string, restPort int, username, password string, useSSL bool, data model.MikrotikPPPoESecretInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePPPoESecret", host, restPort, username, password, useSSL, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePPPoESecret indicates an expected call of CreatePPPoESecret.
func (mr *MockMikrotikPortMockRecorder) CreatePPPoESecret(host, restPort, username, password, useSSL, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePPPoESecret", reflect.TypeOf((*MockMikrotikPort)(nil).CreatePPPoESecret), host, restPort, username, password, useSSL, data)
}

// CreateSimpleQueue mocks base method.
func (m *MockMikrotikPort) CreateSimpleQueue(host string, restPort int, username, password string, useSSL bool, data model.MikrotikSimpleQueueInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSimpleQueue", host, restPort, username, password, useSSL, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSimpleQueue indicates an expected call of CreateSimpleQueue.
func (mr *MockMikrotikPortMockRecorder) CreateSimpleQueue(host, restPort, username, password, useSSL, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSimpleQueue", reflect.TypeOf((*MockMikrotikPort)(nil).CreateSimpleQueue), host, restPort, username, password, useSSL, data)
}

// DeleteHotspotUser mocks base method.
func (m *MockMikrotikPort) DeleteHotspotUser(host string, restPort int, username, password string, useSSL bool, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteHotspotUser", host, restPort, username, password, useSSL, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteHotspotUser indicates an expected call of DeleteHotspotUser.
func (mr *MockMikrotikPortMockRecorder) DeleteHotspotUser(host, restPort, username, password, useSSL, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteHotspotUser", reflect.TypeOf((*MockMikrotikPort)(nil).DeleteHotspotUser), host, restPort, username, password, useSSL, id)
}

// DeletePPPoESecret mocks base method.
func (m *MockMikrotikPort) DeletePPPoESecret(host string, restPort int, username, password string, useSSL bool, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePPPoESecret", host, restPort, username, password, useSSL, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePPPoESecret indicates an expected call of DeletePPPoESecret.
func (mr *MockMikrotikPortMockRecorder) DeletePPPoESecret(host, restPort, username, password, useSSL, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePPPoESecret", reflect.TypeOf((*MockMikrotikPort)(nil).DeletePPPoESecret), host, restPort, username, password, useSSL, id)
}

// DeleteSimpleQueue mocks base method.
func (m *MockMikrotikPort) DeleteSimpleQueue(host string, restPort int, username, password string, useSSL bool, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSimpleQueue", host, restPort, username, password, useSSL, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSimpleQueue indicates an expected call of DeleteSimpleQueue.
func (mr *MockMikrotikPortMockRecorder) DeleteSimpleQueue(host, restPort, username, password, useSSL, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSimpleQueue", reflect.TypeOf((*MockMikrotikPort)(nil).DeleteSimpleQueue), host, restPort, username, password, useSSL, id)
}

// DisablePPPoESecret mocks base method.
func (m *MockMikrotikPort) DisablePPPoESecret(host string, restPort int, username, password string, useSSL bool, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisablePPPoESecret", host, restPort, username, password, useSSL, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisablePPPoESecret indicates an expected call of DisablePPPoESecret.
func (mr *MockMikrotikPortMockRecorder) DisablePPPoESecret(host, restPort, username, password, useSSL, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisablePPPoESecret", reflect.TypeOf((*MockMikrotikPort)(nil).DisablePPPoESecret), host, restPort, username, password, useSSL, id)
}

// EnablePPPoESecret mocks base method.
func (m *MockMikrotikPort) EnablePPPoESecret(host string, restPort int, username, password string, useSSL bool, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnablePPPoESecret", host, restPort, username, password, useSSL, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnablePPPoESecret indicates an expected call of EnablePPPoESecret.
func (mr *MockMikrotikPortMockRecorder) EnablePPPoESecret(host, restPort, username, password, useSSL, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnablePPPoESecret", reflect.TypeOf((*MockMikrotikPort)(nil).EnablePPPoESecret), host, restPort, username, password, useSSL, id)
}

// GetActiveConnections mocks base method.
func (m *MockMikrotikPort) GetActiveConnections(host string, port int, username, password string, useSSL bool) ([]model.MikrotikConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveConnections", host, port, username, password, useSSL)
	ret0, _ := ret[0].([]model.MikrotikConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveConnections indicates an expected call of GetActiveConnections.
func (mr *MockMikrotikPortMockRecorder) GetActiveConnections(host, port, username, password, useSSL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveConnections", reflect.TypeOf((*MockMikrotikPort)(nil).GetActiveConnections), host, port, username, password, useSSL)
}

// GetIdentity mocks base method.
func (m *MockMikrotikPort) GetIdentity(host string, port int, username, password string, useSSL bool) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdentity", host, port, username, password, useSSL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIdentity indicates an expected call of GetIdentity.
func (mr *MockMikrotikPortMockRecorder) GetIdentity(host, port, username, password, useSSL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdentity", reflect.TypeOf((*MockMikrotikPort)(nil).GetIdentity), host, port, username, password, useSSL)
}

// GetInterfaceTraffic mocks base method.
func (m *MockMikrotikPort) GetInterfaceTraffic(host string, port int, username, password string, useSSL bool, interfaceName string) (model.MikrotikTraffic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInterfaceTraffic", host, port, username, password, useSSL, interfaceName)
	ret0, _ := ret[0].(model.MikrotikTraffic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInterfaceTraffic indicates an expected call of GetInterfaceTraffic.
func (mr *MockMikrotikPortMockRecorder) GetInterfaceTraffic(host, port, username, password, useSSL, interfaceName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInterfaceTraffic", reflect.TypeOf((*MockMikrotikPort)(nil).GetInterfaceTraffic), host, port, username, password, useSSL, interfaceName)
}

// ListHotspotUsers mocks base method.
func (m *MockMikrotikPort) ListHotspotUsers(host string, restPort int, username, password string, useSSL bool) ([]model.MikrotikHotspotUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListHotspotUsers", host, restPort, username, password, useSSL)
	ret0, _ := ret[0].([]model.MikrotikHotspotUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListHotspotUsers indicates an expected call of ListHotspotUsers.
func (mr *MockMikrotikPortMockRecorder) ListHotspotUsers(host, restPort, username, password, useSSL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHotspotUsers", reflect.TypeOf((*MockMikrotikPort)(nil).ListHotspotUsers), host, restPort, username, password, useSSL)
}

// ListPPPoEProfiles mocks base method.
func (m *MockMikrotikPort) ListPPPoEProfiles(host string, restPort int, username, password string, useSSL bool) ([]model.MikrotikProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPPPoEProfiles", host, restPort, username, password, useSSL)
	ret0, _ := ret[0].([]model.MikrotikProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPPPoEProfiles indicates an expected call of ListPPPoEProfiles.
func (mr *MockMikrotikPortMockRecorder) ListPPPoEProfiles(host, restPort, username, password, useSSL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPPPoEProfiles", reflect.TypeOf((*MockMikrotikPort)(nil).ListPPPoEProfiles), host, restPort, username, password, useSSL)
}

// ListPPPoESecrets mocks base method.
func (m *MockMikrotikPort) ListPPPoESecrets(host string, restPort int, username, password string, useSSL bool) ([]model.MikrotikPPPoESecret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPPPoESecrets", host, restPort, username, password, useSSL)
	ret0, _ := ret[0].([]model.MikrotikPPPoESecret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPPPoESecrets indicates an expected call of ListPPPoESecrets.
func (mr *MockMikrotikPortMockRecorder) ListPPPoESecrets(host, restPort, username, password, useSSL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPPPoESecrets", reflect.TypeOf((*MockMikrotikPort)(nil).ListPPPoESecrets), host, restPort, username, password, useSSL)
}

// ListSimpleQueues mocks base method.
func (m *MockMikrotikPort) ListSimpleQueues(host string, restPort int, username, password string, useSSL bool) ([]model.MikrotikSimpleQueue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSimpleQueues", host, restPort, username, password, useSSL)
	ret0, _ := ret[0].([]model.MikrotikSimpleQueue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSimpleQueues indicates an expected call of ListSimpleQueues.
func (mr *MockMikrotikPortMockRecorder) ListSimpleQueues(host, restPort, username, password, useSSL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSimpleQueues", reflect.TypeOf((*MockMikrotikPort)(nil).ListSimpleQueues), host, restPort, username, password, useSSL)
}

// MonitorBandwidth mocks base method.
func (m *MockMikrotikPort) MonitorBandwidth(host string, port int, username, password string, useSSL bool, target string) (model.MikrotikBandwidth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MonitorBandwidth", host, port, username, password, useSSL, target)
	ret0, _ := ret[0].(model.MikrotikBandwidth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MonitorBandwidth indicates an expected call of MonitorBandwidth.
func (mr *MockMikrotikPortMockRecorder) MonitorBandwidth(host, port, username, password, useSSL, target interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MonitorBandwidth", reflect.TypeOf((*MockMikrotikPort)(nil).MonitorBandwidth), host, port, username, password, useSSL, target)
}

// TestConnection mocks base method.
func (m *MockMikrotikPort) TestConnection(host string, port int, username, password string, useSSL bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestConnection", host, port, username, password, useSSL)
	ret0, _ := ret[0].(error)
	return ret0
}

// TestConnection indicates an expected call of TestConnection.
func (mr *MockMikrotikPortMockRecorder) TestConnection(host, port, username, password, useSSL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestConnection", reflect.TypeOf((*MockMikrotikPort)(nil).TestConnection), host, port, username, password, useSSL)
}

// UpdateHotspotUser mocks base method.
func (m *MockMikrotikPort) UpdateHotspotUser(host string, restPort int, username, password string, useSSL bool, id string, data model.MikrotikHotspotUserInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHotspotUser", host, restPort, username, password, useSSL, id, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateHotspotUser indicates an expected call of UpdateHotspotUser.
func (mr *MockMikrotikPortMockRecorder) UpdateHotspotUser(host, restPort, username, password, useSSL, id, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHotspotUser", reflect.TypeOf((*MockMikrotikPort)(nil).UpdateHotspotUser), host, restPort, username, password, useSSL, id, data)
}

// UpdatePPPoESecret mocks base method.
func (m *MockMikrotikPort) UpdatePPPoESecret(host string, restPort int, username, password string, useSSL bool, id string, data model.MikrotikPPPoESecretInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePPPoESecret", host, restPort, username, password, useSSL, id, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePPPoESecret indicates an expected call of UpdatePPPoESecret.
func (mr *MockMikrotikPortMockRecorder) UpdatePPPoESecret(host, restPort, username, password, useSSL, id, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePPPoESecret", reflect.TypeOf((*MockMikrotikPort)(nil).UpdatePPPoESecret), host, restPort, username, password, useSSL, id, data)
}

// UpdateSimpleQueue mocks base method.
func (m *MockMikrotikPort) UpdateSimpleQueue(host string, restPort int, username, password string, useSSL bool, id string, data model.MikrotikSimpleQueueInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSimpleQueue", host, restPort, username, password, useSSL, id, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSimpleQueue indicates an expected call of UpdateSimpleQueue.
func (mr *MockMikrotikPortMockRecorder) UpdateSimpleQueue(host, restPort, username, password, useSSL, id, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSimpleQueue", reflect.TypeOf((*MockMikrotikPort)(nil).UpdateSimpleQueue), host, restPort, username, password, useSSL, id, data)
}
