// Code generated by MockGen. DO NOT EDIT.
// Source: registry_http.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	outbound_port "mikrops/internal/port/outbound"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockHttpPort is a mock of HttpPort interface.
type MockHttpPort struct {
	ctrl     *gomock.Controller
	recorder *MockHttpPortMockRecorder
}

// MockHttpPortMockRecorder is the mock recorder for MockHttpPort.
type MockHttpPortMockRecorder struct {
	mock *MockHttpPort
}

// NewMockHttpPort creates a new mock instance.
func NewMockHttpPort(ctrl *gomock.Controller) *MockHttpPort {
	mock := &MockHttpPort{ctrl: ctrl}
	mock.recorder = &MockHttpPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHttpPort) EXPECT() *MockHttpPortMockRecorder {
	return m.recorder
}

// Mikrotik mocks base method.
func (m *MockHttpPort) Mikrotik() outbound_port.MikrotikPort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mikrotik")
	ret0, _ := ret[0].(outbound_port.MikrotikPort)
	return ret0
}

// Mikrotik indicates an expected call of Mikrotik.
func (mr *MockHttpPortMockRecorder) Mikrotik() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mikrotik", reflect.TypeOf((*MockHttpPort)(nil).Mikrotik))
}

// Whatsapp mocks base method.
func (m *MockHttpPort) Whatsapp() outbound_port.WhatsappPort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Whatsapp")
	ret0, _ := ret[0].(outbound_port.WhatsappPort)
	return ret0
}

// Whatsapp indicates an expected call of Whatsapp.
func (mr *MockHttpPortMockRecorder) Whatsapp() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Whatsapp", reflect.TypeOf((*MockHttpPort)(nil).Whatsapp))
}
