// Code generated by MockGen. DO NOT EDIT.
// Source: internal/port/outbound/activity_log.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "go-template/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockActivityLogDatabasePort is a mock of ActivityLogDatabasePort interface.
type MockActivityLogDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockActivityLogDatabasePortMockRecorder
}

// MockActivityLogDatabasePortMockRecorder is the mock recorder for MockActivityLogDatabasePort.
type MockActivityLogDatabasePortMockRecorder struct {
	mock *MockActivityLogDatabasePort
}

// NewMockActivityLogDatabasePort creates a new mock instance.
func NewMockActivityLogDatabasePort(ctrl *gomock.Controller) *MockActivityLogDatabasePort {
	mock := &MockActivityLogDatabasePort{ctrl: ctrl}
	mock.recorder = &MockActivityLogDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActivityLogDatabasePort) EXPECT() *MockActivityLogDatabasePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockActivityLogDatabasePort) Create(log *model.ActivityLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", log)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockActivityLogDatabasePortMockRecorder) Create(log interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockActivityLogDatabasePort)(nil).Create), log)
}

// Find mocks base method.
func (m *MockActivityLogDatabasePort) Find(filter model.ActivityLogFilter) ([]model.ActivityLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", filter)
	ret0, _ := ret[0].([]model.ActivityLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockActivityLogDatabasePortMockRecorder) Find(filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockActivityLogDatabasePort)(nil).Find), filter)
}

// FindAll mocks base method.
func (m *MockActivityLogDatabasePort) FindAll() ([]model.ActivityLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]model.ActivityLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockActivityLogDatabasePortMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockActivityLogDatabasePort)(nil).FindAll))
}

// FindByAction mocks base method.
func (m *MockActivityLogDatabasePort) FindByAction(action string) ([]model.ActivityLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByAction", action)
	ret0, _ := ret[0].([]model.ActivityLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByAction indicates an expected call of FindByAction.
func (mr *MockActivityLogDatabasePortMockRecorder) FindByAction(action interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByAction", reflect.TypeOf((*MockActivityLogDatabasePort)(nil).FindByAction), action)
}

// FindByEntity mocks base method.
func (m *MockActivityLogDatabasePort) FindByEntity(entityType, entityID string) ([]model.ActivityLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEntity", entityType, entityID)
	ret0, _ := ret[0].([]model.ActivityLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEntity indicates an expected call of FindByEntity.
func (mr *MockActivityLogDatabasePortMockRecorder) FindByEntity(entityType, entityID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEntity", reflect.TypeOf((*MockActivityLogDatabasePort)(nil).FindByEntity), entityType, entityID)
}

// FindByID mocks base method.
func (m *MockActivityLogDatabasePort) FindByID(id string) (*model.ActivityLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*model.ActivityLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockActivityLogDatabasePortMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockActivityLogDatabasePort)(nil).FindByID), id)
}

// FindByUserID mocks base method.
func (m *MockActivityLogDatabasePort) FindByUserID(userID string) ([]model.ActivityLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", userID)
	ret0, _ := ret[0].([]model.ActivityLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockActivityLogDatabasePortMockRecorder) FindByUserID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockActivityLogDatabasePort)(nil).FindByUserID), userID)
}
