// Code generated by MockGen. DO NOT EDIT.
// Source: payment_method.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "mikrops/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPaymentMethodDatabasePort is a mock of PaymentMethodDatabasePort interface.
type MockPaymentMethodDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentMethodDatabasePortMockRecorder
}

// MockPaymentMethodDatabasePortMockRecorder is the mock recorder for MockPaymentMethodDatabasePort.
type MockPaymentMethodDatabasePortMockRecorder struct {
	mock *MockPaymentMethodDatabasePort
}

// NewMockPaymentMethodDatabasePort creates a new mock instance.
func NewMockPaymentMethodDatabasePort(ctrl *gomock.Controller) *MockPaymentMethodDatabasePort {
	mock := &MockPaymentMethodDatabasePort{ctrl: ctrl}
	mock.recorder = &MockPaymentMethodDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentMethodDatabasePort) EXPECT() *MockPaymentMethodDatabasePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPaymentMethodDatabasePort) Create(data model.PaymentMethodInput) (model.PaymentMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", data)
	ret0, _ := ret[0].(model.PaymentMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPaymentMethodDatabasePortMockRecorder) Create(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPaymentMethodDatabasePort)(nil).Create), data)
}

// Delete mocks base method.
func (m *MockPaymentMethodDatabasePort) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPaymentMethodDatabasePortMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPaymentMethodDatabasePort)(nil).Delete), id)
}

// FindByFilter mocks base method.
func (m *MockPaymentMethodDatabasePort) FindByFilter(filter model.PaymentMethodFilter) ([]model.PaymentMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFilter", filter)
	ret0, _ := ret[0].([]model.PaymentMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFilter indicates an expected call of FindByFilter.
func (mr *MockPaymentMethodDatabasePortMockRecorder) FindByFilter(filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFilter", reflect.TypeOf((*MockPaymentMethodDatabasePort)(nil).FindByFilter), filter)
}

// FindByID mocks base method.
func (m *MockPaymentMethodDatabasePort) FindByID(id string) (model.PaymentMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(model.PaymentMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPaymentMethodDatabasePortMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPaymentMethodDatabasePort)(nil).FindByID), id)
}

// Update mocks base method.
func (m *MockPaymentMethodDatabasePort) Update(id string, data model.PaymentMethodInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPaymentMethodDatabasePortMockRecorder) Update(id, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPaymentMethodDatabasePort)(nil).Update), id, data)
}
