// Code generated by MockGen. DO NOT EDIT.
// Source: internal/port/outbound/notification.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "go-template/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockNotificationDatabasePort is a mock of NotificationDatabasePort interface.
type MockNotificationDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationDatabasePortMockRecorder
}

// MockNotificationDatabasePortMockRecorder is the mock recorder for MockNotificationDatabasePort.
type MockNotificationDatabasePortMockRecorder struct {
	mock *MockNotificationDatabasePort
}

// NewMockNotificationDatabasePort creates a new mock instance.
func NewMockNotificationDatabasePort(ctrl *gomock.Controller) *MockNotificationDatabasePort {
	mock := &MockNotificationDatabasePort{ctrl: ctrl}
	mock.recorder = &MockNotificationDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationDatabasePort) EXPECT() *MockNotificationDatabasePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNotificationDatabasePort) Create(notification *model.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockNotificationDatabasePortMockRecorder) Create(notification interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNotificationDatabasePort)(nil).Create), notification)
}

// Delete mocks base method.
func (m *MockNotificationDatabasePort) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockNotificationDatabasePortMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNotificationDatabasePort)(nil).Delete), id)
}

// Find mocks base method.
func (m *MockNotificationDatabasePort) Find(filter model.NotificationFilter) ([]model.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", filter)
	ret0, _ := ret[0].([]model.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockNotificationDatabasePortMockRecorder) Find(filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockNotificationDatabasePort)(nil).Find), filter)
}

// FindAll mocks base method.
func (m *MockNotificationDatabasePort) FindAll() ([]model.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]model.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockNotificationDatabasePortMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockNotificationDatabasePort)(nil).FindAll))
}

// FindByID mocks base method.
func (m *MockNotificationDatabasePort) FindByID(id string) (*model.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*model.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockNotificationDatabasePortMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockNotificationDatabasePort)(nil).FindByID), id)
}

// FindByRecipient mocks base method.
func (m *MockNotificationDatabasePort) FindByRecipient(recipient string) ([]model.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRecipient", recipient)
	ret0, _ := ret[0].([]model.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRecipient indicates an expected call of FindByRecipient.
func (mr *MockNotificationDatabasePortMockRecorder) FindByRecipient(recipient interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRecipient", reflect.TypeOf((*MockNotificationDatabasePort)(nil).FindByRecipient), recipient)
}

// FindByStatus mocks base method.
func (m *MockNotificationDatabasePort) FindByStatus(statuses []string) ([]model.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByStatus", statuses)
	ret0, _ := ret[0].([]model.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByStatus indicates an expected call of FindByStatus.
func (mr *MockNotificationDatabasePortMockRecorder) FindByStatus(statuses interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByStatus", reflect.TypeOf((*MockNotificationDatabasePort)(nil).FindByStatus), statuses)
}

// Update mocks base method.
func (m *MockNotificationDatabasePort) Update(notification *model.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockNotificationDatabasePortMockRecorder) Update(notification interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockNotificationDatabasePort)(nil).Update), notification)
}

// MockNotificationTemplateDatabasePort is a mock of NotificationTemplateDatabasePort interface.
type MockNotificationTemplateDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationTemplateDatabasePortMockRecorder
}

// MockNotificationTemplateDatabasePortMockRecorder is the mock recorder for MockNotificationTemplateDatabasePort.
type MockNotificationTemplateDatabasePortMockRecorder struct {
	mock *MockNotificationTemplateDatabasePort
}

// NewMockNotificationTemplateDatabasePort creates a new mock instance.
func NewMockNotificationTemplateDatabasePort(ctrl *gomock.Controller) *MockNotificationTemplateDatabasePort {
	mock := &MockNotificationTemplateDatabasePort{ctrl: ctrl}
	mock.recorder = &MockNotificationTemplateDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationTemplateDatabasePort) EXPECT() *MockNotificationTemplateDatabasePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNotificationTemplateDatabasePort) Create(template *model.NotificationTemplate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", template)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockNotificationTemplateDatabasePortMockRecorder) Create(template interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNotificationTemplateDatabasePort)(nil).Create), template)
}

// Delete mocks base method.
func (m *MockNotificationTemplateDatabasePort) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockNotificationTemplateDatabasePortMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNotificationTemplateDatabasePort)(nil).Delete), id)
}

// FindAll mocks base method.
func (m *MockNotificationTemplateDatabasePort) FindAll() ([]model.NotificationTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]model.NotificationTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockNotificationTemplateDatabasePortMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockNotificationTemplateDatabasePort)(nil).FindAll))
}

// FindByID mocks base method.
func (m *MockNotificationTemplateDatabasePort) FindByID(id string) (*model.NotificationTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*model.NotificationTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockNotificationTemplateDatabasePortMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockNotificationTemplateDatabasePort)(nil).FindByID), id)
}

// FindByName mocks base method.
func (m *MockNotificationTemplateDatabasePort) FindByName(name string) (*model.NotificationTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", name)
	ret0, _ := ret[0].(*model.NotificationTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockNotificationTemplateDatabasePortMockRecorder) FindByName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockNotificationTemplateDatabasePort)(nil).FindByName), name)
}

// Update mocks base method.
func (m *MockNotificationTemplateDatabasePort) Update(template *model.NotificationTemplate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", template)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockNotificationTemplateDatabasePortMockRecorder) Update(template interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockNotificationTemplateDatabasePort)(nil).Update), template)
}
