package billing

import (
	"context"
	"errors"
	"fmt"
	"time"

	"go-template/internal/model"
	outbound_port "go-template/internal/port/outbound"
	"go-template/utils/log"
)

type BillingDomain interface {
	CreateInvoice(ctx context.Context, input model.InvoiceInput) (*model.Invoice, error)
	GetInvoice(ctx context.Context, id string) (*model.Invoice, error)
	ListInvoices(ctx context.Context, filter model.InvoiceFilter) ([]model.Invoice, error)
	UpdateInvoice(ctx context.Context, id string, input model.InvoiceInput) (*model.Invoice, error)
	DeleteInvoice(ctx context.Context, id string) error
	GenerateMonthlyInvoices(ctx context.Context, year int, month int) ([]model.Invoice, error)
	ApplyPayment(ctx context.Context, invoiceID string, amount float64) error
	CheckOverdueInvoices(ctx context.Context) ([]model.Invoice, error)
	CalculateLateFee(ctx context.Context, invoice *model.Invoice) float64
	CreateInvoiceItem(ctx context.Context, item model.InvoiceItemInput) (*model.InvoiceItem, error)
	GetInvoiceItem(ctx context.Context, id string) (*model.InvoiceItem, error)
	ListInvoiceItems(ctx context.Context, invoiceID string) ([]model.InvoiceItem, error)
}

type domain struct {
	dbPort            outbound_port.DatabasePort
	systemSettingPort outbound_port.SystemSettingDatabasePort
}

func NewBillingDomain(
	dbPort outbound_port.DatabasePort,
	systemSettingPort outbound_port.SystemSettingDatabasePort,
) BillingDomain {
	return &domain{
		dbPort:            dbPort,
		systemSettingPort: systemSettingPort,
	}
}

func (d *domain) CreateInvoice(ctx context.Context, input model.InvoiceInput) (*model.Invoice, error) {
	if len(input.Items) == 0 {
		return nil, errors.New("at least one invoice item is required")
	}

	customer, err := d.dbPort.Customer().FindByID(input.CustomerID.String())
	if err != nil {
		return nil, fmt.Errorf("customer not found: %w", err)
	}

	profile, err := d.dbPort.BandwidthProfile().FindByID(customer.ProfileID.String())
	if err != nil {
		return nil, fmt.Errorf("profile not found: %w", err)
	}

	var result interface{}
	var billingErr error
	result, billingErr = d.dbPort.DoInTransaction(func(repo outbound_port.DatabasePort) (interface{}, error) {
		issueDate := time.Now()
		if input.IssueDate != nil {
			issueDate = *input.IssueDate
		}

		dueDate := issueDate.AddDate(0, 0, 7)
		if input.DueDate != nil {
			dueDate = *input.DueDate
		}

		invoiceType := "recurring"
		if input.InvoiceType != nil {
			invoiceType = *input.InvoiceType
		}

		invoice := &model.Invoice{
			CustomerID:         input.CustomerID,
			BillingPeriodStart: input.BillingPeriodStart,
			BillingPeriodEnd:   input.BillingPeriodEnd,
			BillingMonth:       input.BillingMonth,
			BillingYear:        input.BillingYear,
			IssueDate:          issueDate,
			DueDate:            dueDate,
			PaymentDeadline:    input.PaymentDeadline,
			Subtotal:           0,
			TaxAmount:          0,
			DiscountAmount:     0,
			LateFee:            0,
			TotalAmount:        0,
			PaidAmount:         0,
			Status:             "draft",
			PaymentStatus:      "unpaid",
			InvoiceType:        invoiceType,
			IsAutoGenerated:    input.IsAutoGenerated,
			Notes:              input.Notes,
			InternalNotes:      input.InternalNotes,
		}

		subtotal := 0.0
		taxAmount := 0.0

		for _, itemInput := range input.Items {
			quantity := 1
			if itemInput.Quantity != nil {
				quantity = *itemInput.Quantity
			}

			taxRate := 0.11
			if itemInput.TaxRate != nil {
				taxRate = *itemInput.TaxRate
			}

			sortOrder := 0
			if itemInput.SortOrder != nil {
				sortOrder = *itemInput.SortOrder
			}

			item := &model.InvoiceItem{
				ItemType:            itemInput.ItemType,
				Description:         itemInput.Description,
				ProfileID:           &profile.ID,
				Quantity:            quantity,
				UnitPrice:           itemInput.UnitPrice,
				Subtotal:            itemInput.UnitPrice * float64(quantity),
				TaxRate:             taxRate,
				IsProrated:          itemInput.IsProrated,
				ProrationDays:       itemInput.ProrationDays,
				ProrationPercentage: itemInput.ProrationPercentage,
				SortOrder:           sortOrder,
			}

			itemTax := item.Subtotal * taxRate
			itemTotal := item.Subtotal + itemTax

			subtotal += item.Subtotal
			taxAmount += itemTax

			err := repo.InvoiceItem().Create(item)
			if err != nil {
				return nil, err
			}

			invoice.TotalAmount += itemTotal
		}

		invoice.Subtotal = subtotal
		invoice.TaxAmount = taxAmount

		if input.Subtotal != nil {
			invoice.Subtotal = *input.Subtotal
		}
		if input.TaxAmount != nil {
			invoice.TaxAmount = *input.TaxAmount
		}
		if input.TotalAmount != nil {
			invoice.TotalAmount = *input.TotalAmount
		}
		if input.LateFee != nil {
			invoice.LateFee = *input.LateFee
		}

		if input.Status != nil {
			invoice.Status = *input.Status
		}

		invoice.InvoiceNumber = generateInvoiceNumber()
		invoice.BillingMonth = input.BillingMonth
		invoice.BillingYear = input.BillingYear

		model.InvoicePrepare(invoice)

		err := repo.Invoice().Create(invoice)
		if err != nil {
			return nil, err
		}

		return invoice, nil
	})

	if billingErr != nil {
		return nil, billingErr
	}

	return result.(*model.Invoice), nil
}

func (d *domain) GetInvoice(ctx context.Context, id string) (*model.Invoice, error) {
	return d.dbPort.Invoice().FindByID(id)
}

func (d *domain) ListInvoices(ctx context.Context, filter model.InvoiceFilter) ([]model.Invoice, error) {
	if filter.IsEmpty() {
		return d.dbPort.Invoice().FindAll()
	}
	return d.dbPort.Invoice().Find(filter)
}

func (d *domain) UpdateInvoice(ctx context.Context, id string, input model.InvoiceInput) (*model.Invoice, error) {
	var result interface{}
	var err error
	result, err = d.dbPort.DoInTransaction(func(repo outbound_port.DatabasePort) (interface{}, error) {
		invoice, err := repo.Invoice().FindByID(id)
		if err != nil {
			return nil, errors.New("invoice not found")
		}

		if input.Status != nil {
			invoice.Status = *input.Status
		}
		if input.PaymentDate != nil {
			invoice.PaymentDate = input.PaymentDate
		}
		if input.PaidAmount != nil {
			invoice.PaidAmount = *input.PaidAmount
		}
		if input.Notes != nil {
			invoice.Notes = input.Notes
		}
		if input.InternalNotes != nil {
			invoice.InternalNotes = input.InternalNotes
		}

		err = repo.Invoice().Update(invoice)
		if err != nil {
			return nil, err
		}

		if input.Status != nil && (*input.Status == "paid" || *input.Status == "refunded") {
			paymentDate := time.Now()
			invoice.PaymentDate = &paymentDate
		}

		return invoice, nil
	})

	if err != nil {
		return nil, err
	}

	return result.(*model.Invoice), nil
}

func (d *domain) DeleteInvoice(ctx context.Context, id string) error {
	items, err := d.dbPort.InvoiceItem().FindByInvoiceID(id)
	if err != nil {
		return err
	}

	if len(items) > 0 {
		return errors.New("cannot delete invoice with existing items")
	}

	return d.dbPort.Invoice().Delete(id)
}

func (d *domain) GenerateMonthlyInvoices(ctx context.Context, year int, month int) ([]model.Invoice, error) {
	dueDaysSetting, _ := d.systemSettingPort.FindByKey("invoice.due_days")
	dueDays := dueDaysSetting.GetInt(7)

	customers, err := d.dbPort.Customer().FindAll()
	if err != nil {
		return nil, err
	}

	var generatedInvoices []model.Invoice

	for _, customer := range customers {
		if customer.Status != "active" && customer.Status != "isolated" {
			continue
		}

		if customer.ExpiryDate == nil {
			continue
		}

		expiryDate := time.Date(customer.ExpiryDate.Year(), customer.ExpiryDate.Month(), 1, 0, 0, 0, 0, time.Local)
		nextMonth := expiryDate.AddDate(0, 1, 0)

		if nextMonth.Before(time.Now()) {
			continue
		}

		profile, err := d.dbPort.BandwidthProfile().FindByID(customer.ProfileID.String())
		if err != nil {
			log.WithContext(ctx).Warn(fmt.Sprintf("Skipping customer %s: no profile found", customer.CustomerCode))
			continue
		}

		if profile.Category != "pppoe" {
			log.WithContext(ctx).Warn(fmt.Sprintf("Skipping customer %s: profile is not PPPoE", customer.CustomerCode))
			continue
		}

		billingStart := expiryDate
		billingEnd := expiryDate.AddDate(0, 1, -1)

		invoice := model.Invoice{
			CustomerID:         customer.ID,
			BillingPeriodStart: billingStart,
			BillingPeriodEnd:   billingEnd,
			BillingMonth:       func() *int { m := int(billingStart.Month()); return &m }(),
			BillingYear:        func() *int { y := int(billingStart.Year()); return &y }(),
			IssueDate:          time.Now(),
			DueDate:            billingStart.AddDate(0, dueDays, 0),
			PaymentDeadline:    func() *time.Time { t := billingStart.AddDate(0, dueDays, 0); return &t }(),
			Subtotal:           profile.PriceMonthly,
			TaxAmount:          profile.PriceMonthly * profile.TaxRate,
			DiscountAmount:     0,
			LateFee:            0,
			TotalAmount:        profile.PriceMonthly + (profile.PriceMonthly * profile.TaxRate),
			PaidAmount:         0,
			Status:             "draft",
			PaymentStatus:      "unpaid",
			InvoiceType:        "recurring",
		}

		isAutoGen := true
		invoice.IsAutoGenerated = &isAutoGen
		taxRate := profile.TaxRate
		isProrated := false
		item := model.InvoiceItem{
			ItemType:    "subscription",
			Description: fmt.Sprintf("Langgananan %s - %s", profile.Name, customer.FullName),
			ProfileID:   &profile.ID,
			Quantity:    1,
			UnitPrice:   profile.PriceMonthly,
			Subtotal:    profile.PriceMonthly,
			TaxRate:     taxRate,
			TaxAmount:   profile.PriceMonthly * taxRate,
			Total:       invoice.TotalAmount,
			IsProrated:  &isProrated,
			SortOrder:   1,
		}

		err = d.dbPort.InvoiceItem().Create(&item)
		if err != nil {
			log.WithContext(ctx).Error(fmt.Sprintf("Failed to create invoice item for customer %s: %v", customer.CustomerCode, err))
			continue
		}

		invoice.InvoiceNumber = generateInvoiceNumber()
		model.InvoicePrepare(&invoice)

		err = d.dbPort.Invoice().Create(&invoice)
		if err != nil {
			log.WithContext(ctx).Error(fmt.Sprintf("Failed to generate invoice for customer %s: %v", customer.CustomerCode, err))
		} else {
			log.WithContext(ctx).Info(fmt.Sprintf("Generated invoice %s for customer %s", invoice.InvoiceNumber, customer.CustomerCode))
		}

		generatedInvoices = append(generatedInvoices, invoice)
	}

	return generatedInvoices, nil
}

func (d *domain) ApplyPayment(ctx context.Context, invoiceID string, amount float64) error {
	_, err := d.dbPort.DoInTransaction(func(repo outbound_port.DatabasePort) (interface{}, error) {
		invoice, err := repo.Invoice().FindByID(invoiceID)
		if err != nil {
			return nil, errors.New("invoice not found")
		}

		newPaidAmount := invoice.PaidAmount + amount
		if newPaidAmount > invoice.TotalAmount {
			newPaidAmount = invoice.TotalAmount
		}

		invoice.PaidAmount = newPaidAmount

		if invoice.PaidAmount >= invoice.TotalAmount {
			invoice.PaymentStatus = "paid"
			paymentDate := time.Now()
			invoice.PaymentDate = &paymentDate
		} else if newPaidAmount > 0 {
			invoice.PaymentStatus = "partial"
		}

		err = repo.Invoice().Update(invoice)
		if err != nil {
			return nil, err
		}

		return nil, nil
	})

	return err
}

func (d *domain) CheckOverdueInvoices(ctx context.Context) ([]model.Invoice, error) {
	return d.dbPort.Invoice().FindOverdue()
}

func (d *domain) CalculateLateFee(ctx context.Context, invoice *model.Invoice) float64 {
	lateFeeSetting, _ := d.systemSettingPort.FindByKey("invoice.late_fee_enabled")
	lateFeeEnabled := lateFeeSetting.GetBool(false)

	if !lateFeeEnabled {
		return 0
	}

	lateFeeAmountSetting, _ := d.systemSettingPort.FindByKey("invoice.late_fee_amount")
	lateFeeAmount := lateFeeAmountSetting.GetInt(0)

	daysOverdue := int(time.Since(invoice.DueDate).Hours() / 24)

	if daysOverdue <= 0 {
		return 0
	}

	return float64(daysOverdue) * float64(lateFeeAmount)
}

func (d *domain) CreateInvoiceItem(ctx context.Context, item model.InvoiceItemInput) (*model.InvoiceItem, error) {
	quantity := 1
	if item.Quantity != nil {
		quantity = *item.Quantity
	}

	taxRate := 0.11
	if item.TaxRate != nil {
		taxRate = *item.TaxRate
	}

	sortOrder := 0
	if item.SortOrder != nil {
		sortOrder = *item.SortOrder
	}

	subtotal := item.UnitPrice * float64(quantity)
	taxAmount := subtotal * taxRate
	total := subtotal + taxAmount

	invoiceItem := model.InvoiceItem{
		ItemType:            item.ItemType,
		Description:         item.Description,
		ProfileID:           item.ProfileID,
		Quantity:            quantity,
		UnitPrice:           item.UnitPrice,
		Subtotal:            subtotal,
		TaxRate:             taxRate,
		TaxAmount:           taxAmount,
		Total:               total,
		IsProrated:          item.IsProrated,
		ProrationDays:       item.ProrationDays,
		ProrationPercentage: item.ProrationPercentage,
		SortOrder:           sortOrder,
	}

	err := d.dbPort.InvoiceItem().Create(&invoiceItem)
	if err != nil {
		return nil, err
	}

	return &invoiceItem, nil
}

func (d *domain) GetInvoiceItem(ctx context.Context, id string) (*model.InvoiceItem, error) {
	return d.dbPort.InvoiceItem().FindByID(id)
}

func (d *domain) ListInvoiceItems(ctx context.Context, invoiceID string) ([]model.InvoiceItem, error) {
	return d.dbPort.InvoiceItem().FindByInvoiceID(invoiceID)
}

func generateInvoiceNumber() string {
	return fmt.Sprintf("INV-%s-%s-%04d", time.Now().Format("200601"), time.Now().Format("1504"), time.Now().UnixNano()%10000)
}
