package billing

import (
	"context"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/palantir/stacktrace"
	"github.com/shopspring/decimal"

	"go-template/internal/model"
	outbound_port "go-template/internal/port/outbound"
)

type BillingDomain interface {
	CreateInvoice(ctx context.Context, input model.InvoiceInput) (*model.Invoice, error)
	FindByID(ctx context.Context, id string) (*model.Invoice, error)
	FindByFilter(ctx context.Context, filter model.InvoiceFilter) ([]model.Invoice, error)
	UpdateStatus(ctx context.Context, id string, status model.InvoiceStatus) error
	CancelInvoice(ctx context.Context, id string, reason string) error
	GenerateMonthlyInvoices(ctx context.Context, year int, month int) ([]model.Invoice, error)
	ApplyPayment(ctx context.Context, invoiceID string, amount decimal.Decimal, paymentDate time.Time, paymentMethod string) error
	CheckOverdueInvoices(ctx context.Context) ([]model.Invoice, error)
	CalculateLateFee(ctx context.Context, invoice *model.Invoice) (decimal.Decimal, error)
	GetMonthlyRevenue(ctx context.Context, year int, month int) (map[string]interface{}, error)
}

type billingDomain struct {
	databasePort outbound_port.DatabasePort
}

func NewBillingDomain(
	databasePort outbound_port.DatabasePort,
) BillingDomain {
	return &billingDomain{
		databasePort: databasePort,
	}
}

func (d *billingDomain) CreateInvoice(ctx context.Context, input model.InvoiceInput) (*model.Invoice, error) {
	// Validate input
	if input.CustomerID == uuid.Nil {
		return nil, stacktrace.NewError("customer ID is required")
	}
	if len(input.Items) == 0 {
		return nil, stacktrace.NewError("at least one invoice item is required")
	}

	// Get customer
	databaseCustomerPort := d.databasePort.Customer()
	customers, err := databaseCustomerPort.FindByFilter(model.CustomerFilter{
		IDs: []uuid.UUID{input.CustomerID},
	})
	if err != nil {
		return nil, stacktrace.Propagate(err, "failed to find customer")
	}
	if len(customers) == 0 {
		return nil, stacktrace.NewError("customer not found")
	}
	customer := &customers[0]

	// Get billing period
	year := input.BillingPeriodStart.Year()
	month := int(input.BillingPeriodStart.Month())

	// Generate invoice number
	databaseInvoicePort := d.databasePort.Invoice()
	sequence, err := databaseInvoicePort.GetNextSequenceNumber(year, month)
	if err != nil {
		return nil, stacktrace.Propagate(err, "failed to get sequence number")
	}

	invoiceNumber := model.GenerateInvoiceNumber(year, month, sequence)

	// Create invoice
	invoice := &model.Invoice{
		ID:                 uuid.New(),
		InvoiceNumber:      invoiceNumber,
		CustomerID:         input.CustomerID,
		BillingPeriodStart: input.BillingPeriodStart,
		BillingPeriodEnd:   input.BillingPeriodEnd,
		BillingMonth:       month,
		BillingYear:        year,
		IssueDate:          input.IssueDate,
		DueDate:            input.DueDate,
		DiscountAmount:     input.DiscountAmount,
		InvoiceType:        input.InvoiceType,
		Status:             model.InvoiceStatusDraft,
		PaymentStatus:      model.PaymentStatusUnpaid,
		IsAutoGenerated:    false,
		Notes:              input.Notes,
		InternalNotes:      input.InternalNotes,
	}

	// Create invoice items
	var items []model.InvoiceItem
	for i, itemInput := range input.Items {
		item := model.InvoiceItem{
			ID:                  uuid.New(),
			ItemType:            itemInput.ItemType,
			Description:         itemInput.Description,
			ProfileID:           itemInput.ProfileID,
			Quantity:            itemInput.Quantity,
			UnitPrice:           itemInput.UnitPrice,
			TaxRate:             itemInput.TaxRate,
			IsProrated:          itemInput.IsProrated,
			ProrationDays:       itemInput.ProrationDays,
			ProrationPercentage: itemInput.ProrationPercentage,
			SortOrder:           i,
		}

		// Set default tax rate if not provided
		if item.TaxRate.IsZero() {
			// Get tax rate from system settings
			settingPort := d.databasePort.SystemSetting()
			taxSetting, err := settingPort.GetByKey("invoice.tax_rate")
			if err == nil && taxSetting != nil {
				taxRate, err := taxSetting.GetFloat()
				if err == nil {
					item.TaxRate = decimal.NewFromFloat(taxRate)
				}
			}

			if item.TaxRate.IsZero() {
				item.TaxRate = decimal.NewFromFloat(0.11) // Default 11%
			}
		}

		// Calculate item totals
		item.CalculateItemTotals()

		items = append(items, item)
	}

	// Calculate late fee if overdue
	if time.Now().After(invoice.DueDate) {
		lateFee, err := d.CalculateLateFee(ctx, invoice)
		if err == nil {
			invoice.LateFee = lateFee
		}
	}

	// Set items to invoice and calculate totals
	invoice.Items = items
	invoice.CalculateTotals()

	// Create invoice with items in transaction
	err = databaseInvoicePort.CreateWithItems(invoice, items)
	if err != nil {
		return nil, stacktrace.Propagate(err, "failed to create invoice")
	}

	return invoice, nil
}

func (d *billingDomain) FindByID(ctx context.Context, id string) (*model.Invoice, error) {
	if id == "" {
		return nil, stacktrace.NewError("id is required")
	}

	invoiceID, err := uuid.Parse(id)
	if err != nil {
		return nil, stacktrace.Propagate(err, "invalid uuid format")
	}

	databaseInvoicePort := d.databasePort.Invoice()
	invoices, err := databaseInvoicePort.FindByFilter(model.InvoiceFilter{
		IDs: []uuid.UUID{invoiceID},
	})
	if err != nil {
		return nil, stacktrace.Propagate(err, "failed to find invoice")
	}

	if len(invoices) == 0 {
		return nil, stacktrace.NewError("invoice not found")
	}

	return &invoices[0], nil
}

func (d *billingDomain) FindByFilter(ctx context.Context, filter model.InvoiceFilter) ([]model.Invoice, error) {
	databaseInvoicePort := d.databasePort.Invoice()
	invoices, err := databaseInvoicePort.FindByFilter(filter)
	if err != nil {
		return nil, stacktrace.Propagate(err, "failed to find invoices")
	}

	return invoices, nil
}

func (d *billingDomain) UpdateStatus(ctx context.Context, id string, status model.InvoiceStatus) error {
	// Find invoice
	invoice, err := d.FindByID(ctx, id)
	if err != nil {
		return stacktrace.Propagate(err, "failed to find invoice")
	}

	// Update status
	invoice.Status = status
	invoice.UpdatedAt = time.Now()

	databaseInvoicePort := d.databasePort.Invoice()
	err = databaseInvoicePort.Update(invoice)
	if err != nil {
		return stacktrace.Propagate(err, "failed to update invoice status")
	}

	return nil
}

func (d *billingDomain) CancelInvoice(ctx context.Context, id string, reason string) error {
	// Find invoice
	invoice, err := d.FindByID(ctx, id)
	if err != nil {
		return stacktrace.Propagate(err, "failed to find invoice")
	}

	// Check if invoice can be cancelled
	if invoice.Status == model.InvoiceStatusPaid {
		return stacktrace.NewError("cannot cancel a paid invoice")
	}

	// Update status
	invoice.Status = model.InvoiceStatusCancelled
	invoice.InternalNotes = fmt.Sprintf("%s\n\nCancellation reason: %s", invoice.InternalNotes, reason)
	invoice.UpdatedAt = time.Now()

	databaseInvoicePort := d.databasePort.Invoice()
	err = databaseInvoicePort.Update(invoice)
	if err != nil {
		return stacktrace.Propagate(err, "failed to cancel invoice")
	}

	return nil
}

func (d *billingDomain) GenerateMonthlyInvoices(ctx context.Context, year int, month int) ([]model.Invoice, error) {
	// Check if invoices already generated for this period
	databaseInvoicePort := d.databasePort.Invoice()
	count, err := databaseInvoicePort.CountInvoicesByPeriod(year, month)
	if err != nil {
		return nil, stacktrace.Propagate(err, "failed to check existing invoices")
	}

	if count > 0 {
		return nil, stacktrace.NewError("invoices already generated for %d-%02d", year, month)
	}

	// Get all active customers
	databaseCustomerPort := d.databasePort.Customer()
	customers, err := databaseCustomerPort.FindByFilter(model.CustomerFilter{
		Statuses: []model.CustomerStatus{
			model.CustomerStatusActive,
		},
	})
	if err != nil {
		return nil, stacktrace.Propagate(err, "failed to find active customers")
	}

	if len(customers) == 0 {
		return nil, stacktrace.NewError("no active customers found")
	}

	// Get system settings
	settingPort := d.databasePort.SystemSetting()
	dueDaysSetting, _ := settingPort.GetByKey("invoice.due_days")
	dueDays := 7
	if dueDaysSetting != nil {
		dueDays = dueDaysSetting.GetIntDefault(7)
	}

	var generatedInvoices []model.Invoice

	// Generate invoice for each customer
	for _, customer := range customers {
		// Skip if customer has no profile
		if customer.ProfileID == nil {
			continue
		}

		// Get profile
		databaseBandwidthProfilePort := d.databasePort.BandwidthProfile()
		profiles, err := databaseBandwidthProfilePort.FindByFilter(model.BandwidthProfileFilter{
			IDs: []uuid.UUID{*customer.ProfileID},
		})
		if err != nil || len(profiles) == 0 {
			continue
		}
		profile := &profiles[0]

		// Calculate billing period
		billingStart := time.Date(year, time.Month(month), 1, 0, 0, 0, 0, time.Local)
		billingEnd := billingStart.AddDate(0, 1, -1)

		// Issue date is today
		issueDate := time.Now()

		// Due date is issue date + due days
		dueDate := issueDate.AddDate(0, 0, dueDays)

		// Create invoice items
		items := []model.InvoiceItemInput{
			{
				ItemType:    model.InvoiceItemTypeSubscription,
				Description: fmt.Sprintf("Berlangganan Internet - %s", profile.Name),
				ProfileID:   customer.ProfileID,
				Quantity:    1,
				UnitPrice:   profile.PriceMonthly,
			},
		}

		// Create invoice
		invoiceInput := model.InvoiceInput{
			CustomerID:         customer.ID,
			BillingPeriodStart: billingStart,
			BillingPeriodEnd:   billingEnd,
			IssueDate:          issueDate,
			DueDate:            dueDate,
			InvoiceType:        model.InvoiceTypeRecurring,
			Items:              items,
		}

		invoice, err := d.CreateInvoice(ctx, invoiceInput)
		if err != nil {
			// Log error but continue with other customers
			continue
		}

		// Mark as auto-generated
		invoice.IsAutoGenerated = true
		invoice.Status = model.InvoiceStatusSent

		err = databaseInvoicePort.Update(invoice)
		if err != nil {
			continue
		}

		generatedInvoices = append(generatedInvoices, *invoice)
	}

	return generatedInvoices, nil
}

func (d *billingDomain) ApplyPayment(ctx context.Context, invoiceID string, amount decimal.Decimal, paymentDate time.Time, paymentMethod string) error {
	// Validate amount
	if amount.LessThanOrEqual(decimal.Zero) {
		return stacktrace.NewError("payment amount must be greater than zero")
	}

	// Find invoice
	invoice, err := d.FindByID(ctx, invoiceID)
	if err != nil {
		return stacktrace.Propagate(err, "failed to find invoice")
	}

	// Check if invoice can accept payment
	if invoice.Status == model.InvoiceStatusCancelled || invoice.Status == model.InvoiceStatusRefunded {
		return stacktrace.NewError("cannot apply payment to cancelled or refunded invoice")
	}

	// Apply payment
	databaseInvoicePort := d.databasePort.Invoice()
	err = databaseInvoicePort.UpdatePaymentStatus(invoiceID, amount.String(), paymentDate, paymentMethod)
	if err != nil {
		return stacktrace.Propagate(err, "failed to apply payment")
	}

	return nil
}

func (d *billingDomain) CheckOverdueInvoices(ctx context.Context) ([]model.Invoice, error) {
	databaseInvoicePort := d.databasePort.Invoice()
	invoices, err := databaseInvoicePort.FindOverdueInvoices()
	if err != nil {
		return nil, stacktrace.Propagate(err, "failed to find overdue invoices")
	}

	// Update status to overdue
	for i := range invoices {
		if invoices[i].Status != model.InvoiceStatusOverdue {
			invoices[i].Status = model.InvoiceStatusOverdue
			err = databaseInvoicePort.Update(&invoices[i])
			if err != nil {
				// Log error but continue
				continue
			}
		}
	}

	return invoices, nil
}

func (d *billingDomain) CalculateLateFee(ctx context.Context, invoice *model.Invoice) (decimal.Decimal, error) {
	// Get late fee settings
	settingPort := d.databasePort.SystemSetting()

	// Check if late fee is enabled
	enabledSetting, err := settingPort.GetByKey("invoice.late_fee_enabled")
	if err != nil || enabledSetting == nil {
		return decimal.Zero, nil
	}

	enabled := enabledSetting.GetBoolDefault(false)
	if !enabled {
		return decimal.Zero, nil
	}

	// Get late fee amount
	amountSetting, err := settingPort.GetByKey("invoice.late_fee_amount")
	if err != nil || amountSetting == nil {
		return decimal.Zero, nil
	}

	lateFeeAmount := amountSetting.GetFloat64Default(0)
	if lateFeeAmount <= 0 {
		return decimal.Zero, nil
	}

	return decimal.NewFromFloat(lateFeeAmount), nil
}

func (d *billingDomain) GetMonthlyRevenue(ctx context.Context, year int, month int) (map[string]interface{}, error) {
	databaseInvoicePort := d.databasePort.Invoice()
	revenue, err := databaseInvoicePort.GetMonthlyRevenue(year, month)
	if err != nil {
		return nil, stacktrace.Propagate(err, "failed to get monthly revenue")
	}

	return revenue, nil
}
